### ISSUE TITLE
The first time I create a record, none of the contents are retained

### ISSUE THREAD

**Issue by 0spinboson** [bolt/core#1005]
Currently, every time I create a new record, none of the contents are saved until the record exists in the database (using bolt 4rc1, php 7.2, mariadb 10.2). This problem has existed I think since I updated from beta 4 to beta 5, and it may have been introduced with that, though I don't know this for sure.

**Comment by I-Valchev** [comment]
@0spinboson can you please explain better what do you mean when you say "until the record exists in the database"?

The expected behaviour is that when you create a new record, none of the contents (or the record itself) will be processed and persisted (saved) until you press the "Save changes" button.

**Comment by 0spinboson** [comment]
I mean I click 'create new', then enter some data, then click save. it creates the record, but saves none of the data until after clicking save that first time. Afterwards, saving data works as expected.

**Comment by I-Valchev** [comment]
Can you please include some screenshots with your description so I can see more clearly what is going on? :) Thanks!

**Comment by 0spinboson** [comment]
Screen 1:
![bolt test](https://user-images.githubusercontent.com/21077532/73766889-fc21ad80-4776-11ea-8695-023d459111f5.png)
after clicking save, it 'refreshes' and shows:
![screen 2](https://user-images.githubusercontent.com/21077532/73766944-0a6fc980-4777-11ea-96e8-079ae29e83b2.png)

**Comment by bobdenotter** [comment]
@0spinboson I've also not been able to confirm this.. Maybe it's a glitch from updating your existing install, and you missed one of the changes we had to make in config? (the `UPDATE.md` in bolt/project should detail all)

**Comment by 0spinboson** [comment]
could be, of course, but everything in update.md matches what I have in my local files.

**Comment by bobdenotter** [comment]
@0spinboson The linked issue was resolved, right? I just tried again to reproduce this issue, and wasn't succesful. Is still still hapenning on your end?

**Comment by 0spinboson** [comment]
yes, it was solved. I've not encountered it recently.
