### ISSUE TITLE
Exception on empty front page

### ISSUE THREAD

**Issue by izzyu91** [bolt/core#1056]
I am not sure in which project to file this bug, so I will simply file it here:

After installing bolt 4 without dummy data the front page is returned with an exception. The relevant part of the exception should be:

```
Twig\Error\SyntaxError:
Unknown "isallowed" function.

  at public/theme/base-2018/partials/_no_content.twig:6
  at Twig\ExpressionParser->getFunctionNodeClass('isallowed', 6)
     (vendor/twig/twig/src/ExpressionParser.php:446)
  at Twig\ExpressionParser->getFunctionNode('isallowed', 6)
     (vendor/twig/twig/src/ExpressionParser.php:235)
  at Twig\ExpressionParser->parsePrimaryExpression()
     (vendor/twig/twig/src/ExpressionParser.php:175)
...
```

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | seen on RC1 and RC2
| Install type                   |  composer
| BC Break                     | no 
| PHP version                 | 7.3
| Web server                  |  Symfony built-in
| Theme                         | base-2018

Reproduction
------------

### Bug summary

A call to an undefined method in Twig.

<img width="1053" alt="Bildschirmfoto 2020-02-11 um 20 54 24" src="https://user-images.githubusercontent.com/9365577/74273462-cc434e80-4d10-11ea-8a99-935016789508.png">

### Steps to reproduce

Install bolt via composer without dummy data and call the front page.

### Expected result

Render the page without an exception.

**Comment by bobdenotter** [comment]
Fix is in the queue: #1058
