### ISSUE TITLE
Update to RC5 / Clean install broken - Bolt\Command\CopyAssetsCommand

### ISSUE THREAD

**Issue by wgaulke** [bolt/core#1121]
Update from RC3 -> to RC5 breaks installation. Happens also in clean install.

Details
-------

Error message:

> Cannot autowire service "Bolt\Command\CopyAssetsCommand": argument "$public  
> !!    Folder" of method "__construct()" is type-hinted "string", you should confi  
> !!    gure its value explicitly.    

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0 RC5
| Install type                   |  Composer install 
| PHP version                 |  7.3 
| Web server                  | Apache / Nginx 

Reproduction
------------

Update composer installation of RC3 -> RC5. 

I did try to create a new composer project and update it to RC5 -> same error.

**Comment by bobdenotter** [comment]
Hi, this change can be fixed acccording to https://github.com/bolt/project/blob/master/UPDATE.md#publicfolder-of-method-__construct

> I did try to create a new composer project and update it to RC5 -> same error.

Hmm, if you do a _new_ `composer create-project`, it should be correct out of the box, right? 🤔

**Comment by wgaulke** [comment]
Strangely, a new composer create-project loads 

> bolt/core (4.0.0-rc.4)

But greets me afterwards with RC3. Composer update then breaks it again.
I am not that much of an composer expert, but I expected to create it a new RC5 install.

**Comment by wgaulke** [comment]
https://github.com/bolt/project/blob/master/UPDATE.md#publicfolder-of-method-__construct

Did the trick. Thanks, closing the issue.
