### ISSUE TITLE
On second thought: The login page _shouldn't_ display the password strength.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#1130]
Because it's not relevant here. The user should just input their password, whatever it is. 

![Screenshot 2020-02-25 at 06 53 10](https://user-images.githubusercontent.com/1833361/75218859-92a42600-579b-11ea-800b-708b88fd31b4.png)

**Comment by I-Valchev** [comment]
Strange... I did set it to false [here](https://github.com/bolt/core/pull/1119/files#diff-44948a1caf3eafdace046f7144b85152R59).
I'll check that :-)

**Comment by bobdenotter** [comment]
@I-Valchev the problem is with Twig being stupid.. `false|default()|json_encode` parses to `""` instead of `false`. 

Fixed in #1133.
