### ISSUE TITLE
Bundled extensions

### ISSUE THREAD

**Issue by mbursa** [bolt/core#1134]
Does/will Bolt4 support the same concept of bundled extensions of Bolt3?

I tried to port some of my bolt3 bundles, but it does not work as there is no bolt/core/src/Extensions/SimpleExtension.php.

**Comment by bobdenotter** [comment]
I'm still working on documentation, but this is certainly the case. Bolt 4 is a Symfony app, so you can use Autowiring and Dependency Injection, in your own project. Very briefly: You can create a new file `src/Extension.php`: 

```php
<?php


namespace App;


use Bolt\Extension\BaseExtension;

class Extension extends BaseExtension
{
    public function getName(): string
    {
        return 'FooBar Extension';
    }

    public function initialize()
    {
        // Do stuff
    }
}
```

Then, run `bin/console extensions:list` and you should see an output like: 

```
 Currently installed extensions:
 ------------------------------------- --------------------------
  Class                                 Extension name
 ------------------------------------- --------------------------
  App\Extension                         FooBar Extension
  BobdenOtter\WeatherWidget\Extension   Dashboard Weather Widget
  Bolt\NewsWidget\Extension             Dashboard News Widget
 ------------------------------------- --------------------------
```

There you go, working local Extension! :-)

From here, you can inspect `vendor/bolt/core/src/Extension/BaseExtension.php` to see more about available methods.

**Comment by mbursa** [comment]
Many thanks. I figured out the `class Extension extends BaseExtension`, but not the `namespace App` part, so nothing was loaded.

Similarly, I am able to add a Twig extension:

```php
namespace App;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

class MyExtension extends AbstractExtension
{
    public function getFunctions()
    {
        return [
            new TwigFunction('myfunction', [$this, 'my_function']),
        ];
    }

    public function my_function()
    {
        return 'ok';
    }
}
```

... but can I register twig related stuff (like a function) from BaseExtension's `initialize()` function (or any other) or is the above the right way? `addTwigExtension` is marked as depreciated in 'BaseExtension`.

**Comment by bobdenotter** [comment]
For things like Twig extensions, Commands, Event Listeners and Subscribers, you can add them "as is". The `src` is set up to be used as Services. If you add a Twig extension (that `extends Twig\Extension\AbstractExtension`), it should be picked up automatically: https://github.com/bolt/reference-extension/blob/master/src/Twig.php
