### ISSUE TITLE
the backend listing template iterates over title in the excerpt

### ISSUE THREAD

**Issue by 0spinboson** [bolt/core#1135]
on the dashboard (etc.) view, the title is repeated at the start of the content excerpt. (Also, inserting a linebreak after the title would not hurt :) )

**Comment by bobdenotter** [comment]
You know the drill: Screenshots help! https://bolt.tips/entry/reporting-issues-effectively

**Comment by 0spinboson** [comment]
![title](https://user-images.githubusercontent.com/21077532/75339309-8bab0f80-5890-11ea-90f7-44593b7df920.png)

**Comment by bobdenotter** [comment]
Ah, I see it now! Thanks, we'll get that fixed.
