### ISSUE TITLE
Project install comes with non-writable public/files folder

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1174]
Not sure what's the best place to put this, but the `files` folder under `public` comes with missing write permissions, which makes image/file upload break.

**Comment by bobdenotter** [comment]
This can't really be done in the "project" itself. We _can_ set the permissions in git, but they don't stick when somebody installs later on using composer or a distribution file. Instead, people will have to read the docs: https://docs.bolt.cm/4.0/installation/permissions

**Comment by bobdenotter** [comment]
Closing this. Fixed in docs. :-)
