### ISSUE TITLE
Unexpected results on Contenttype sorting

### ISSUE THREAD

**Issue by JTNMW** [bolt/core#1190]
**Backend:**

- Sorting contenttypes on defined fields (eg `sort: title`) shows unexpected results. it is not apparent what sort is being based on.

- Sorting contenttypes using columns in Bolt_content table (eg `sort: id`, `sort: -createdAt`) works and gives correct results. 

**Frontend:**

- Listing.twig  - sort defaults to `sort: id` regardless of what is set in the `contenttype.yaml`.

- `{% setcontent entries = 'entries' orderby 'title' %}` also does not show correctly sorted results. This replicates the problems encountered at the backend. 

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version |  4.0.0 rc 6 / rc 7
| Install type                   |  Composer install 
| BC Break                     | no
| PHP version                 |  7.4 
| Web server                  | Apache 
| For UX/UI issues        | n/a

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

As above

### Specifics

screen shot 1: incorrect sort order using defined field
![screenshot_1](https://user-images.githubusercontent.com/57093734/76754433-05d90080-677a-11ea-81a3-9cc02c2d45b5.png)

screen shot 2: correct sort order using id, created date etc
![screenshot 2](https://user-images.githubusercontent.com/57093734/76754620-5bada880-677a-11ea-9cf3-e35f61c9c369.png)

### Expected result

Ability to sort results based on defined fields of contenttype.

**Comment by bobdenotter** [comment]
Additional notes: This only shows up when using MySQL. SQLite works as expected.
