### ISSUE TITLE
Label in "edit block" is in Dutch

### ISSUE THREAD

**Issue by martynwheeler** [bolt/core#1194]
The label for title in edit block is in Dutch "De Titel:".  I assume this is not the expected behaviour.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | legacy / 4.0 / 4.1 / master
| Install type                   |  Zip or tar install / Composer install / GitHub checkout
| BC Break                     | yes/no
| PHP version                 | 7.2 / 7.3 / 7.4 |
| Web server                  | Apache / Nginx / Built-in, version [ version ]
| For UX/UI issues        | Browser name and version

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by bobdenotter** [comment]
Fixed in this commit: https://github.com/bolt/project/commit/c46881eb247eae4ca7a4fd3eec9cdfed2b1174a6

Thanks! 👍
