### ISSUE TITLE
Image attributes should not be misleading when attributes are not set

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1197]
Currently, if the image `filaname` attribute is empty, the `path` and `url` are "semi-set". This means that in the API, there is no way to check if the url is empty or not. I should be able to check if URL is empty to be able to decide how to handle this case.

Example:

```
"featured_image": {
                "media": "",
                "filename": "",
                "alt": "",
                "path": "/files/",
                "url": "https://example.org/files/",
                "thumbnail": "/assets/images/placeholder.png",
                "fieldname": "featured_image"
              },
```

Expected:
```
"featured_image": {
                "media": "",
                "filename": "",
                "alt": "",
                "path": "",
                "url": "",
                "thumbnail": "/assets/images/placeholder.png",
                "fieldname": "featured_image"
              },
```

(As a side note: why is the thumbnail set to the placeholder?)

**Comment by bobdenotter** [comment]
I don't think the placeholder needs to be set, if there's no image to begin with.. I'll clear that one too. :-)
