### ISSUE TITLE
setcontent  by taxonomies not functioning

### ISSUE THREAD

**Issue by JTNMW** [bolt/core#1217]
Fetching content by taxonomies does not return results. It's not functioning for 'categories', 'groups' or 'tags'

eg
{% setcontent entries = 'Entries' where { categories: 'love'} %}
{% setcontent pages = 'Pages' where { groups: 'meta'} %}

returns no content.

**Comment by bobdenotter** [comment]
Are your certain the contentype is correct.. Does `{% setcontent entries = 'entries' where { categories: 'love'} %}` work? 

Can you post the output of `{% setcontent entries = 'entries' where { categories: 'love'} printquery %}`

**Comment by JTNMW** [comment]
All taken from fresh composer bolt project install and setup (SQLite).

content type config:
![Screenshot 2020-03-25 at 14 14 47](https://user-images.githubusercontent.com/57093734/77547436-1b9aa400-6ea5-11ea-9547-6924f413f473.png)
 

entry with categories
![Screenshot 2020-03-25 at 14 19 35](https://user-images.githubusercontent.com/57093734/77547561-41c04400-6ea5-11ea-8f5c-f79361f0e81d.png)

twig:
![Screenshot 2020-03-25 at 14 32 08](https://user-images.githubusercontent.com/57093734/77547734-7d5b0e00-6ea5-11ea-9da0-8a376f01cc9d.png)

output:

![Screenshot 2020-03-25 at 14 17 21](https://user-images.githubusercontent.com/57093734/77547895-b09d9d00-6ea5-11ea-84fb-60709a1f9c21.png)

**Comment by JTNMW** [comment]
Both upper and lowercase for 'categories' and 'Love' gave similar results.

**Comment by bobdenotter** [comment]
Fix for this is in the pipeline. Note that the syntax _does_ require you to use the slugs for both the Taxonomy name as well ass the value: 

Works: 

`{% setcontent entries = 'entries' where { categories: 'love'} %}`

Neither of these work: 

```
{% setcontent entries = 'entries' where { categories: 'Love'}  %}
{% setcontent entries = 'entries' where { Categories: 'love'}  %}
{% setcontent entries = 'Entries' where { categories: 'love'}  %}
```
