### ISSUE TITLE
WYSIWYG settings are ignored

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1218]
Changes in the WYSIWYG settings in config.yaml are not visible in html field types.

Settings in config.yaml:
<img width="309" alt="Screenshot 2020-03-24 at 18 35 02" src="https://user-images.githubusercontent.com/2750653/77458808-0ff4a200-6dff-11ea-98c1-744fff7073d1.png">

Corresponding field:
<img width="727" alt="Screenshot 2020-03-24 at 18 35 17" src="https://user-images.githubusercontent.com/2750653/77458796-0bc88480-6dff-11ea-9b92-a26b10763836.png">

The true/false values seem to be ignored.

---
Bolt4.0.0 rc11

**Comment by bobdenotter** [comment]
I think we'll bump this to 4.1. It's not trivial to implement, because v3 used CKeditor, and we can't use the latest of that. (long story short: It has no "view source" option, thereby disqualifying itself)

Is there any _specific_ markup that you're missing in the wysiwyg editor?

**Comment by peterboorsma** [comment]
The current feature set is fine. It's just that I like to hide the options that I don't want an editor to use. It's not superimportant to me right now.

**Comment by bobdenotter** [comment]
See also #938

**Comment by bobdenotter** [comment]
Let's close this, now that we have the fancy Redactor and Article fields.
