### ISSUE TITLE
problem with records without titles

### ISSUE THREAD

**Issue by 0spinboson** [bolt/core#1227]
![testimonial](https://user-images.githubusercontent.com/21077532/77646462-e48bc780-6f64-11ea-9f8c-e43270331cdb.png)
(This also causes problems in the front end: 
![Screenshot_2020-03-26_13-23-43](https://user-images.githubusercontent.com/21077532/77646559-0e44ee80-6f65-11ea-86d3-facc3d4fbd67.png)
)

**Comment by bobdenotter** [comment]
Apart from the title not being said so it returns `/files/`, that's not something we should fix (because it's literally doing what you're telling it to do. 

Fix to prevent breakage in the frontend coming up!

**Comment by 0spinboson** [comment]
I'm fine with it not showing a title, of course, but just to be sure: your fix also addresses the backend 'list' entries for the CT (see the flyout menu in the first screenshot), so that you can access them?

**Comment by bobdenotter** [comment]
Well, kinda.. My opinion is that there isn't an actual problem there. If you choose to make a contentype that has no slug or title, it needs to use _something_ to set them apart, right? 

![Screenshot 2020-03-29 at 13 46 28](https://user-images.githubusercontent.com/1833361/77848272-e43d3780-71c3-11ea-8723-f2cbbaefbab3.png)

It now also lists them all on the backend overview page, if the slug is missing (this was part of the fix) 

![Screenshot 2020-03-29 at 13 48 23](https://user-images.githubusercontent.com/1833361/77848296-12bb1280-71c4-11ea-8905-5e38cdd156f7.png)

**Comment by 0spinboson** [comment]
okay, but why couldn't it show, say, the id (or 'contenttype/id' instead?

That aside, there's also this issue:
![Screenshot_2020-03-31_12-18-42](https://user-images.githubusercontent.com/21077532/78015750-242e2700-734a-11ea-8727-5d89233a7b6b.png)
(compare the hover menu output to the listing output.)

**Comment by bobdenotter** [comment]
> okay, but why couldn't it show, say, the id (or 'contenttype/id' instead?

Because we've made the assumption that a contenttype should hold _some_ information. If there's none, what's the point of putting it in the CMS? 

> (compare the hover menu output to the listing output.)

Can't tell from your screenshot: What version is this?

**Comment by 0spinboson** [comment]
this is prerelease 13

**Comment by 0spinboson** [comment]
how do you mean some info though? it does hold information (i.e., it has a textarea / html field), I just don't see the point in having a title field, because they're just going to be testimonials.

**Comment by bobdenotter** [comment]
I'll see if i can improve this some more.

**Comment by 0spinboson** [comment]
thanks

**Comment by bobdenotter** [comment]
The reason why nothing shows up in on the page itself, is that you're sorting on a field (`sort: -datecreated`) that doesn't exist. 


![Schermafbeelding 2020-03-31 om 17 49 05](https://user-images.githubusercontent.com/1833361/78047970-53a85800-7379-11ea-9676-543ca567981a.png)

If you remove that line, it'll work better: 

![Schermafbeelding 2020-03-31 om 17 57 14](https://user-images.githubusercontent.com/1833361/78047792-19d75180-7379-11ea-9a3b-34c25bb2618c.png)

I'm also making a PR in a few minutes that'll make it select the first Field that has `excerptable` to determine the "title", so it'll skip the image field.

**Comment by 0spinboson** [comment]
sounds good, thank you. :)
