### ISSUE TITLE
Can't delete file

### ISSUE THREAD

**Issue by technicallyerik** [bolt/core#1240]
I am unable to delete a file from the file manager.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.0-rc.12
| Install type                   |  Composer install
| PHP version                 | 7.3.9
| Web server                  | Apache
| For UX/UI issues        | Safari 13.0.5

Reproduction
------------

### Specifics

1) Navigate to http://technicallyerikv4.local:8888/bolt/filemanager/files#
2) Select "Delete" under the actions menu for a file
3) Confirm deletion in the confirmation prompt

### Expected result

I would expect the file to be deleted.

### Actual result

Observe the file is not deleted.  Looking in the network inspector, it looks like there wasn't attempt to make an Ajax call either.

I also confirmed my 'files' folder, and the files within it, had write access from the server.

**Comment by bobdenotter** [comment]
See also #1240. :-)

**Comment by technicallyerik** [comment]
Ah, sorry!  I see the other ticket now (#1141).
