### ISSUE TITLE
First user should be an admin?

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1254]
I just installed a new Bolt environment by following the docs (to test https://github.com/bolt/core/issues/1201).

When I add the first user ("admin", like I always do) with:
`bin/console bolt:add-user`
I get a warning message, after adding the first user:

 _[WARNING] Note: regular users CAN NOT log in to the Bolt backend. Create a user with the `--admin` flag instead, if this is what you intended._

My opinion is that the first added user should always be an admin user. What's the point of adding a first user that is unable to log in the backend?

So either add the admin flag in the docs:
`bin/console bolt:add-user --admin`
or
make sure the first added user ahs admin rights.

----
 Bolt version: 4.0.0 RC 13

**Comment by bobdenotter** [comment]
I'm not sure I see the problem here.. Either run `bin/console bolt:setup` and the first user _will_ be an admin user. Or, if you want to do it in separate steps, you can do that as well, but: 

> So either add the admin flag in the docs:
> bin/console bolt:add-user --admin

It is documented as such, right?

**Comment by bobdenotter** [comment]
Hi @peterboorsma, 

Any followup on this, so i can perhaps improve docs?

**Comment by peterboorsma** [comment]
I see that you already added the --admin flag to the "Installation" section of the docs. 
This is clear now in the docs, together with the "then lets you create the first (admin) user" sentence.
Thank you.

**Comment by nestordedios** [comment]
Thank you @peterboorsma for the feedback.

I'm closing this issue since this seems to be solved for some time already 👍 .
