### ISSUE TITLE
Field config  'allow_twig: true'  not working

### ISSUE THREAD

**Issue by JTNMW** [bolt/core#1272]
twig not being rendered when field contains twig control/echo.

contenttype.yaml
![Screenshot 2020-04-03 at 10 33 34](https://user-images.githubusercontent.com/57093734/78346806-7b750700-7597-11ea-843a-b2847c112c81.png)

filed with allow_twig: true
![Screenshot 2020-04-03 at 10 34 17](https://user-images.githubusercontent.com/57093734/78346822-816ae800-7597-11ea-904c-24940453aad3.png)

output - twig not being rendered as expected:
![Screenshot 2020-04-03 at 10 34 37](https://user-images.githubusercontent.com/57093734/78346839-8760c900-7597-11ea-80ab-edce09ee6ab2.png)

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | legacy / 4.0 / 4.1 / master
| Install type                   |  Zip or tar install / Composer install / GitHub checkout
| BC Break                     | yes/no
| PHP version                 | 7.2 / 7.3 / 7.4 |
| Web server                  | Apache / Nginx / Built-in, version [ version ]
| For UX/UI issues        | Browser name and version

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by bobdenotter** [comment]
A fix for this is in the queue.. Note that you'll _also_ need to set `{{ record|allow_twig }}` in your template. 
I'm afraid that's unavoidable for now. :-/
