### ISSUE TITLE
Language Switcher - Settings are not kept

### ISSUE THREAD

**Issue by surips** [bolt/core#1288]
I need two languages for my website, therefore I use a language switcher. When I call up my url the website is shown in the language of the browser. Switching the language works, but if I go to another page the language switches back to the original language (same as the browser) and does not keep the language that I chose.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0 RC15
| Install type                   |  Composer install 
| PHP version                 | 7.4 
| Web server                  | Apache / Nginx 

Reproduction
------------

Switching languages works, but the language settings are not kept. If you got to another page of the website, the language is switched back.

### Specifics

Language switch template used:
`{% include 'helpers/_languageselect.html.twig' with {'type': 'select', 'style': 'width: 13rem;'} %}`

### Steps to reproduce

1. Call website without being logged on to bolt backend
2. Switch to other language (not the default language of your browser)
3. Go to another page on website

### Expected result

Language stays the same, meaning the one that the user chose

### Actual result

Language switches back to standard

**Comment by bobdenotter** [comment]
Hi @surips, 

if you go to another page, what's the URL of that page? It _should_ stick to the current language, unless the URL specifically specifies another language.

**Comment by surips** [comment]
@bobdenotter So imagine I have the following URL: https://mypage.de. When I switch to english it transforms to: https://mypage.de/en. But if I then change the page, i.e. go to Contenttype pages/10 the URL looses the 'en' and is as follows: https://mypage.de/pages/10 and switches back to the original language (in this case back to german).

This only happens if I am not logged in to the Bolt Backend as mentioned before.

**Comment by I-Valchev** [comment]
hi @surips , I _think_ I was able to reproduce it. Using the skeleton theme, if I change the locale by selecting Netherlands, and then click any of the links to a page, the page gets rendered in the default locale (in this case, English). This is what you pointed out is the problem, correct?

I will work on a fix for this and will let you know once done :-)

**Comment by surips** [comment]
@I-Valchev yes, exactly! Thanks :-)

**Comment by I-Valchev** [comment]
@surips sure :-)
A fix is in the pipeline #1315.
