### ISSUE TITLE
Hide viewless content from API

### ISSUE THREAD

**Issue by technicallyerik** [bolt/core#1296]
Feature request / suggestion:  Viewless content should be hidden from the API.

A user might have either data submitted from Bolt Forms into a content type, or maybe a certain content type has content restricted to authenticated users via 3rd party code.

We can piggyback off the `viewless: false` parameter in content types to hide this content from the public API.

`curl -X GET "http://localhost/api/contents?contentType=viewless_content_type" -H "accept: application/ld+json"`

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0-RC 15
| Install type                   |  Composer install
| PHP version                 | 7.3.9
| Web server                  | Apache

**Comment by technicallyerik** [comment]
https://api-platform.com/docs/core/security/#filtering-collection-according-to-the-current-user-permissions

**Comment by bobdenotter** [comment]
fixed by #1305
