### ISSUE TITLE
Locales and canonical URLs - no root url?

### ISSUE THREAD

**Issue by wgaulke** [bolt/core#1301]
No distinct canonical url for a language.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0 RC16
| Install type                   |  Composer install 
| PHP version                 | 7.4 |
| Web server                  | Apache / Nginx 

Reproduction
------------

### Bug summary

Content is accessible with and without locale. For example if "de" is the primary language, a page can be accessed with `mydomain/de/page/1` but also with `mydomain/page/1`.

There should be a canonical URL pointing to the "master" page, but both pages identify themselfes as the canonical. There should only be one canonical url.

### Steps to reproduce

1. Open a Bolt4 lage, look at canonical. 
2. Add locale in url.
3. Take a look at the canonical.

### Expected result

There should only be one canonical to identify the main source.

**Comment by bobdenotter** [comment]
Correct, we should fix this
