### ISSUE TITLE
Homepage preview shown in wrong template

### ISSUE THREAD

**Issue by ianfoulds** [bolt/core#1306]
When you preview the homepage from the back-end the wrong template is used.

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version |  master
| Install type                   |  GitHub checkout
| PHP version                 | 7.3
| Web server                  | Apache

Reproduction
------------

After a standard git checkout and editing the homepage from the main menu, when the preview button is pressed the preview tab is shown using record.twig and not index.twig. When the homepage is viewed via the frontend the correct template is used (index.twig).

According to the homepage description in config.yaml, the following definition should cause index.twig to be used, there are no overrides define in theme.yml:
```
# The default content to use for the homepage, and the template to render it
# with. This can either be a specific record (like `page/1`) or a listing of
# records (like `entries`). In the chosen homepage_template, you will have
# `record` or `records` at your disposal, depending on the homepage setting.
#
# Note: If you've changed the filename, and your changes do not show up on
#       the website, be sure to check for a theme.yml file in your themes
#       folder. If a template is set there, it will override the setting here.
homepage: homepage/1
homepage_template: index.twig
```
there is a work around by adding a 'record_template: index.twig' attribute to the homepage definition in contenttypes.yaml

**Comment by bobdenotter** [comment]
Confirmed.. We'll fix this!

**Comment by bobdenotter** [comment]
This has been fixed. Being the oaf that I am, i accidentally pushed straight to the repo, so there's no PR. See: f29cf7ec600f4b3dea301ab6bf7175bb4784e3b3
