### ISSUE TITLE
'Create new' button on overview pages does not work

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1318]
There's a dark blue 'Create new <contenttypename>' button on overview pages in the backend (Like: https://my.site/bolt/content/<contenttype>)
This button does not work.

Bolt 4.0.0 RC16

<img width="324" alt="Screenshot 2020-04-21 at 15 14 38" src="https://user-images.githubusercontent.com/2750653/79870163-d6558d80-83e2-11ea-9c63-fd9b5994689c.png">

**Comment by bobdenotter** [comment]
This has alreasdy been fixed by @I-Valchev, very recently. :-)
