### ISSUE TITLE
Unable to change number of records listing [backend]

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1320]
When I change the number of records of a contenttype I want to show on one page in the backend, it keeps showing only 10.

From my contenttypes.yaml:

```
    recordsperpage: 50
    listing_records: 50
```
It seems the list does not respect the settings in contenttypes.yaml

Bolt 4.0.0 RC17

**Comment by bobdenotter** [comment]
We've changed it to `records_per_page`, for consistency. 

The contenttypes in the default `contenttypes.yaml` should have it correct, and the listing in the docs is updated too: https://docs.bolt.cm/4.0/contenttypes/intro#defining-contenttypes

**Comment by peterboorsma** [comment]
Thanks. This site was ported from Bolt3. Missed that one.
