### ISSUE TITLE
RC17 > RC18 update breaks installation

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1351]
I just updated some Bolt 4 sites. In the end of the update process I get this message:

> Cannot autowire service "Bolt\Canonical": argument "$defaultLocale" of method "__construct()" is type-hinted "string", you should configure its value explicitly.

<img width="587" alt="Screenshot 2020-05-03 at 16 07 09" src="https://user-images.githubusercontent.com/2750653/80916421-d184c800-8d58-11ea-84f1-0f198c63c454.png">

Tested on multiple installs. All of them break.

Bolt 4.0.0 RC17/18

**Comment by 0spinboson** [comment]
see the top of https://github.com/bolt/project/blob/master/UPDATE.md for fix. :)

**Comment by peterboorsma** [comment]
Tnx

**Comment by bobdenotter** [comment]
Closing this one. ^_^
