### ISSUE TITLE
Handle changes in ContentTypes more gracefully.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#1374]
When adding a new contenttype `foo_bar_qux`, you might get this error when requiesting a page: 

```
Twig\Error\RuntimeError:
An exception has been thrown during the rendering of a template ("Parameter "contentTypeSlug" for route "listing" must match "homepage|pages|entries|blocks|page|entry|block" ("foo_bar_qux" given) to generate a corresponding URL.").
```

It's remedied bu running `bin/console cache:clear`, but this is not very user friendly.

**Comment by I-Valchev** [comment]
Two more things:
- View saved version on site button does not work before clearing the cache
- Adding a CT which does not have a `singular_name` or `singular_slug` gives a 500, which is difficult to debug.

**Comment by I-Valchev** [comment]
Update on this:

container params can only be set before the container is compiled, which means we cannot update the container bolt.requirement.contenttypes param at runtime. That means when a new content type is created, cache has to be cleared.

This looks, however, like an important usability issue impacting the "simplicity of creating content" aim of Bolt :/
