### ISSUE TITLE
Image field types in a collection of sets should by default return empty 

### ISSUE THREAD

**Issue by nealmarques** [bolt/core#1378]
Empty image field types that are part of set in a collection are returning '/files/' when empty.  I'm expecting an empty string.  I'm having to check for '/files/' instead of using "is empty" condition.

| Relevant Bolt Version | version4.0.0 RC 17
| Install type | Composer install
| BC Break | yes/no
| PHP version | 7.3
| Web server | Built-in

**Comment by bobdenotter** [comment]
@nealmarques I couldn't reproduce this, just yet.. Could you post the contenttype from `contenttypes.yaml`?

**Comment by nealmarques** [comment]
`
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        body:
            type: html
            height: 300px
            allowtwig: true
        template:
            type: templateselect
            filter: '*.twig'
        sections:
            type: collection
            group: sections
            fields:
                rows:
                    type: set
                    fields: 
                        row_background_image:
                            type: image
                            label: Background Image for Entire Row
                            alt: false
                        row_background_color:
                            type: text
                            label: Background Color of Row
                            placeholder: 'Ex: #ffffff , rgba(255,255,255,.5)'
                            postfix: '<hr>'
                        left_copy:
                            type: html
                            label: Left Copy
                        left_color:
                            type: text
                            label: Left Color
                            placeholder: 'Ex: #ffffff , rgba(255,255,255,.5)'
                        left_copy_position:
                            type: select
                            values: [flex-start, center, flex-end]
                            label: Copy Position
                        left_background_color:
                            type: text
                            label: Left Background Color
                            placeholder: 'Ex: #ffffff , rgba(255,255,255,.5)'
                        left_bg_image:
                            type: image
                            label: Left Background Image
                            alt: false
                            postfix: '<hr>'
                        right_copy:
                            type: html
                            label: Right Copy
                        right_color:
                            type: text
                            label: Right Color
                            placeholder: 'Ex: #ffffff , rgba(255,255,255,.5)'
                        right_copy_position:
                            type: select
                            values: [flex-start, center, flex-end]
                            label: Copy Position
                        right_background_color:
                            type: text
                            label: Right Background Color
                            placeholder: 'Ex: #ffffff , rgba(255,255,255,.5)'
                        right_bg_image:
                            type: image
                            alt: false
                            label: Right Background Image

        foreground_image:
            type: image
            label: Foreground Image
            group: media
            upload: Foreground
        background_image:
            type: image
            label: Background image
            upload: Background
            group: media
    taxonomy: [ groups ]
    records_per_page: 5
    order: id
`

**Comment by nealmarques** [comment]
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        body:
            type: html
            height: 300px
            allowtwig: true
        template:
            type: templateselect
            filter: '*.twig'
        sections:
            type: collection
            group: sections
            fields:
                rows:
                    type: set
                    fields: 
                        row_background_image:
                            type: image
                            label: Background Image for Entire Row
                            alt: false
                        row_background_color:
                            type: text
                            label: Background Color of Row
                            placeholder: 'Ex: #ffffff , rgba(255,255,255,.5)'
                            postfix: '<hr>'
                        left_copy:
                            type: html
                            label: Left Copy
                        left_color:
                            type: text
                            label: Left Color
                            placeholder: 'Ex: #ffffff , rgba(255,255,255,.5)'
                        left_copy_position:
                            type: select
                            values: [flex-start, center, flex-end]
                            label: Copy Position
                        left_background_color:
                            type: text
                            label: Left Background Color
                            placeholder: 'Ex: #ffffff , rgba(255,255,255,.5)'
                        left_bg_image:
                            type: image
                            label: Left Background Image
                            alt: false
                            postfix: '<hr>'
                        right_copy:
                            type: html
                            label: Right Copy
                        right_color:
                            type: text
                            label: Right Color
                            placeholder: 'Ex: #ffffff , rgba(255,255,255,.5)'
                        right_copy_position:
                            type: select
                            values: [flex-start, center, flex-end]
                            label: Copy Position
                        right_background_color:
                            type: text
                            label: Right Background Color
                            placeholder: 'Ex: #ffffff , rgba(255,255,255,.5)'
                        right_bg_image:
                            type: image
                            alt: false
                            label: Right Background Image

        foreground_image:
            type: image
            label: Foreground Image
            group: media
            upload: Foreground
        background_image:
            type: image
            label: Background image
            upload: Background
            group: media
    taxonomy: [ groups ]
    records_per_page: 5
    order: id

**Comment by nealmarques** [comment]
[contenttypes.yaml.txt](https://github.com/bolt/core/files/4647377/contenttypes.yaml.txt)

**Comment by I-Valchev** [comment]
@nealmarques I am not able to reproduce this yet as well. Using the `contenttypes.yaml` that you provided, when I create a row with all fields empty, and dump the `row_background_image` value, I get:
```
array:7 [▼
  "filename" => ""
  "path" => ""
  "media" => ""
  "thumbnail" => ""
  "fieldname" => "row_background_image"
  "alt" => ""
  "url" => ""
]
```

The image value is an array with `filename`, `path`, `media`, `thumbnail`, `fieldname` and `url`. Can you provide the output you're getting for each of those, so that I can see which one exactly contains `/files/`?

**Comment by nealmarques** [comment]
When I dump out row_background_image I don't get such a clean list of values,
![Screenshot 2020-05-19 at 15 35 50](https://user-images.githubusercontent.com/5342693/82339891-77d1fe00-99e6-11ea-8a83-08e062dacd69.png)
To be honest, I can't even find the array that  lists out the row_background_image.

However,
I'm looping through the rows in the section, and if do the following:

{{dump(row.row_background_image == '/files/')}}. I'll get true
{{dump(row.row_background_image is empy)}}. I'll get false.

And this is on an empty page with just an empty row defined.

**Comment by nealmarques** [comment]
I should also mention that I'm just using sqllite.

**Comment by I-Valchev** [comment]
Right, I see.
@nealmarques can you try 

{% dump(row_background_image.value) %}

This should output the array like it did in my earlier comment. Make sure that you dump that in a place where row_background_image is defined, of course :-)

**Comment by nealmarques** [comment]
With the .value I can see that filename is empty, as expected.  The question is, should I be using .value.filename to see if its empty; or should it be expected that "row_background_image is empty" will return true if the filename is empty.

**Comment by bobdenotter** [comment]
@nealmarques I think it'd be really nice if `{% if record.row_background_image %}` would work that way, but i don't think we can make it work that way. Under the hood, `row_background_image` is an Object for the field, so it'll evaluate to the object. Even if there's no image set, it's still a valid Field Object. Same goes for `is empty`: The field has attributes, regardless of an actual image being set.

**Comment by nealmarques** [comment]
Okay.

**Comment by I-Valchev** [comment]
let's just keep this open for a bit: we _might_ be able to pull it off with the countable interface.
