### ISSUE TITLE
Collections with just 1 item in them should be loopable

### ISSUE THREAD

**Issue by nealmarques** [bolt/core#1402]
I have a content type with a collection of sets.  If I only add 1 set in that collection, i'm not able to  iterates over that collection with for loop; the code inside the loop will never execute.

I suppose this happens because the array is never created if its just one set.  An array should always be returned, this way the template developer doesn't need to duplicate code to catch the 1 set case.

| Relevant Bolt Version | version4.0.0 RC 17
| Install type | Composer install
| BC Break | yes/no
| PHP version | 7.3
| Web server | Built-in

**Comment by I-Valchev** [comment]
@bobdenotter hmm, we fixed that today, but... does it apply to collections I didn't think so
