### ISSUE TITLE
Phone number field?

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1436]
Might be tricky to implement, but it could be nice to support a phone number field? (e.g. + (country code) etc..
and maybe as output some nicer formatting?

**Comment by bobdenotter** [comment]
As an intermediary fix, you could use a plain text field, and add a pattern: `pattern: '/^([+]31|0)[1-8]\s*-?\s*([\d]\s*-?\s*){8}$/'` (this will match Dutch phone-numbers)

**Comment by bobdenotter** [comment]
Let's write a bolt.tips atricle about this!

**Comment by I-Valchev** [comment]
Done!

See https://bolt.tips/entry/8
