### ISSUE TITLE
Records locale issues

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1437]
Bolt install updated to RC22 with 1 language (nl)

In config.yaml:` locale: nl`
No localizations in contenttype.yaml

The issues:
- The `{{ htmllang() }}` tag shows nothing in my frontend templates: `<html lang="">`

- When adding a new record, the slug remains empty. I have to 1) save the record, then 2) use "generate from: title" to add the correct slug. 
See screencast: https://www.dropbox.com/s/z9puc6i7pv1f7mp/Screen%20Recording%202020-05-31%20at%2022.14.41.mov?dl=0

- /nl/ appears in links to records in listing templates 

First I thought that it could be a caching thing, so I emptied cache in Bolt (Maintenance > Empty cache). No changes. The did a php ./bin/console cache:clear . No changes. Then I emptied the complete cache/dev directory.
Unfortunetaly the issues remain.

Remote system info:
```
 Bolt version: 4.0.0 RC 22
 
 * Install type: Composer install
 * Database: mysql 5.5.5-10.2.32-MariaDB - 127.0.0.1 via TCP/IP (with JSON)
 * PHP version: 7.3.18
 * Operating System: Linux - 2.6.32-042stab136.1
```

Local system info:
```
 Bolt version: 4.0.0 RC 22

 * Install type: Composer install
 * Database: mysql 5.7.26 - 127.0.0.1 via TCP/IP (with JSON)
 * PHP version: 7.3.12
 * Operating System: Darwin - 19.4.0
```

This is a new issue based on problems as described in https://github.com/bolt/core/issues/1398

**Comment by I-Valchev** [comment]
hi @peterboorsma , can you try setting the `locale` option in `services.yaml` to `nl`, if it was different?

**Comment by peterboorsma** [comment]
It was set to `'en'` in `services.yaml`. Changed it to `'nl'` but now all content 'dissapeared' from my records.
<img width="360" alt="Screenshot 2020-06-03 at 12 47 23" src="https://user-images.githubusercontent.com/2750653/83628201-6701ba80-a598-11ea-9133-b9da362d2651.png">

No luck with the {{ htmllang()}} either I'm afraid.

**Comment by peterboorsma** [comment]
Update: if I save a new record (still have to add the slug manually) and go to my (frontend) listing page, all records in that listing now have url's without the /nl/ addition.

**Comment by peterboorsma** [comment]
Just to see this is documented here: 
- Set the locale in services.yaml:` locale: 'nl'`
- I did this in my db:
`UPDATE `bolt_field_translation` SET `locale` = replace(locale, 'en', 'nl') `
My content is back in place. Thank you.

The other 2 issues (empty {{ htmllang() }} tag and missing slugs when creating a new record) remain.

**Comment by peterboorsma** [comment]
Will test the slugificator (ha!) when the next RC is release. Manual fix did not solve the problem.

**Comment by bobdenotter** [comment]
The slugification is fixed in the compiled JS. Would be tricky to apply manually. Let me know if it works better after you've upgraded!

**Comment by peterboorsma** [comment]
> The slugification is fixed in the compiled JS. Would be tricky to apply manually. Let me know if it works better after you've upgraded!

It is fixed in RC23. But there's a quirk... It only works correctly when you put the slug field before the title field in contenttypes.yaml:

Slugifier work correctly:
```
    fields:
        title:
            type: text
        slug:
            type: slug
            uses: [ title ]
            group: Content
```

Slugifier fails:
```
    fields:
        slug:
            type: slug
            uses: [  title ]
            group: Content
        title:
            type: text
```

**Comment by peterboorsma** [comment]
I think this is solved now. Tried again a few hours later and now it works. Don't know why but it does.

**Comment by bobdenotter** [comment]
Cool, closing this one, then! 👍
