### ISSUE TITLE
<meta rel="canonical"> is duplicated

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1443]
The canonical meta tag appears twice on the page, e.g. /page/this-is-a-page

**Comment by bobdenotter** [comment]
I'm not seeing this.. Any special way to trigger it?

**Comment by bobdenotter** [comment]
it looks like the event to inject the snippets in the header is triggered twice, then.  Haven't been able to reproduce yet, though. 🤔

**Comment by I-Valchev** [comment]
I can't seem to replicate it again, and it's been some time.

Let's close it, if it happens again we'll look into it :-)
