### ISSUE TITLE
accept_upload_size issues

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1454]
I added `accept_upload_size: 16M` to `config.yaml` but I'm only allowed to upload files up to about 1mb. Tested with  +/- 3MB, 2MB, 1MB images.
The 1MB version uploads succesfully.

**Error after failing to upload:**
`The file for field 'Upload file' was not uploaded. The upload can have a maximum filesize of 16 MB.`

**Info:**
```
 Bolt version: 4.0.0 RC 23

 * Install type: Composer install
 * Database: mysql 5.7.26 - 127.0.0.1 via TCP/IP (with JSON)
 * PHP version: 7.3.12
 * Operating System: Darwin - 19.4.0
```
From phpinfo:
```
upload_max_filesize | 32M
post_max_size | 32M
```

**Comment by bobdenotter** [comment]
Is this on mamp? or a version of the built-in / symfony server?

**Comment by peterboorsma** [comment]
MAMP. Also tested on remote with the same results:

 ```
Bolt version: 4.0.0 RC 23
 
 * Install type: Composer install
 * Database: mysql 5.5.5-10.2.32-MariaDB - 127.0.0.1 via TCP/IP (with JSON)
 * PHP version: 7.3.18
 * Operating System: Linux - 2.6.32-042stab136.1
```
