### ISSUE TITLE
Wrong output contenttypename

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1467]
A contenttype like this:

```
planjebezoek:
    name: Plan je bezoek
    singular_name: Plan je bezoek item
```

Using `{{ records|first.contenttypename }}` in a loop, the `singular_name` is returned, not the `name`.

---
Bolt 4.0.0 RC23

**Comment by bobdenotter** [comment]
Fix is in the queue.. Thanks for reporting!
