### ISSUE TITLE
Refactor to `FriendsOfBehat/SymfonyExtension`

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#1474]
As part of the road to Symfony 5 (See #1182), we should use this: https://github.com/FriendsOfBehat/SymfonyExtension

See also: https://kamilkokot.com/tame-behat-with-the-brand-new-symfony-extension/

**Comment by I-Valchev** [comment]
This is WIP for me. 

see [#128](https://github.com/FriendsOfBehat/SymfonyExtension/issues/128)
and on core #1500

**Comment by I-Valchev** [comment]
Fixed by #1500
