### ISSUE TITLE
Image alt attribute defaults to true in Imagelist field

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#1486]
Setting up a Contenttype with an Imagelist field sets the `alt` attribute of every added image to true.

![default value](https://user-images.githubusercontent.com/6607455/84767830-65da7f80-afd3-11ea-874c-5219c52271d5.PNG)

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.0 RC 24
| Install type                   | Composer install
| PHP version                 | 7.2  |
| Web server                  | Symfony local Server

Reproduction
------------

1. Add and Imagelist field into the `fields` options of a Contenttype:
   ```
       fields:
            imagelist:
                type: imagelist
   ```
2. Add a new image into the Imagelist field.

### Expected result

Empty value for `alt` attribute

### Actual result

True value for `alt` attribute.

**Comment by bobdenotter** [comment]
I've seen this happen too.. 

@I-Valchev You mentioned you knew where this came from, right?

**Comment by I-Valchev** [comment]
@bobdenotter yeh, I believe so. I'll fix that!
