### ISSUE TITLE
404 :: NotFoundHttpException No route found for new records of new Contenttype

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#1504]
The route for a new record can not be found.

![not-found-route](https://user-images.githubusercontent.com/6607455/85005357-f68e9800-b158-11ea-8a17-380bd7f12cc2.JPG)

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.0 RC 24
| Install type                   | Composer install
| PHP version                 | 7.2
| Web server                  | Symfony Local Server

Reproduction
------------

1. Add a new contenttype to the `contenttypes.yaml` file
   ```news:
    name: News
    singular_name: News Item
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image
        text:
            type: html
            height: 300px
    record_template: newsitem.twig```
2. Create a new News record
3. Navigate to the created record URL `/news/{slug}`

### Expected result

I expect to see the detail page view of the created record

### Actual result

I get the a `404 :: NotFoundHttpException` error page

**Comment by bobdenotter** [comment]
Does the `configuration notices` widget in the backend tell you to clear the cache? I think this is solved after clearing the cache.

**Comment by nestordedios** [comment]
Hey @bobdenotter,

Yes indeed what you said. The configuration notices widget was telling me to clear the cache. I missed that one.

Thank you!
