### ISSUE TITLE
[RFC] Add Configuration notices widget to overview and edit pages in backend

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#1506]
I don't know if this is already possible with some extra configuration but at this moment the Configuration notices widget is displayed only in the Bolt Dashboard `/bolt`. 

For a more user friendly experience, I think this notices should also be added to the overview `/bolt/content/{contenttype}`, new `/bolt/new/{contenttype}` and edit pages `/bolt/edit/{recordID}`. 

I think it would be good to get these notices throughout the biggest part of the backend so the user will get notified when navigating throw overview and edit pages. It would be even better if this could be done async, so there was no need to refresh/reload the page to get this notices.

Making this notices more visible will make users more aware of these notices. It has happened to me that:
- I added a new Contenttype 
- I reloaded an edit record page (where I was at that moment) to see the new added Contettype on the left menu
- Directly created a new record of the new Contenttype following the options of the menu
- Missed the notice that said I needed to do a cache clear after I added the new Contenttype.

### Dasboard overview page
![notices-in-dashboard](https://user-images.githubusercontent.com/6607455/85013843-8df9e800-b165-11ea-9466-6d08a27439f1.JPG)
### Edit page
![no-notices-in-edit](https://user-images.githubusercontent.com/6607455/85013833-8c302480-b165-11ea-89ee-5b642b67d776.JPG)
### New record page
![no-notices-in-new](https://user-images.githubusercontent.com/6607455/85013837-8cc8bb00-b165-11ea-8f4f-7ae140e8a22d.JPG)
### Contenttype records oveview page
![no-notices-in-overview](https://user-images.githubusercontent.com/6607455/85013842-8df9e800-b165-11ea-8adc-002f92e0a53a.JPG)

**Comment by bobdenotter** [comment]
I'm not sure yet, if we should.. 

Thing is: If we put it on many places, people will develop a blind spot for it, as opposed to it sticking out like a sore thumb (as it should, imho). 

Apart from that, we'd need to consider if it has a negartive impact on performance. I think some of the tests are a bit CPU-intensive. 🤔 

I'd be happy to hear opinions from other people on this, as well.

**Comment by I-Valchev** [comment]
Maybe we can find some common ground here.

I think it's pretty common when you're developing (as an implementer) to _not_ look at the dashboard page. For this, I think it's helpful to have it more often and on other pages too. + it only shows when there's an issue, not otherwise.

For performance, it'll definitely be annoying to have it run _all the time_. Once the `disable extension` button is implemented, people will be able to disable it on production, after making sure all is fine. Hence, no extra CPU burden, right? :-)

**Comment by bobdenotter** [comment]
I'm not fond of disabling this.. From Bolt 3 we know the _most_ important check this extension does is: "Hey stupid! You've left DEBUG on in PROD, and now your cache folder is rapidly consuming _all_ of your disk space". If we advise people to disable it on PROD, you'd miss out on these.

**Comment by nestordedios** [comment]
I agree on what @I-Valchev said here:
> I think it's pretty common when you're developing (as an implementer) to not look at the dashboard page. For this, I think it's helpful to have it more often and on other pages too. + it only shows when there's an issue, not otherwise.

on reply to @bobdenotter:
> Thing is: If we put it on many places, people will develop a blind spot for it, as opposed to it sticking out like a sore thumb (as it should, imho).

I understand having it enabled in more places might be CPU consuming but I don't think this is the only thing it warns about in Bolt 3.  
> "Hey stupid! You've left DEBUG on in PROD, and now your cache folder is rapidly consuming all of your disk space". If we advise people to disable it on PROD, you'd miss out on these.

Why I opened this issue is not to discuss what this extension does, should do, tell or not. I'm thinking more about the experience of a non experienced (or even experienced) user that might find himself trapped when things are not going smoothly and a certain notification could have saved some troubleshooting. 

See examples of Bolt 3 when user gets notified that the database needs to be updated (This notifications are not only on the Dashboard page):

### Database update notification in content overview page 
![bolt-3-notices-overview](https://user-images.githubusercontent.com/6607455/85131213-a8e85d00-b236-11ea-8894-73eb690e4ebc.JPG)

### Database update notification in content edit page 
![bolt-3-notices-edit](https://user-images.githubusercontent.com/6607455/85131300-ce756680-b236-11ea-83e8-620c470f3203.JPG)

**Comment by bobdenotter** [comment]
I've come around on my opinion, and i think we _should_ show these notices on other pages as well. 

There's one tricky thing, though. We can currently only target _one_ location for a widget: https://github.com/bobdenotter/configuration-notices/blob/master/src/ConfigurationWidget.php#L24

I've made a separate issue, of this wider problem: https://github.com/bolt/core/issues/1585

**Comment by bobdenotter** [comment]
Closing this, because we'll handle this in #1585
