### ISSUE TITLE
Allow viewless homepage contenttype or make it optional

### ISSUE THREAD

**Issue by milosa** [bolt/core#1512]
I'm working on a single-page website. So not, let's say, a blog, with blog items that need to be available in the homepage template. 

I have a singleton viewless contenttype that contains the content for the single page. 
This used to work, but (I think) in RC 25, I cannot use viewless anymore.

I tried removing the `homepage` and `homepage_template` settings completely. But this gives errors (`php.CRITICAL: explode() expects parameter 2 to be string, null given {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): explode() expects parameter 2 to be string, null given at (...)/vendor/bolt/core/src/Controller/Frontend/HomepageController.php:38)"} []`)

So it would be nice to either allow viewless contenttypes, or to make the homepage settings optional, so I can load the contenttype manually with `setcontent`.

**Comment by bobdenotter** [comment]
@milosa Did you read the discussion about this in Slack? I'm wondering if this should be considered a bug or a feature. 🤔
