### ISSUE TITLE
PDF file upload over 2MB

### ISSUE THREAD

**Issue by twokingshq** [bolt/core#1522]
Tried uploading a pdf file larger then 2 mb. Then this happens.
![Bolt weird things](https://user-images.githubusercontent.com/20402496/85143233-cc68d300-b249-11ea-92f5-e397aa5e531e.jpg)

**Comment by bobdenotter** [comment]
If you click "new issue" there's a boilerplate issue report there, with information. Please don't _just_ remove that, but actually read it.

**Comment by I-Valchev** [comment]
^ that's my fault, it's what I told Michael when we were creating this issue together. I'll correct this in future, sorry.

**Comment by I-Valchev** [comment]
Not quite fixed yet. #1531 fixed it for image and file fields, but not in the filemanager.
