### ISSUE TITLE
Upgrade from 4.0.0 RC 24 to RC 25 breaks

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#1533]
I have just updated to the latest RC 25 release (`composer update`)  and now my Bolt project is broken with the following error

![Knipsel](https://user-images.githubusercontent.com/6607455/85274671-8ac16d80-b47f-11ea-94fb-ba6cd51c6f82.PNG)

My `composer.json`
```
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "bobdenotter/weatherwidget": "^1.0",
        "bolt/assets": "^4.0",
        "bolt/core": "^4.0",
        "bolt/newswidget": "^1.1",
        "bolt/themes": "^3.1",
        "symfony/flex": "^1.6",
        "bobdenotter/configuration-notices": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd",
            "bolt:copy-assets": "symfony-cmd"
        },
        "post-create-project-cmd": [
            "cp -n .env.dist .env || true",
            "rm public/.gitignore .github/FUNDING.yml",
            "mv README_project.md README.md"
        ],
        "post-install-cmd": [
            "php bin/console bolt:copy-themes",
            "@auto-scripts",
            "php bin/console bolt:info"
        ],
        "post-update-cmd": [
            "@auto-scripts",
            "php bin/console bolt:info"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": true,
            "require": "^4.4"
        },
        "public-dir": "public"
    }
}
```

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.0 RC 25
| Install type                   |  Composer `composer create-project bolt/project projectname`
| PHP version                 | 7.2 |
| Web server                  | Symfony Local Server

Reproduction
------------
This is how I got into this issue and I hope it's reproducible like this again. 

1. Create some content on a Bolt 4.0.0 RC 24 project
2. Update from a Bolt 4.0.0 RC 24 to RC 25
3. Go to Frontend/Backend of the project

I have tried to revert the installation to **Bolt 4.0.0 RC 24** but then I've got a different error message:

![Knipsel](https://user-images.githubusercontent.com/6607455/85277865-5f8d4d00-b484-11ea-9b6f-38f0b23240d8.PNG)

### Expected result

Frontend and Backend of the project working

### Actual result

Frontend and Backend of the project NOT working

**Comment by bobdenotter** [comment]
You can read about it here: https://github.com/bolt/project/blob/master/UPDATE.md

**Comment by nestordedios** [comment]
Thank you @bobdenotter, I did not know about this file.

Following the instructions for this type of issue and dealing with some PHP Extensions (I think) kind solved my problem.

### PHP Extensions error
![Knipsel](https://user-images.githubusercontent.com/6607455/85283245-4dfc7300-b48d-11ea-89fe-3408a2883a35.PNG)

### New Error (not in [UPDATE.md](https://github.com/bolt/project/blob/master/UPDATE.md))
![Knipsel](https://user-images.githubusercontent.com/6607455/85283875-6a4cdf80-b48e-11ea-8a0b-28c8124241e0.PNG)

**Comment by nestordedios** [comment]
Last error is related to issue #1537.
