### ISSUE TITLE
Cannot autowire argument $content...

### ISSUE THREAD

**Issue by benplummer** [bolt/core#1536]
The following `RuntimeException` takes place when updating to Bolt 4.0.0 RC 25.

![Screenshot 2020-06-22 at 12 47 52](https://user-images.githubusercontent.com/1983525/85284643-72555100-b487-11ea-94ac-88944661b7dd.png)

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.0 RC 25
| Install type                   |  Composer install
| PHP version                 | 7.3.17

**Comment by nestordedios** [comment]
This is also happening to me as well using PHP 7.2

![Knipsel](https://user-images.githubusercontent.com/6607455/85289378-a46eaf00-b497-11ea-954d-9f234bec1344.PNG)

**Comment by bobdenotter** [comment]
How / when does this happen?

**Comment by nestordedios** [comment]
In my case it's hard to say. 

I got this #1533 problem solved, and then this happened in the backend.

**Comment by benplummer** [comment]
@bobdenotter I only get the error when I access the edit page of a record in the bolt back-end panel.

I did a `composer update` which resulted in a 500 due to `bcmath` and `gmp` PHP extensions not being found. I fixed that issue by installing them and then this issue was present.

**Comment by nestordedios** [comment]
^ Same here

**Comment by milosa** [comment]
I have the same issue. I'm on dev-master. 
For me it started after updating to the latest commit.

**Comment by I-Valchev** [comment]
@milosa @peterboorsma @nestordedios 

This should be resolved by removing the following from your `bundles.php` file:
`Roukmoute\HashidsBundle\RoukmouteHashidsBundle::class => ['all' => true], this in bundles.php`

Then remove:
`/config/packages/roukmoute_hashids.yaml`

And run `composer update`

**Comment by milosa** [comment]
@I-Valchev That works! Thanks.

**Comment by nestordedios** [comment]
The last fix from @I-Valchev worked!

> 
> 
> @milosa @peterboorsma @nestordedios
> 
> This should be resolved by removing the following from your `bundles.php` file:
> `Roukmoute\HashidsBundle\RoukmouteHashidsBundle::class => ['all' => true],`
> 
> Then remove:
> `/config/packages/roukmoute_hashids.yaml`
> 
> And run `composer update`

But now I'm getting in the backend I'm getting:
![Knipsel](https://user-images.githubusercontent.com/6607455/85303144-66c75180-b4aa-11ea-9b2a-ab86c5dc6da2.PNG)

Is this happening to anyone else?

**Comment by nestordedios** [comment]
I just solved that by running `composer update` again.

**Comment by bobdenotter** [comment]
Closing this one, as it's been solved!

**Comment by bobdenotter** [comment]
I just got this: 

![Screenshot 2020-06-23 at 07 15 54](https://user-images.githubusercontent.com/1833361/85363593-92395300-b521-11ea-9dd7-b418fe38e46b.png)

It was reverted here: https://github.com/KnpLabs/DoctrineBehaviors/pull/579
