### ISSUE TITLE
Contentlisting route does not exist

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#1538]
I'm trying to generate a URL for a listing page using `{{ path('contentlisting', {'contenttypeslug': 'news'}) }}` as explained in the Docs https://docs.bolt.cm/4.0/templating/linking-in-templates#using-path-and-url-to-link-to-named-routes but I get the following Error:

![afbeelding](https://user-images.githubusercontent.com/6607455/85305614-988de780-b4ad-11ea-8a48-094cc28173b8.png)

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.0 RC 25
| Install type                   | Composer composer create-project bolt/project projectname
| PHP version                 | 7.2 |
| Web server                  | Symfony Local Server

Reproduction
------------

Try to generate a URL for a listing page of one of your Contenttypes using:
`{{ path('contentlisting', {'contenttypeslug': 'pages'}) }}` 

### Expected result

The URL of the listing view for the Contenttype

### Actual result

Error page

**Comment by bobdenotter** [comment]
If you do `bin/console debug:route` you'll see all routes. 

I think this one is now: 

```
  listing                                              GET|POST   ANY      ANY    /{contentTypeSlug}
```

So, you can try: `{{ path('listing', {'contenttypeslug': 'pages'}) }}`.
