### ISSUE TITLE
Imagelist alt:true on rc26

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1567]
The bug with the `alt` attribute showing as true still happens on RC26, after updating from RC24.

Is it assets not being up to date?

**Comment by bobdenotter** [comment]
Starting with the next version, we'll include this file: https://github.com/bolt/assets/blob/master/package.json 

in the `vendor/bolt/assets/` folder. That way you'll be able to see when it was built (and on what date), so we can debug things like this a bit easier.

**Comment by bobdenotter** [comment]
Did you have a change to verify yet if this is still an issue?

**Comment by I-Valchev** [comment]
I'll check this evening :-)

**Comment by I-Valchev** [comment]
Cannot replicate this again. Let's close it, if it shows up again we'll fix it.
