### ISSUE TITLE
Search within contenttype

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1578]
If I am on a listing page, e.g. `/blog` I want to be able to add a search form that, on submit, goes to `/blog?search=term`.

On that listing page with query param `search`, I want the `records` variable to only include records matched against the search term.

Afaik, this is not (yet) implemented, right? @bobdenotter

**Comment by bobdenotter** [comment]
This is something that can be done in twig only, on the frontend.. Do you think this is something that should be coe functionality, or a snippet or something elsewhere explaining how to do it?

**Comment by I-Valchev** [comment]
Hmm, I think that depends on how easy it is to implement in twig. If it is several lines of straightforward code, I think snippet / docs how-to page is better... less noise in core.

If not, putting it in core (or extension?) is needed imho. It looks like a fairly common use case to be able to search for blog posts, news, events, etc. and be able to display them with the same listing template (rather than the generic search one).

**Comment by I-Valchev** [comment]
okay, we have a bolt.tips entry about that, using:

`{% setcontent records =  contenttype.slug where { 'anyField': '%' ~ searchTerm ~ '%' } %}`

Documentation needs updating, do we even need `pages/search` handler in that case? @bobdenotter

**Comment by JTNMW** [comment]
i have just implemented this in my project with a slight change to the listingController and contentRepository ( both of which are in my project/src - not vendor/bolt/src). All params are passed and if search (anyfield) is given it performs a searchNaive() on the search term in all fields and taxonomies and returns records to the listing.twig.

It also allows fields and taxonomies to be queried in the url and returns results to the listing. functions including changes below:

listingController.php
```
public function listing(ContentRepository $contentRepository, Request $request, string $contentTypeSlug): Response
    {
        $contentType = ContentType::factory($contentTypeSlug, $this->config->get('contenttypes'));
        $page = (int) $request->query->get('page', 1);
        $amountPerPage = $contentType->get('listing_records');
         //get all query parameters
		$params = $request->query->all();
		
		
		//check if search is set and move to anyField param with like %...% appended.
		if( $request->query->get('search') !='') { $params['anyField'] = '%'.$request->query->get('search').'%';
            //clear search param 
            unset ($params ['search']);};
		
		
		//get published records only
		$params ['status'] = 'published';
		
		//set order defaults if not set in query
        $params ['order'] = $request->query->get('order', $contentType->get('order'));
      
		 if (! empty($params['anyField'])) {
             $contentTypes = $this->config->get('contenttypes')->where('searchable', true);
             
            $records = $contentRepository->searchNaive($params['anyField'], $page, $amountPerPage, $contentTypes);
        } else {
            // include all params as array
		$records = $this->query->getContent($contentTypeSlug, $params)
            ->setMaxPerPage($amountPerPage)
            ->setCurrentPage($page);
        }
		
		

        /*
        $order = $request->query->get('order', $contentType->get('order'));

        $records = $this->query->getContent($contentTypeSlug, [
            'status' => 'published',
            'order' => $order,
        ])
            ->setMaxPerPage($amountPerPage)
            ->setCurrentPage($page);*/

        $templates = $this->templateChooser->forListing($contentType);

        $twigVars = [
            'records' => $records,
            $contentType->getSlug() => $records,
            'contenttype' => $contentType,
        ];

        return $this->renderTemplate($templates, $twigVars);
    }
}
```
contentRepository.php

```
public function searchNaive(string $searchTerm, int $page, int $amountPerPage, Collection $contentTypes, bool $onlyPublished = true): Pagerfanta
    {
        // First, create a querybuilder to get the fields that match the Query
        $qb = $this->getQueryBuilder()
            ->select('partial content.{id}');

        $qb->addSelect('f')
            ->innerJoin('content.fields', 'f')
            ->innerJoin('f.translations', 't')
            ->andWhere($qb->expr()->like('LOWER(t.value)', 'LOWER(:search)'))
            ->setParameter('search', '%'.$searchTerm . '%')

            //ACNMW - added to incude taxonomies to be searched
            ->addSelect('tx')
            ->innerJoin('content.taxonomies', 'tx')
            ->orWhere($qb->expr()->like('tx.slug', ':slug'))
            ->setParameter('slug', '%' . $searchTerm . '%');

        // These are the ID's of content we need.
        $ids = array_column($qb->getQuery()->getArrayResult(), 'id');

        // Next, we'll get the full Content objects, based on ID's
        $qb = $this->getQueryBuilder()
            ->addSelect('a')
            ->innerJoin('content.author', 'a')
            ->orderBy('content.modifiedAt', 'DESC');

        if ($onlyPublished) {
            $qb->andWhere('content.status = :status')
                ->setParameter('status', Statuses::PUBLISHED);
        }

        $qb->andWhere('content.contentType IN (:cts)')
            ->setParameter('cts', $contentTypes->keys()->all());

        $qb->andWhere('content.id IN (:ids)')
            ->setParameter('ids', $ids);

        return $this->createPaginator($qb->getQuery(), $page, $amountPerPage);
    }
```

I don't seem to be too successfull with PRs but can try to pr these if you think they may help like?

**Comment by JTNMW** [comment]
as an aside, i just have a simple search form on the listing page /taxa which submits to itself eg /taxa?search=xxxxx
```
<form class="field has-addons" method="get" action="/taxa" enctype="text/plain">


						<label class="label is-hidden" for="search">Search</label>
						<div class="control">
							<input class="input" type="search" value="{% if app.request.get('search') is defined %}{{ app.request.get('search')|escape }}{% endif %}" placeholder="{{ __('general.phrase.search-ellipsis') }}" name="search" id="search" style="width: 9rem;">


						</div>
						<div class="control">
							<button class="button is-black" type="submit">{{ __('action.search') }}</button>
						</div>
					</form>`
```

**Comment by I-Valchev** [comment]
@JTNMW you can also take a look at this:
https://bolt.tips/entry/7

pretty simple :-)

**Comment by JTNMW** [comment]
@I-Valchev,  ok, that's great, thanks. That would seem to mitigate me having to use custom listingController.php and contentRepository.php. I think i changed these as i wanted the search (anyField) to be able to search in taxonomies as well as fields, but ive since added this ability to selectQuery.php (see pr #1541) which i gather is used by setcontent anyway.

would this method work with multiple (and unknown) query parameters on submission of a form with many options? what would be the best way to get all app.request params and loop through adding to the where {}. ??

for example, if i have the the url /taxa?genera=abana&continent=Nearctic after submitting a form on the listing page (where _genera_ is a taxonony slug, and _continent_ is a field)  could the twig end up bing created dynamically like this?

{% setcontent records = contenttype.slug where { 'genera': 'abana', 'continent': 'nearctic' } %}

**Comment by I-Valchev** [comment]
that should work, yes. If you loop over it and add the object properties that way.

Here's some pointers:
https://stackoverflow.com/questions/7719838/updating-object-properties-in-twig

And then you'd pass that object after the where, like so:
{% setcontent records = contenttype.slug where _object_ %}

**Comment by I-Valchev** [comment]
See https://bolt.tips/entry/7
