### ISSUE TITLE
Unexpected time notation/behaviour

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1581]
In the backend:
When saving a record, the 'current status' text below the save button shows "in 1 hour", instead of the time the record is changed/saved.

<img width="306" alt="Screenshot 2020-06-30 at 13 05 00" src="https://user-images.githubusercontent.com/2750653/86119207-59c1e800-bad2-11ea-8237-e03934d84b5b.png">

When creating a record, the timestamp is of by +2 hours.

Local time:
<img width="89" alt="Screenshot 2020-06-30 at 13 07 30" src="https://user-images.githubusercontent.com/2750653/86119435-bde4ac00-bad2-11ea-9168-59f90e928bbf.png">

Saving a new record:
<img width="412" alt="Screenshot 2020-06-30 at 13 07 22" src="https://user-images.githubusercontent.com/2750653/86119470-cf2db880-bad2-11ea-9cc4-efea66fe5147.png">

Addition to this issue: displayed time uses AM/PM notation instead of 24 hour clock. And the time notation always show in English instead of the used locale in the backend.
In my specific case date/time isn't being translated to NL in the frontend/templates. This is an older issue but forgot to make an issue. But it may be related.

Bolt 4.0.0 RC26 + RC25

**Comment by peterboorsma** [comment]
I'm reopening this. The problem still occurs. Tested it on multiple sites, on my local MAMP as well as a public server.

Server time:
<img width="213" alt="Screenshot 2020-08-21 at 09 03 28" src="https://user-images.githubusercontent.com/2750653/90863660-bda8b480-e38f-11ea-888d-e4f4254877da.png">

Time in Bolt:
<img width="358" alt="Screenshot 2020-08-21 at 09 02 59" src="https://user-images.githubusercontent.com/2750653/90863679-c8634980-e38f-11ea-85b3-f9bcabc77bd4.png">

---
PHP Version 7.3.20
Bolt 4.0.0 RC35

**Comment by sellmark** [comment]
I'm just wondering - isn't that a Javascript related issue? It happened to me a lot of times when I read from DB(SQL) specific datetime and have it "transformed"(mostly +2h, because that's my locale) by invoking a Date object on the given value.
Not a resolve, but may make u to look somewhere you wouldn't look normally :)

**Comment by bobdenotter** [comment]
It has to do with the time difference between UTC ("greenwich time") and your local time. Timestamps should be saved in the DB in UTC, and then in the application show up as local time. 

What we're seeing here is this transformation going wrong sometimes. We'll need to dig in how to fix it properly.

**Comment by I-Valchev** [comment]
This definitely needs fixing, but letss  bump it to 4.1 if we can't solve it earlier.
