### ISSUE TITLE
New Feature: Widgets should be able to have multiple targets

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#1585]
Currently, a widget can target only one location, like this: 

https://github.com/bobdenotter/configuration-notices/blob/master/src/ConfigurationWidget.php#L24

```php
    protected $target = AdditionalTarget::WIDGET_BACK_DASHBOARD_ASIDE_TOP;
```

`$target` should be able to take an array of multiple targets, so we can re-use a widget in different locations. 

See also #1506

When this is done, we should fix https://github.com/bobdenotter/configuration-notices/issues/3

**Comment by Spomsoree** [comment]
I couldn't get any other additional target, other than `WIDGET_BACK_DASHBOARD_ASIDE_TOP` to work.
Ist this known (described in this issue), or is this only about supporting multiple at once?

**Comment by I-Valchev** [comment]
Completed ✅
