### ISSUE TITLE
⭐️ Update documentation for v4

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#159]

**Comment by bobdenotter** [comment]
Work has been done on this, but needs more work.

**Comment by sbonardt** [comment]
@bobdenotter Is there a list? _(not trying to be smart...)_

**Comment by bobdenotter** [comment]
@sbonardt No, there's no list yet.. 

There's a current copy of v3 docs, that needs to get update to v4: https://docs.bolt.cm/4.0/getting-started/introduction
Repo is here: https://github.com/bolt/docs/tree/4.0

**Comment by 0spinboson** [comment]
one item: explain how to install extensions in Bolt 4

**Comment by bobdenotter** [comment]
One more: This page needs love: https://docs.bolt.cm/4.0/contenttypes/intro (esp. the examples)

**Comment by bobdenotter** [comment]
It's time we close this. Much work has been done on docs.
