### ISSUE TITLE
If you pass in a date format, output seems double-encoded or somesuch.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#1604]
For example: `{{ record.publishedAt|localedatetime("%A %B %e, %Y") }}` 

![Screenshot 2020-07-05 at 17 31 38](https://user-images.githubusercontent.com/1833361/86536137-8ec0a700-bee5-11ea-88d3-b5ad5dc3c873.png)

**Comment by I-Valchev** [comment]
Oh, I think the Carbon library only works with this format:
https://www.php.net/manual/en/function.date.php

not with the one `strftime` uses
https://www.php.net/manual/en/function.strftime.php
