### ISSUE TITLE
`{% setcontent %}` tag should work with relative dates

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1608]
```twig
{% setcontent myarticles = 'entries' where { status: 'published', publishedAt: '< last monday' } %}
```

**Comment by bobdenotter** [comment]
Duplicate of #1417 

(which i was pretty sure I fixed, but apparently not)

**Comment by I-Valchev** [comment]
hmm... maybe you did, but it doesn't work with the content dates? Or maybe I'm stupid and can't make it work.

**Comment by bobdenotter** [comment]
No, it's broken alright.. I fixed it, but either my fix was wrong, or it got broken again.

**Comment by bobdenotter** [comment]
The issue here is the space between `<` and `last monday`.. PR incoming!
