### ISSUE TITLE
`{% setcontent %}` filtering options

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1610]
The following should work:

```twig
{% setcontent myevents = 'events' where { categories: 'music' } %} {# THIS WORKS #}
{% setcontent pages = 'pages' where { author: '1 OR 4' } %}
{% setcontent pages = 'pages' where { id: '>5 AND < 10' } %}
```

**Comment by bobdenotter** [comment]
> {% setcontent pages = 'pages' where { author: '1 OR 4' } %}

You can use `{% setcontent pages = 'pages' where { author: '1 || 4' } %}`

> {% setcontent pages = 'pages' where { id: '>5 AND < 10' } %}

You can use `{% setcontent pages = 'pages' where { id: '>5 && < 10' } printquery %}` 

```
SELECT content FROM Bolt\Entity\Content content WHERE content.contentType = :ct0 AND ((content.id > :id_1 AND content.id < :id_2) AND content.status = :status_1) ORDER BY content.publishedAt DESC

    ct0: pages
    id_1: 5
    id_2: 10
    status_1: published
```

(even with that superfluous space, which was fixed in #1621)

**Comment by bobdenotter** [comment]
This probably needs to be documented better, though.. :-)

**Comment by I-Valchev** [comment]
I'm pretty sure this is (by now) explained in the docs. Let's close it.
