### ISSUE TITLE
Changing float field value manually breaks 'Save changes'

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1615]
When I change a float field value manually (e.g. by updating `650` to `650,3`), if the step is invalid, I cannot save the content.

There is no feedback stating that the field value is invalid either.

What should happen is a validation error message that states that the entered number is not valid (and suggests the closest valid one?)

**Comment by bobdenotter** [comment]
Seems to work for me.. 
![Schermafbeelding 2020-07-10 om 16 45 31](https://user-images.githubusercontent.com/1833361/87168988-96aa8d80-c2cf-11ea-9056-6ab3698a0964.png)

**Comment by I-Valchev** [comment]
Works for me too! Probably old assets. Thanks!
