### ISSUE TITLE
Database created with bin/console bolt:setup has latin1 charset/swedish collation

### ISSUE THREAD

**Issue by Sander-Hub** [bolt/core#1617]
Hi there,

When setting up a new Bolt4 site I noticed that when the database is created through the setup script the database has a latin1 character set and the collation is latin1_swedish, please see attached image.

Should this not be a utf8 charset and a utf8_general collation? Or is my database client (DBeaver) showing me wrong data?

![charset_collation](https://user-images.githubusercontent.com/66225295/86930043-d25e1f80-c136-11ea-9559-ab0501e39ecf.PNG)

===
Bolt version: 4.0.0 RC 28
mysql  Ver 14.14 Distrib 5.6.39
Composer install
Php 7.3.4

**Comment by bobdenotter** [comment]
I'm not too familiar with DBeaver, so i might be off here.. What you're looking at, is that the charset and collation of the database itself, or the tables created by Bolt? 

In case of the first, did you create the DB, or did you also let Bolt create it.. 

Cursory glance seems to indicate that on my machine locally, it _does_ correctly create tables in `utf8_mb4`: 

```sql
CREATE TABLE `bolt_field` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `content_id` int(11) NOT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sortorder` int(11) NOT NULL,
  `version` int(11) DEFAULT NULL,
  `type` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_4A2EBBE584A0A3ED` (`content_id`),
  KEY `IDX_4A2EBBE5727ACA70` (`parent_id`),
  CONSTRAINT `FK_4A2EBBE5727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `bolt_field` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_4A2EBBE584A0A3ED` FOREIGN KEY (`content_id`) REFERENCES `bolt_content` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4441 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by Sander-Hub** [comment]
So what I am looking at is the charset and collation of the DB itself. I checked the tables and those are indeed utf8mb4 / utf8mb4_unicode_ci.

The DB was created via the bin/console bolt:setup script. I did not create the DB myself.

I just found it 'weird' I was seeing 'swedish' in the collation. I figured I mentioned it. Thanks for the update.
