### ISSUE TITLE
⭐️ Make "Relations" work

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#163]

**Comment by JarJak** [comment]
Can we make it easy to fetch relations easy from owning and inversed side? Like:
`{{ record.related(ct, bidirectional=false) }} -> Content[]`
And fetching single (first) related content, like:
`{{ record.related(ct, first=true) }} -> Content`

**Comment by JarJak** [comment]
Have in mind relations in preview mode

**Comment by JarJak** [comment]
`related` filter will be done with #151

**Comment by bobdenotter** [comment]
Relations as such work. Closing this one for now. Feel free to re-open for more specific functionality.
