### ISSUE TITLE
`|shuffle` filter doesn't work

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#1632]
This ought to work: 

```twig
    {% setcontent pages = "pages" limit 4  %}

    {% for page in pages|shuffle %}
        <li>{{ page.id }} - {{ page|title }}</li>
    {% endfor %}
```

But, it throws an exception instead: 

![Schermafbeelding 2020-07-15 om 17 47 30](https://user-images.githubusercontent.com/1833361/87566406-482c3300-c6c3-11ea-9415-e0de22beaf03.png)

We should ensure the `|shuffle` filter works on Pagerfanta objects, as well as regular arrays. 

Additionally, check if this also applies to `sort`, `first`, `last`, `batch`, `length` (does work, but wrong results), `reverse` and `slice`.

**Comment by I-Valchev** [comment]
Afaik, only `|length` doesn't work. The rest seemed to work fine for me. #1633 fixes length and shuffle.
