### ISSUE TITLE
Error 'cp' is not recognized as an internal or external command, operable program or batch file when creating new project

### ISSUE THREAD

**Issue by mcdennem** [bolt/core#1652]
Creating a new project with composer error.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | legacy / 4.0 / 4.1 / master
| Install type                   | Composer install 
| BC Break                     | ???
| PHP version                 | 7.3 |
| Web server                  | Apache / Nginx / Built-in, version [ version ]
| For UX/UI issues        | Browser name and version

Reproduction
------------

`Run composer create-project bolt/project myproject`

### Actual result

`Script cp -n .env.dist .env || true handling the post-create-project-cmd event returned with error code 1`

**Comment by bobdenotter** [comment]
@mcdennem Should be fixed in https://github.com/bolt/project/pull/23 

Could you try again, on the same platform?

**Comment by bobdenotter** [comment]
Fixed in https://github.com/bolt/project/pull/23
