### ISSUE TITLE
{{ item|current }} or {{ item.current }} not working

### ISSUE THREAD

**Issue by ymarkus** [bolt/core#1655]
When using {{ item|current }} in my menu template, an exception is thrown. However, if I use {{ item.current }}, there is no exception thrown, but it always returns false.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version |  4.0-rc32
| Install type                   |  Composer install
| BC Break                     | maybe?
| PHP version                 | 7.3.20 |
| Web server                  | Built-in
| For UX/UI issues        | N/A 

Reproduction
------------

Use the following code in your template:
`menu.yaml`:
```
main:
  - label: Home
    link: /
[...]
```
`_menu_main.twig`:
```
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    {% for item in menu %}
      <li class="nav-item {%- if item.current %} active{% endif %}"> {# item|current throws an exception #}
        {{ dump(item) }}
        <a class="nav-link" href="{{ item.link }}">{{ item.label }}<span class="sr-only"> (current)</span></a>
      </li>
    {% endfor %}
  </ul>
</div>
```

For {{ item|current }} following exception is thrown:
```
Argument 2 passed to Bolt\Twig\ContentExtension::isCurrent() must be an instance of Bolt\Entity\Content, array given
[...]
at vendor/bolt/core/src/Twig/ContentExtension.php:311
at Bolt\Twig\ContentExtension->isCurrent(object(Environment), array('label' => 'Home', 'title' => '', 'link' => '/', 'class' => '', 'submenu' => null, 'uri' => '/', 'current' => false))
```

For {{ item.current }} it simply always returns false.

Therefore, I can't find a way to use the current filter in menus.

**Comment by I-Valchev** [comment]
Nice catch @ymarkus . PR #1659 fixes it, the correct way to use it is `item|current` like you did.
