### ISSUE TITLE
Thumbnailing SVG returns broken link

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1664]
![image](https://user-images.githubusercontent.com/7093518/89013497-4776dc00-d314-11ea-82ea-c9a8afe628e1.png)

The listing template tries to thumbnail an SVG, which of course doesn't really work.

But, imho, if it renders the image at the requested URL, even if it is the original one, it will already avoid a lot of issues like that.

What do you think @bobdenotter ?

**Comment by bobdenotter** [comment]
Yes, that makes sense :-)

**Comment by I-Valchev** [comment]
On it!
