### ISSUE TITLE
Incorrect notice about invalid fieldtypes. (Integer and float)

### ISSUE THREAD

**Issue by milosa** [bolt/core#1676]
I'm getting a notice in the backend saying that `float` and `integer` fieldtypes are invalid.

```
Info - A field of type integer was added to the 'Homepage' ContentType, but this is not a valid field type.

Edit your contenttypes.yaml to ensure that the homepage/integer field has a valid type.
```

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0 rc33
| Install type                   |  Composer install

**Comment by bobdenotter** [comment]
@milosa Try `type: number` instead. ;-)

We'll need to update the docs for this, so it's understandable you didn't know about it. :-) (https://docs.bolt.cm/4.0/manual/fieldtypes#number-based-fields)

**Comment by milosa** [comment]
Oh, you're right. I thought integer and float were the new types and number was the old way.
