### ISSUE TITLE
Twig Runtime Error

### ISSUE THREAD

**Issue by mcdennem** [bolt/core#1687]
After adding a small menu to menu.yaml and adding a template in the partials directory under base2018.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | l 4.0 
| Install type                   | Composer install
| BC Break                     | yes/no
| PHP version                 |  7.3 |
| Web server                  | Apache / Nginx / Built-in, version [ version ]
| For UX/UI issues        | Chrome

Reproduction
------------

Just followed this page:
https://docs.bolt.cm/4.0/menus/detailed

### Specifics
Key "current" for array with keys "label, title, link, class, submenu, uri" does not exist.
..\projectname\vendor\bolt\core\templates\helpers\_menu.html.twig (line 11)

**Comment by bobdenotter** [comment]
run `composer update` and then `bin/console bolt:copy-themes`, and it'll work ;-)
