### ISSUE TITLE
⭐️ Make "Fieldsets" work (to replace both 'blocks' and 'repeaters')

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#176]

**Comment by bobdenotter** [comment]
When implementing this, don't forget to make it work in `_sub_fields.twig` as well.

**Comment by sbonardt** [comment]
The name 'fieldset' for me is too much tied to a <form> to use it as a field type name. Other suggestions:

'field groups', 'field collections', or 'grouped fields'

**Comment by bobdenotter** [comment]
"Groups" is already user to refer to groups of fields shown on one 'tab' in the editors, so that's confusing too.

**Comment by sbonardt** [comment]
@bobdenotter So shouldn't "group" be renamed to "tab" then...? To keep things logical. Now you assign fields to a certain "group" to have them show up in a certain "tab". Assigning a field to a certain "tab" to have them in a certain "tab" in the UI sounds good to me. And then you can use "group" to group fields. Or fieldgroup

**Comment by bobdenotter** [comment]
A tab is what it "looks like", not "what it is". It feels kinda like `<div class="red">` to do that.

**Comment by sbonardt** [comment]
If you want to name it what it is, then just rename "group" to "fieldset". But this is UI for the end user, and that person sees a "tab".

Anyway you get to use "group" for the group of fields

**Comment by bobdenotter** [comment]
I think i'm more in favor of your other suggestion: Name the replacement for Blocks and Repeaters "Collection", and leave 'group' as is.

**Comment by bennash** [comment]
My 2 cents:
Collections and Groups sound like they refer to organized pieces of
content, not the atomic parts.

With Bolt CMS "Blocks" I often call them Content Blocks or Section Blocks.

"Repeaters" is a common CMS term meaning just what they are.

I've thought about this term for years when trying to explain it to my
client editors. I don't have a great suggestion. How about "Combination
Field" or "combo" for short?

**Comment by bobdenotter** [comment]
Closing, because the feature has been implemented.
