### ISSUE TITLE
The word 'new' is probably not needed for singletons

### ISSUE THREAD

**Issue by eduardomart** [bolt/core#1793]
The following is Singleton content type, it doesn't seem like the word 'New' is needed here:

<img width="545" alt="Screen Shot 2020-08-31 at 5 57 19 PM" src="https://user-images.githubusercontent.com/1833020/91783048-b9f90700-ebb3-11ea-8f67-3cac72949e22.png">

**Comment by bobdenotter** [comment]
Agreed, it's unneeded there.

**Comment by eduardomart** [comment]
Sorry to nitpick again, but now instead of 'New' I am seeing: 'Untitled'
Demo:
<img width="339" alt="Screen Shot 2020-09-02 at 2 44 50 PM" src="https://user-images.githubusercontent.com/1833020/92039999-e08d7e00-ed2a-11ea-8447-ca9351c8e58c.png">

**Comment by bobdenotter** [comment]
So, what _should_ it show if it's untitled, in your opinion? If you give it a title, that's what it shows, right? 

You can influence whicht fields it picks by default, using `title_format: '{heading} - {subheading}'`. See https://github.com/bolt/core/blob/master/config/bolt/contenttypes.yaml#L61

**Comment by eduardomart** [comment]
Since it's a singleton I think it shouldn't say anything, just whatever the `name` is set to, in my example it'd be fine to just say Settings

**Comment by eduardomart** [comment]
I apologize if this is confusing, but I am going to try to clarify, since it's affecting titles for both **Singletons** and **Multi Record** CTs, even if in different ways

Please note, when I am talking about **title** in this post I am talking about this:
![Screen Shot 2020-09-03 at 2 15 49 PM](https://user-images.githubusercontent.com/1833020/92171178-337d3900-edf0-11ea-9dc8-41fe1d238374.png)


### Singletons
1. I think the title  should be nothing more than the name defined in the Singleton, like so:
```
MySingleton:
    name: Singleton #<--- this is all we need to know about this record (at least as a default)
```
2. _New_ or _Untitled_ shouldn't apply to Singletons because there will always be only one record, so there's no _New_ and no _Untitled_ record
3. The above doesn't affect the `title_format` functionality, this can still be rendered if set

### Multi Record CTs
1. The word **New** is perfectly fine for new records, however:
2. When creating a new record, if there's a field with has a `default` value that is used in the title while creating a new record, which seems arbitrary, for example:
```
myrecords:
   name: myrecords
   fields:
      title:
         type: text
      web:
         type: text
         default: http://www.eventbrite.com
```
^ this will output http://www.eventbrite.com in the title, like so:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/1833020/92169034-a89c3e80-edef-11ea-8b51-7b9503bf4974.png">
3.  When a new record is being created (before being saved) it should only say '**New [Singular_name]**'
4. Once it's saved, display it, using `title_format` if it exists
