### ISSUE TITLE
"Translate" suggestion

### ISSUE THREAD

**Issue by evertalbers** [bolt/core#180]
_Presuming that the translate functionality and the tabs/group will work comparably with Bolt 3.6.X/ Bolttranslate extension in Bolt 4.0:_

When an editor switches languages while in a certain tab/group for a record
e.g. `/bolt/editcontent/siteblocks/1?_locale=en#footer`
he is sent to `bolt/editcontent/siteblocks/1?_locale=nl` and will have to perform a click to get back to
`/bolt/editcontent/siteblocks/1?_locale=nl#footer`

It is likely (at least, I think so) that the editor will want to continue working on the same tab/group in the other language so it would be good if the `#anchor` is added behind the link in the language switch.

**Comment by bobdenotter** [comment]
Makes sense, shouldn't be too hard to get this right for V4.

**Comment by JarJak** [comment]
@bobdenotter Do we need this in the very first alpha?

**Comment by nestordedios** [comment]
Thank you for reporting @evertalbers !

This issue has been solved long time ago. Update Bolt running `composer update` and you should get the fix.

I'm closing this issue since it has been fixed.
