### ISSUE TITLE
⭐️  Make good event system

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#183]
Some of those https://docs.bolt.cm/3.6/extensions/intermediate/events
But excluding those https://symfony.com/doc/current/reference/events.html
And those https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#lifecycle-events
And those https://api-platform.com/docs/core/events/

What comes to my mind that could be useful to add:
- auth related events
- pre/post config parse event
- pre/post menu parse event 
- some content form events https://symfony.com/doc/current/form/events.html
- maybe some widget or cron related events?

**Comment by bobdenotter** [comment]
Should go with #134

**Comment by bobdenotter** [comment]
Closing, not actionable enough.
