### ISSUE TITLE
Image field errors

### ISSUE THREAD

**Issue by eduardomart** [bolt/core#1869]
### Regular image fields
A regular `type: image` field outputs this button with a dropdown:
<img width="323" alt="Screen Shot 2020-09-16 at 9 27 01 PM" src="https://user-images.githubusercontent.com/1833020/93420404-ac09de00-f863-11ea-94a0-30410ec9ffd0.png">

If the option Edit Attributes is clicked, it causes this error:
<img width="528" alt="Screen Shot 2020-09-16 at 9 30 53 PM" src="https://user-images.githubusercontent.com/1833020/93420514-effce300-f863-11ea-8775-3e88614e2951.png">

### Image field inside a Collection
The option _From Library_ is not working, it doesn't produce the popup to browse image files. And the console shows this:
<img width="727" alt="Screen Shot 2020-09-16 at 9 40 08 PM" src="https://user-images.githubusercontent.com/1833020/93421105-4f0f2780-f865-11ea-8a9d-a23355b19b2f.png">

The option Edit Attributes also causes this error:
<img width="528" alt="Screen Shot 2020-09-16 at 9 30 53 PM" src="https://user-images.githubusercontent.com/1833020/93420514-effce300-f863-11ea-8775-3e88614e2951.png">

---
_Bolt v4 RC43_

**Comment by I-Valchev** [comment]
hi @eduardomart , thanks for bringing this up! I'll take a look.

**Comment by eduardomart** [comment]
Hi @Ivo, just a thing I forgot, the issue with _Edit Attributes_ also happens in the `imglist` field type

**Comment by I-Valchev** [comment]
@eduardomart good that you mention that! We have to fix it for it.

This also falls under #1871, but the imagelist thing for sure has to be fixed before 4.0 is out.

**Comment by I-Valchev** [comment]
The imagelist works for me, so I'm inclined to close that and resolve the `field` references in the other PR.
