### ISSUE TITLE
Twig in fields with `allow_twig` only works on first save

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1891]
The first time I save a title with twig, e.g. `Test page {{ 'hey' }}`, it returns this in the backend:

![image](https://user-images.githubusercontent.com/7093518/93981473-5318d900-fd80-11ea-929d-3c62b6f024ca.png)

But at least it works on the frontend.

Saving again (without any changes) breaks it. The tag is still shown, but it seems its escaped

**Comment by eduardomart** [comment]
Hi @I-Valchev, since you mentioned this, do we need to add it to the default `config.yaml`? It's currently not there.

**Comment by I-Valchev** [comment]
@eduardomart can't reproduce this anymore! Let's close this.
