### ISSUE TITLE
|svg filter should use path not filename

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1892]
The filter does not always work because it uses the filename, not the path.

**Comment by bobdenotter** [comment]
If I have a plain image field like this: 

```yaml
        image:
            type: image
```

And I put in a regular SVG.. And then I use this in my template: 

```twig
    {{ record.field('image')|svg }}

    {{ record|image|svg }}

    {{ record|svg }}
```

It outputs the image three times. Can you explain what's breaking on your end?

**Comment by I-Valchev** [comment]
As far as I know it was breaking when it's inside a collection, and the public path to the image was not correct. But I might be wrong on that, @nestordedios will know best :-)

**Comment by eduardomart** [comment]
I have an svg file in a collection/set and called `icon`

`{{ item.icon('image')|svg }}` -> no output

I tried other statements but the only thing that worked was:
`{{ item.icon.path|svg }}`
