### ISSUE TITLE
Frontend shows wrong dates

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1894]
Output in frontend is different from input from a datefield.

I have a custom datefield, like this:
```
        enddate:
            type: date
            mode: date
            label: Datum t/m
```
In my template I have this:
`{{ record.enddate|localdate(format='D j M Y') }}`
The outputted date is a day off. I.e.:
Input date in backend: `October 16, 2020`
Output in frontend: `Do. 15 okt. 2020`

Bob said earlier that it could have something to do with the way dates are stored in the MySQL database.
I can provide  a 'working' (read: malfunctioning) example when needed.

A dirty fix in your templates: add 2 hours like this:
`{{ (record.enddate ~ '+ 2 hours')|localdate(format='D j M Y') }}`

---
 Bolt version: 4.0.0 RC 43
 
 * Install type: Composer install
 * Database: mysql 5.5.5-10.2.32-MariaDB - 127.0.0.1 via TCP/IP (with JSON)
 * PHP version: 7.3.22
 * Symfony version: v5.1.5
 * Operating System: Linux - 2.6.32-042stab136.1

**Comment by develth** [comment]
Did you set timezone in `config/bolt/config.yaml`?

**Comment by peterboorsma** [comment]
No I did not. Didn't even know that was a thing.

config.yaml refers to  http://php.net/manual/en/timezones.php (should be updated to https btw).
My guess is, the `timezone: UTC` rule is commented out by default.
Looks like this is an undocumented feature.

In my case I want Europe/Amsterdam time. Can I just add
`timezone: Europe/Amsterdam` to my config.yaml?

**Comment by develth** [comment]
@peterboorsma deleted my comment ´cause i have same issue. With the config set i fixed another part - mixed that up. Have the two hours difference, too
