### ISSUE TITLE
|date filter should use default timezone, if not provided

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1898]
The `date` filter accepts the `timezone` parameter, but it does not use the default in `config.yaml`. If it's not passed, it should use the default instead.

Credits to @eduardomart for discovering it.

https://github.com/bolt/core/blob/74171ea99a15267c757481812d973c17b7df506d/src/Twig/FieldExtension.php#L56

**Comment by eduardomart** [comment]
Thank you @I-Valchev
