### ISSUE TITLE
Collection > image > upload > "from library" button doesn't work

### ISSUE THREAD

**Issue by eduardomart** [bolt/core#1910]
Could we maybe have the field also not be read-only? or make it optional?

![Screen Shot 2020-09-26 at 9 38 31 PM](https://user-images.githubusercontent.com/1833020/94356241-ebdd7c00-0040-11eb-8d64-c36914f18839.png)

**Comment by denis-gorin** [comment]
@eduardomart are you using only `.svg` files deau to this case?

**Comment by eduardomart** [comment]
Yes, only svg file type

**Comment by denis-gorin** [comment]
> Yes, only svg file type

So, I've had the same problem, today I plan to make PR to solve this one and next another (refer to delete files in a subfolders)

**Comment by eduardomart** [comment]
Awesome. Thank you!

**Comment by denis-gorin** [comment]
PR done #1913
