### ISSUE TITLE
Buggy thumbnail url generation using "path" and "location" parameters

### ISSUE THREAD

**Issue by luistar15** [bolt/core#1928]
When generating thumbnails with the `thumbnail` twig helper using `path` and `location` parameters, generates a image URL that the `ImageController` doesn't support.

Details
-------

The ImageController only supports and parses `width`, `height` and `fit` parameters
https://github.com/bolt/core/blob/4.0.1/src/Controller/ImageController.php#L136

But the thumbnail generator can use additional parameters (`location`, `path`) wich the ImageController doesn't support.
https://github.com/bolt/core/blob/4.0.1/src/Utils/ThumbnailHelper.php#L39

So, when generating thumbnails using the not suported parameters like in:
https://github.com/bolt/core/blob/4.0.1/templates/media/edit.html.twig#L19

It generates urls like:
http://127.0.0.1:8000/thumbs/900×500×path=stock/image_12174.jpg

And this confuses the ImageController router:
https://github.com/bolt/core/blob/4.0.1/src/Controller/ImageController.php#L41

And doesn't understands the extra parameters, returning `Error 500` with a `FileNotFoundException`.

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.1
| Install type                   |  Composer install
| BC Break                     | -
| PHP version                 | 7.4
| Web server                  | Built-in

Reproduction
------------

- Fresh install: `composer create-project bolt/project myprojectname` with dummy content.
- Start built-in webserver: `bin/console server:run`
- Navigate to: http://127.0.0.1:8000/bolt/media/edit/16
- The media images does not load correctly.

**Comment by bobdenotter** [comment]
Thanks for the detailed write-up, @luistar15 👍

**Comment by bobdenotter** [comment]
Re-opening. Not entirely fixed yet.
