### ISSUE TITLE
Singletons allow multiple when show_in_menu = false

### ISSUE THREAD

**Issue by andysh-uk** [bolt/core#1949]
A singleton content type behaves like any other “multiple” content type when “show_in_menu” is false, i.e. it allows creating multiple instances and shows the listing view.

If show_in_menu is true, you get taken directly to the singleton entry and cannot create another.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.1
| Install type                   |  Composer install
| BC Break                     | not sure, I’m a new Bolt user
| PHP version                 | 7.4 |
| Web server                  | Nginx
| For UX/UI issues        | Firefox on Mac 80, Safari on iPad OS 14

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Create a content type with singleton: true and show_in_menu: false.

Navigate to the content type under “Other Content” > “content type”. You are now on a listing page, not a blank entry form.

Create an entry for the content type.

Select the content type under “Other Content” > “content type” in the menu. You are back on the listing page and can create another entry.

If show_in_menu is true, clicking the content type in the menu goes straight to a blank entry form, or the single entry (if one exists.)

### Specifics

Bolt 4.0.1 installed using Composer. I can replicate on Firefox on Mac, Safari on iPad OS 14.

I wanted a content type called “settings” like that [described here](https://docs.bolt.cm/4.0/howto/singleton-contenttype) but not taking up space in the main menu, so I wanted to use the show_in_menu option to put it under the “Other Content” submenu.

However with this option set to “false”, the content type does not behave like a singleton.

### Steps to reproduce

Set up a content type as singleton: true, viewless: false, and show_in_menu: false.
Navigate to the content type under the “Other Content” submenu, and you are taken to a listing page.

### Expected result

When navigating to the content type with show_in_menu set to false, you should see either a blank entry form or the page to edit the existing singleton entry.

### Actual result

 
You are taken to a listing page, allowing you to create more entries in a singleton content type.

**Comment by I-Valchev** [comment]
@andysh-uk thanks for the detailed bug report! A fix is in the pipeline :-)

**Comment by andysh-uk** [comment]
Amazing, thank you!
