### ISSUE TITLE
⭐️ Make admin interface improvements

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#195]

**Comment by JarJak** [comment]
@nestordedios @bobdenotter what is this task about?

**Comment by sbonardt** [comment]
Yes, this is very 'loose'. To be concise, we discussed the approach/ideas to getting a 'good' UI in place for the backend in Bolt and are working on it. This can for now be archived I guess

**Comment by bobdenotter** [comment]
Closing this one for now.. Not because I disagree, but because it's not actionable. If this pops up again, let's define smaller tasks that can be worked on.
