### ISSUE TITLE
Meta snippet insert error

### ISSUE THREAD

**Issue by ziselive** [bolt/core#1975]
Insert the Meta Generator tag and canonical twice in the front-end head:
```
<link rel="canonical" href="http://www.ts.localhosthttp://ts.localhost/">
<meta name="generator" content="Bolt">
<link rel="canonical" href="http://www.ts.localhosthttp://ts.localhost/">
<meta name="generator" content="Bolt">
```

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.1
| Install type                   | Composer install 
| PHP version                 | 7.4 |
| Web server                  | Apache

**Comment by bobdenotter** [comment]
I've seen this happen once as well, a while ago. But, I've not been able to reproduce it consistently since. 

What happens here is that the 'snippets' queue is run twice. We'd need to figure out under which circumstances that happens, and then we can make a good fix for this.

**Comment by jordanaubert** [comment]
Hi, I stumbled on this issue and got the following in the `head` on my page : 
```
<link rel="canonical" href="http://localhost">
<link rel="canonical" href="http://localhost">
<link rel="canonical" href="http://localhost">
<link rel="canonical" href="http://localhost">
```
The way to reproduce it is to reach a singleton page, the `forward` call on `\Bolt\Controller\Frontend\ListingController::listing` creates a sub-request, triggering `WidgetSubscriber` and `ProcessWidgetsQueueSubscriber` resulting in two double insertion. I'll try to make an MR to fix it soon.
