### ISSUE TITLE
REST/GraphQL API endpoints

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#199]

**Comment by pascalwacker** [comment]
Have you taken a at https://api-platform.com/ it could probably used to automatically generate endpoints

**Comment by JarJak** [comment]
@pascalwacker yes we use API Platform for building API for headless frontend. Those endpoints just needs to be defined there ;)

**Comment by pgnd** [comment]
@JarJak 

I've got a non-Symfony GraphQL headless backend already in production, behind a SF frontend.

Currently _considering_ a switch Bolt4; _just_ started digging into it.  GraphQL is, here, a functional req't.

Can you expand on your "just" comment a bit?  If "just" is trivial, any realistic chance of that accelerating?

**Comment by bobdenotter** [comment]
@pgnd If you have a test-setup of Bolt 4 running, in the backend go to the API Platform screen. There you'll see what's there. For example, the "Content" endpoint can already be used with GraphQL.

**Comment by I-Valchev** [comment]
@bobdenotter can we close this?

**Comment by bobdenotter** [comment]
Yup, let's! :-)
