### ISSUE TITLE
Singleton page and queryParams in page address (ex. ?utm_source=some) cause Error

### ISSUE THREAD

**Issue by denis-gorin** [bolt/core#1990]
When I try to create link for using in external app with marketing params  (ex. ?utm_source=some etc.) the singletone page returns error.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.1
| Install type                   |  Composer install 
| PHP version                 | 7.2
| Web server                  | Apache / Nginx / Built-in, version [ sf 5.1.7]

Reproduction
------------

* create singleton page
* access it by link with query params ex. https://your.site/singleton?utm_source=some
* get an error

**PS**
There is config workaround by disabling  `query_search` in `config.yaml` 
See [Allow filtering on listing pages using query parameters](https://docs.bolt.cm/4.0/configuration/settings#query-search)

Or by overriding some singletons routing (in `routes.yaml`)...

But this is still interesting behaviour...

The reason is most likely in `ListingController.php`  when we '...trying to "list" a singleton...' then forwarding to `DetailController::record` we are using query params, but, I guess, should not...

**PPS**
May be we need firstly to check in `ListingController` if it's a singleton (`instanceof Content`) without queryParams and only after that work out the case with the listing?

**Comment by I-Valchev** [comment]
hi @denis-gorin , yes that sounds like an interesting edge-case.

When you say it gets an error, what do you mean?

If I do it, it returns "No content found" which is strictly speaking true, as those params don't match anything.

Still, I am not sure how this should be fixed, apart from allowing people to disable the `query_search` option.

**Comment by denis-gorin** [comment]
> When you say it gets an error, what do you mean?

"No content found" => no record in template (because template is for singleton using record in it) 

![500](https://user-images.githubusercontent.com/3963911/96214144-eec6ef00-0fa4-11eb-8b8a-bde2731eba1d.png)

**Comment by I-Valchev** [comment]
Okay, I am getting a 404 page, whilst the screenshot above is an exception.
Can you screenshot the whole page, to see where it comes from?

I agree that if we capture singletons in another way it will resolve the issue for singletons, but it will still be a problem for the listing, right? For example, if you wanted to include that same query parameter when people go to the listing page, it's still going to limit the results based on those query params.

**Comment by denis-gorin** [comment]
> Can you screenshot the whole page, to see where it comes from?

![2020-10-16 153536](https://user-images.githubusercontent.com/3963911/96235814-702e7980-0fc5-11eb-8427-1d4d884644da.png)

![2020-10-16 153537](https://user-images.githubusercontent.com/3963911/96235824-7290d380-0fc5-11eb-8223-b0721d3cd6fa.png)

**Comment by denis-gorin** [comment]
> I agree that if we capture singletons in another way it will resolve the issue for singletons, but it will still be a problem for the listing, right? For example, if you wanted to include that same query parameter when people go to the listing page, it's still going to limit the results based on those query params.

may be group search parameters with `query_search` namespace...
