### ISSUE TITLE
Preview and View Saved buttons no longer show up in Singletons

### ISSUE THREAD

**Issue by eduardomart** [bolt/core#1999]
See example:

<img width="1265" alt="Screen Shot 2020-10-14 at 1 10 15 PM" src="https://user-images.githubusercontent.com/1833020/96042404-35d8a700-0e22-11eb-9646-287cc643cc61.png">

Bolt 4.1

**Comment by I-Valchev** [comment]
hi @eduardomart , can you check your `contenttypes.yaml` definition for `viewless: true` for the homepage?

The buttons will not be visible if it is viewless.

**Comment by eduardomart** [comment]
You're absolutely right. My bad.

**Comment by I-Valchev** [comment]
No worries ^^
Recently we've been doing those _smart hacks_ showing and hiding things depending on what people have configured, but sometimes it may not be clear exactly why that happens 😅
