### ISSUE TITLE
Collection Label Listed Double on Add

### ISSUE THREAD

**Issue by develth** [bolt/core#2010]
Hello,

i just recognized, that the Collection Label is printed two Times at the "Add new Item to Collection" Button:
![Bildschirmfoto 2020-10-16 um 16 45 16](https://user-images.githubusercontent.com/3374563/96273094-3e221500-0fcf-11eb-90a1-6dae0dda655d.png)

https://github.com/bolt/core/blob/b436e24e41912c175571fce9749f3e74a76d327e/assets/js/app/editor/Components/Collection.vue#L41
https://github.com/bolt/core/blob/b436e24e41912c175571fce9749f3e74a76d327e/assets/js/app/editor/Components/Collection.vue#L52

So, `labels.add_collection_item` and `labels.select` seems to be the same

**Comment by I-Valchev** [comment]
Hi @develth , nice spot!

You are right, we really should not repeat this twice when there's only one option. 

PR #2011 fixes this.

**Comment by develth** [comment]
Impressive quick fix, thanks!

**Comment by I-Valchev** [comment]
Happy to help! Thanks again for spotting it.

Let's re-open this for now, it will close automatically once the PR is merged in :-)
