### ISSUE TITLE
Missing label for Content-Type Set

### ISSUE THREAD

**Issue by develth** [bolt/core#2012]
Hello,

as mentioned in [my comment](https://github.com/bolt/core/commit/53873f578bf7fa68e68eb9077b6e858a7a7b9567#r43305900), why turned off the Label at this Point?

https://github.com/bolt/core/blob/b436e24e41912c175571fce9749f3e74a76d327e/templates/_partials/fields/set.html.twig#L3

Previously i had a `Set` Label like "More Button" above that:
![Bildschirmfoto 2020-10-16 um 16 40 13](https://user-images.githubusercontent.com/3374563/96275528-2009e400-0fd2-11eb-860f-a26ef8fc303e.png)

Maybe make it configurable that only no Label will be displayed when it is within a Collection?

**Comment by eduardomart** [comment]
As a work around you could add a `prefix` for 'Button text'
