### ISSUE TITLE
Align collection item buttons to the right

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#2014]
![image](https://user-images.githubusercontent.com/7093518/96277659-da024f80-0fd4-11eb-9b08-82f763fdfc05.png)

If we have them right-aligned, it'll be consistent irrespective of how long the title of the field is.

**Comment by eduardomart** [comment]
Hi @I-Valchev this was introduced in 4.1, I wasn't sure if this was done on purpose, I commented about it here:
https://github.com/bolt/core/commit/492c45649f096d2a5318c1bcbbede6825304a88e
