### ISSUE TITLE
Bolt's FieldRepository should not assume all classes are loaded

### ISSUE THREAD

**Issue by arjenm** [bolt/core#2030]
Since #1734 has a large discussion that seems to cloud the actual problem, I decided to open a new issue. But it is effectively a duplicate.

We had the same issue... Diving very deep in the Bolt-internals, I found the cause.

It is related to caching, but not the cache specifically.

https://github.com/bolt/core/blob/b2aba74de9ca50d392e38ac77f3881f83e319e23/src/Repository/FieldRepository.php#L134

With that `get_declared_classes`-call it is assumed all Field-classes are loaded at this time. This happens to be true when the cache is not yet defined, probably due having to create the entity/field-configuration. But is an incorrect assumption when the cache is used. 

In our case, the amount of declared classes at that time drops from 2270 to 1140.
The only Field-class during that call to get_declared_classes is the generic Field-class, none of its subclasses is available. 

As such, this has incorrect behavior for all fields, not just the TemplateselectField. The TemplateselectField's Twig-template just happens to use helper methods with typehints. And those cause fatal errors.

A quick-fix for Bolt-specific fields would be to first test wheter `'Bolt\\Entity\\' . $classname` exists (and implements that interface). But that won't work for fields from outside that namespace.

**Comment by bobdenotter** [comment]
@arjenm We've bumped into this occasionally as well, but we're not sure on how to actually solve it. 

> A quick-fix for Bolt-specific fields would be to first test wheter 'Bolt\\Entity\\' . $classname exists (and implements that interface). But that won't work for fields from outside that namespace.

That would be a patch for this specific thing, but entities / fields added by an extension would still not be recognized in this case.

**Comment by I-Valchev** [comment]
@bobdenotter I was looking up some thing about this today and think we may just about
 be able to go around the `get_declared_classes` bug with Symfony. Let's discuss this this coming week :-)

**Comment by bobdenotter** [comment]
Hmm, interested to hear what your plan is! :-)

**Comment by develth** [comment]
Is it possbile to create a relase for this fix? Currently i cant create pages. 
Thanks!

**Comment by I-Valchev** [comment]
Hi @develth, yes, we'll be releasing a bugfix release today. 🙂
