### ISSUE TITLE
E2E tests fail sometimes on tests/e2e/setcontent.feature:4

### ISSUE THREAD

**Issue by LordSimal** [bolt/core#2061]
Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.1.4
| Install type                   |  Composer install
| BC Break                     | yes/no - What is that? 😅 
| PHP version                 | 7.3 
| Web server                  |  Built-in
| For UX/UI issues        | Google Chrome

Reproduction
------------

### Bug summary

As we already discussed in #2060 the automatic E2E tests fail due to inconsistencies with the test-data.

### Explanation of the problem

Basically in `src/DataFixtures/ContentFixtures.php` Line 446 the custom Template `public/theme/skeleton/custom/setcontent_1.twig` is being set for the `Setcontent test page`.

![image](https://user-images.githubusercontent.com/9105243/97144632-15cfae80-1765-11eb-8c95-eaf8b348fa27.png)

In that template a `yes` is being printed inside the <span> IF `entries` has some results.

The problem here is - as @simongroenewolt already mentioned - that the query only checks for blocks, entries and showcases which have `voluptat` somewhere in their title.

![image](https://user-images.githubusercontent.com/9105243/97144774-59c2b380-1765-11eb-800b-a563f2093315.png)

The title of an entry is `text` and therefore is being randomized via this function
src/DataFixtures/ContentFixtures.php Line 310

![image](https://user-images.githubusercontent.com/9105243/97145395-6c89b800-1766-11eb-9cd1-1913166a3bef.png)

Therefore either refactor that part of the code to always set the title of content with a preset randomzied set of words or call `seed()` for the faker instance 😄

**Comment by bobdenotter** [comment]
Ideally, it'd be configurable. Something like: 

```
bin/console doctrine:fixtures:load --group=without-images -n --seed=98765
```

Often, i _like_ my fixtures to be random-ish, just to see what it does. but for tests seeding it would be great!

**Comment by LordSimal** [comment]
alright, I will see how I can get this option into that fixture 😄 
Otherwise if this is not set we let it still be randomised

**Comment by bobdenotter** [comment]
If we can't add it to the `doctrine:fixtures:load`, we could perhaps just add it to `config.yaml` ?

```
fixtures_seed: 87654
```

On `bolt/core` by default, and 

```
fixtures_seed: ~
```

On `bolt/project`

**Comment by LordSimal** [comment]
I currently haven't found an easy way to extend the options available for `bin/console doctrine:fixtures:load`
Therefore setting that in the `config.yaml` would be easier because we already have the `$config` instance injected in there.

**Comment by bobdenotter** [comment]
Let's just do that, then! :-)

**Comment by LordSimal** [comment]
Lets see if your given seed of  `87654` actually works 😄

**Comment by LordSimal** [comment]
Seems it does 😄
