### ISSUE TITLE
404 error after installation

### ISSUE THREAD

**Issue by svivian** [bolt/core#2065]
I've just installed a fresh copy of the latest Bolt but I get a 404 error when loading the site. Like this:

## 404 :: Content not found

In Controller/TwigAwareController.php

```
Symfony\Component\HttpKernel\Exception\NotFoundHttpException {#5565 ▼
  -statusCode: 404
  -headers: []
  #message: "Content not found"
  #code: 0
  #file: "/.../myprojectname/vendor/bolt/core/src/Controller/TwigAwareController.php"
  #line: 123
  trace: {▶}
}
```

I followed the instructions [in the docs](https://docs.bolt.cm/4.0/installation/installation) to install via composer, i.e. I ran these:

```
composer create-project bolt/project myprojectname
(edit .env with correct MySQL parameters)
chmod -R 777 config/ public/files/ public/theme/ public/thumbs/ var/
bin/console doctrine:database:create
bin/console doctrine:schema:create
bin/console bolt:add-user --admin
```

Opening the home page via my server, or using the built-in server, I get a 404.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0
| Install type                   |  Composer
| PHP version                 | 7.2.33
| Web server                  | Apache or Built-in, both fail

**Comment by svivian** [comment]
Hmm, pretty sure I did that the first time. When it didn’t work I started over and did the individual commands.

The docs imply they are equivalent. How does selecting ‘no’ at that stage differ from running only the first 3 commands separately?

**Comment by svivian** [comment]
Also has the table prefix option been removed? Setting it in the config.yaml (under database like in v3) doesn't do anything, it always tried to use `bolt_`. I searched the docs and there is nothing there about it.

**Comment by bobdenotter** [comment]
@svivian It's in `services.yaml`, near the top.

**Comment by bobdenotter** [comment]
Closing this one.. feel free to re-open, if it requires action on our side.

**Comment by svivian** [comment]
Why do you think it doesn't require action? You said I don't need to install the demo content, but Bolt doesn't work without it. And installing it caused a fatal error. I have tried again and this time it did go through without an error, but now I have junk data I need to delete. There are two things that need fixing:

- Nothing works unless the demo content is installed.
- The demo content fails if Unsplash is down. (Though perhaps if the first one is fixed this doesn't matter.)

**Comment by bobdenotter** [comment]
> Nothing works unless the demo content is installed. 

Why not? You can log in, create content.. That works, right? 

> The demo content fails if Unsplash is down. (Though perhaps if the first one is fixed this doesn't matter.) 

That's an issue, but it's a _different_ issue than "404 error after installation", right? because that's not what was happening here. Also, there's a specific issue for that, here: https://github.com/bolt/project/issues/34

Or, let's turn it around: What do you think we should change as a response to this issue?

**Comment by svivian** [comment]
> Why not? You can log in, create content.. That works, right?

No it doesn't, as I already said. I get a 404 on `/bolt`. Now that the demo content is installed it shows using the default theme, rather than a Symfony error, but it's still a 404. The other pages in the demo content work fine so it's not due to an htaccess issue or anything like that.

Are you saying a 404 is expected for the home page? As I said it works perfectly fine in v3.7. There is the 'homepage' content type that just shows a fairly empty page, but it's still there. (The homepage contenttype is in my config.yaml on the v4 install so AFAIK it's not an issue with a missing contenttype.)

I really don't know how I can be any more specific. I've posted exactly the steps I've taken, the exact error messages with stack traces and told you what is not working.

**Comment by bobdenotter** [comment]
> No it doesn't, as I already said.

No need to get on the offense. Please don't forget i'm just trying to help (and keep the queue maintainable)

Are you _certain_ you've tried this recently? This was a bug, that was fixed, but you say you've tried it after that.

> Are you saying a 404 is expected for the home page? 

If you choose not to install the fixtures, what would you expect to see on the non-existing frontpage? 

> There is the 'homepage' content type that just shows a fairly empty page, but it's still there.

If there is a frontpage, it should show that. If it doesn't, that's a bug.

**Comment by svivian** [comment]
Sorry if you feel I was being "offensive" but I explained very clearly exactly what worked and what didn't. If you didn't bother reading it then that's on you. Like you, I'm only trying to help...

I looked through the commits and it appears that the URL for the Bolt admin was incorrectly set to something else. Oddly, you posted above shortly after you fixed it so it's a shame you didn't mention it then, but oh well.

As for the home page 404 issue, I'd expect to see a mostly blank page (like in v3.7) without installing any fixtures. A 404 implies something didn't install correctly. I mean the point of the Homepage contenttype is that there's only 1, it's not like demo content where you have to go through and delete everything. So just a blank homepage would suffice. Every CMS I've ever used has *something* to show after a basic install.

**Comment by mcbmcb0** [comment]
this one is over my simple head, but installing 4.1 with no content (i set skeleton in config.yaml) yielded the same error: the only thing i needed to do to get the frontend live was log in backend (/bolt) and add a homepage title. it would be easier for noobs like my if this basic homepage setting was set out of the box.
thanks

**Comment by bobdenotter** [comment]
@mcbmcb0 When installing, you get the question "Do you want to fill the database with fixtures (dummy content)?". Answering yes to that question literally does what you're suggesting. ;-)

**Comment by mcbmcb0** [comment]
yes, thanks Bob - i was trying to avoid installing a lot of unnecessary content and also responding to the OPs wish for it to work out the box (with no content).
thanks for all your work on this.
