### ISSUE TITLE
Cannot autowire service "Bolt\Redactor\Controller\Upload"

### ISSUE THREAD

**Issue by hanzx** [bolt/core#2085]
After composer update:

`Executing script cache:clear --no-warmup [KO]
 [KO]
Script cache:clear --no-warmup returned with error code 1
!!  
!!  In DefinitionErrorExceptionPass.php line 54:
!!                                                                                 
!!    Cannot autowire service "Bolt\Redactor\Controller\Upload": argument "$redac  
!!    torConfig" of method "__construct()" has type "Bolt\Redactor\RedactorConfig  
!!    " but this class is missing a parent class (syntax error, unexpected end of  
!!     file).                                                                      
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd
`

`Cannot autowire service "Bolt\Redactor\Controller\Upload": argument "$redac  
  torConfig" of method "__construct()" has type "Bolt\Redactor\RedactorConfig  
  " but this class is missing a parent class (syntax error, unexpected end of  
   file).                                                                      
               `

**Comment by bobdenotter** [comment]
Oops. my bad. fixed in https://github.com/bolt/redactor/commit/ee9b4aade2330a5fe2fbbaea5919bf4856418213

Run composer update again, and you'll get the fixed version.
