### ISSUE TITLE
Collection items are opened when moved up/down

### ISSUE THREAD

**Issue by simongroenewolt** [bolt/core#2115]
If you edit a content-type with a collection field, and move items up/down in the list, as a side effect content will be expanded.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 4.0 / 4.1 / master
| Install type                                          |  GitHub checkout
| <abbr title="Backwards Compatibility">BC</abbr> Break | yes/no
| PHP version                                           | 7.2 / 7.3 / 7.4 |
| Web server                                            | Apache / Nginx / Built-in, version [ version ]
| For UX/UI issues                                      | Firefox 82.0.2 (64-bit)

Reproduction
------------

Using bolt/core use 'showcase' and move the 'collection' tab.
- collapse all
- move one item up/down
- see that the item that is now at the position where you clicked is expanded

I think this has to do with the use of the details and summary tags, where a click on summary expands the details.  It looks like there is code to block the events from activating the 'opening' of the details, but that doesn't work (in firefox at least).

**Comment by simongroenewolt** [comment]
Chrome (Version 86.0.4240.183 (Official Build) (x86_64)) has the same behavior.

**Comment by simongroenewolt** [comment]
@I-Valchev I've seen your name next to a couple of accessibility items so I'm asking you :-) 

Is <details> in use as an accessibility measure, or can I create a PR that changes it to a 'plain' div if that could solve this issue?

**Comment by simongroenewolt** [comment]
Hahaha! actually using a Details tag was by accident! But I'm leaving it in!

**Comment by bobdenotter** [comment]
In general, "details" is a nice semantic HTML 5 tag, but if it's problematic here, we can probably use a plain div instead.. I wonder if it (being a native tag) has a native behaviour to open if clicked/activated? 🤔

**Comment by simongroenewolt** [comment]
It looks like it has a native click handler that takes a click anywhere in the `summary` part to mean 'open/close the details' (which is according to spec, if I've read it correctly). I can prevent it from opening by changing the buttons in `templates/_partials/fields/_collection_buttons.html.twig` and add an onclick listener there that calls event.stopPropagation(); -- but that prevents the js code in the vue part from being run as well...
I'll dig a little deeper to see if there a out of there without changing the markup too much, but I think the current setup 'misuses' the summary part to show a general header, which is not as intended by the spec.

**Comment by I-Valchev** [comment]
👋. Nice findings, @simongroenewolt .

As far as I am aware, the `details/summary` html tags do have that behaviour on click. IMHO, it would be best to leave them out because they are semantic elements, **but** when someone clicks on a button inside them, silence the native click handler.

Then:
If click on summary -> open/close
If click on button (move up/down) inside summary -> move accordingly, do _not_ open/close

**Comment by simongroenewolt** [comment]
I think to get this under control the creation of the buttons should be moved from twig to vue -- as they are already passed _via_ vue i don't think that should make the experience for the end-user any different. Without js the back-end is not functional as far as I can see.

**Comment by simongroenewolt** [comment]
Ok, I think we really should drop the detail/summary - If I understand https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary correctly it doesn't allow (or at least intend) it to be used as is done now. I'll start by moving the buttons out of the summary, and see what I can come up with.

Also: this part of the code is (in my Firefox version) not behaving as expected. It will open elements that are moved.

        /**
         * Open newly inserted collection items.
         */
        $(document).on('DOMNodeInserted', function(e) {
            if ($(e.target).hasClass('collection-item')) {
                $(e.target)
                    .find('details')
                    .first()
                    .attr('open', '');
            }
        });

And aside from not working as expected the usage of `DOMNodeInserted` is also discouraged: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events

**Comment by simongroenewolt** [comment]
Possible new lay-out that can keep the detail/summary usage:

(of course moving the up/down/delete to the right is also possible)

![Screen Shot 2020-11-10 at 15 56 28](https://user-images.githubusercontent.com/3960/98690625-6baf7380-236d-11eb-9ddb-be471c487859.png)

@bobdenotter  @I-Valchev what do you think? This way the change (in code) is minimal, as it basically only moves the set of buttons out of the original element into the parent. Visually it's quite different of course.

If you'd like to keep the current lay-out the detail/summary has to go I'd say.

**Comment by simongroenewolt** [comment]
I've rewritten detail/summary to divs and added functionality to exapand/collapse in js. PR needs some browser checks before it can be merged.
