### ISSUE TITLE
Error on trying to join discussion forum -> Ticket already created in that repo, but no response

### ISSUE THREAD

**Issue by antiftw** [bolt/core#2135]
Im creating this issue, because there has been no response for the third day to the issue I have created on the other repository.

I am unable to create a new account because the confirmation email is not being sent (I have tried for 3 days in different browsers, but the email is just not getting sent)

Related issue: [https://github.com/bolt/discuss/issues/1](url)

**Comment by bobdenotter** [comment]
The forum doesn't work very well for some.. I don't really have the resources to look into it. You're of course very welcome to join us on slack! https://slack.bolt.cm :-)

**Comment by antiftw** [comment]
Ok, thanks for the response. I looked at Slack but it told me to fill in a work email, so I wasn't sure I was also allowed in there. But since you invite me, I will come and check it out soon :)

**Comment by bobdenotter** [comment]
@antiftw It's open to the public, and everyone is welcome! 😅

**Comment by bobdenotter** [comment]
Closing this one, we're deprecating the "discuss" in favor of https://github.com/bolt/core/discussions
