### ISSUE TITLE
Ismobilclient() twig function is not implemented in bolt 4

### ISSUE THREAD

**Issue by Sandrine-D** [bolt/core#2154]
Ismobilclient() twig function is missing in bolt 4, instead if bolt 3.7

**Comment by I-Valchev** [comment]
Hi @Sandrine-D, in my view this is one of those things that should not be part of `bolt/core` itself, but rather better done as extensions that people can add to their bolt project, if they want to.

**Comment by Sandrine-D** [comment]
Hello @I-Valchev, that's fine for me, I can add it in an extension.

**Comment by I-Valchev** [comment]
Awesome! Let me know if you bump into issues building the extension.

**Comment by I-Valchev** [comment]
Hi @Sandrine-D ,

We've created an extension that you can use to achieve what you were trying to do.

Please refer to it here https://github.com/bolt/browsercheck

Feel free to create an issue in the browsercheck repository if you bump into issues using it!
