### ISSUE TITLE
🐞🐛🐜 Template select output not in alphabetical order!!1!one! 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#2168]
See screenshot: 

![Schermafbeelding 2020-11-24 om 11 36 43](https://user-images.githubusercontent.com/1833361/100083375-ade6b380-2e49-11eb-8c79-3282f7838398.png)

Why!? Why?!?

**Comment by Sandrine-D** [comment]
I saw this too and I'm wondering if the order is not by last changed date?

**Comment by bobdenotter** [comment]
It's Symfony's built-in finder thing, and it _might_ be the last changed date, but it depends on the platform so it's not reliable. Let's just make it alphabetical, and it should at least make more sense in most cases! 😇
