### ISSUE TITLE
Set sensible defaults for Avatar settings

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#2182]
To prevent this when upgrading from 4.1 to 4.2

![Schermafbeelding 2020-11-26 om 13 59 28](https://user-images.githubusercontent.com/1833361/100354598-af9eab80-2ff0-11eb-8ecb-756028be262d.png)

**Comment by simongroenewolt** [comment]
Probably stating the obvious, but adding new parameters in an 'upgrade friendly' way is easily done by configuring a working default value in the config parser(s). In this case somewhere here I'm guessing: https://github.com/bolt/core/blob/5c6d317f394f03ed0951cc3ad76636356a18eaec/src/Configuration/Parser/GeneralParser.php#L64

**Comment by I-Valchev** [comment]
Also, another related breaking change: 

The PR added this to the User entity:
https://github.com/bolt/core/blob/b2815796da8ba217275f6a6be428bfaae5cf3dbc/src/Entity/User.php#L109

Which means we'd need to create a migration and run it on time so stuff doesn't break.

**Comment by I-Valchev** [comment]
@bobdenotter It looks like #2183

 #2193 solves the config part of this, but as far as I can see we still need to figure out a solution for the `avatar` column migration, am I right?

**Comment by bobdenotter** [comment]
Yes, we'll bump into this when we do the preparations for 4.2. :-)

**Comment by I-Valchev** [comment]
Re-opening this one, so that we don't forget about the extra column issue.

**Comment by I-Valchev** [comment]
Config issue fixed in #2193 
Migration issue fixed in #2232 

Hence it is safe to close this as it will no longer constitute a BC.
