### ISSUE TITLE
Listing pages have different canonical when using singular or plural form

### ISSUE THREAD

**Issue by doup** [bolt/core#2218]
Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.1.5
| Install type                   | GitHub checkout (bolt/core)
| BC Break                     | no
| PHP version                 | 7.4
| Web server                  | Built-in PHP

Reproduction
------------

### Bug summary

- On `bolt/core` with the default fixtures
- Both `/pages` & `/page` show the listing page **but** have a different canonical URL
  - `/pages` canonical is `/pages` (plural) 
  - `/page` canonical is `/page` (singular)
- This happens also when prefixing with locales 

![listing-canonical](https://user-images.githubusercontent.com/188612/101279259-563d3600-37c1-11eb-854d-01db3003bb8b.gif)

### Expected result

- Both `/pages` & `/page` should point to the same canonical `/pages`

### Actual result

- `/pages` and `/page` have different canonical

**Comment by I-Valchev** [comment]
Hi @doup , thanks for submitting the issue. A fix is in the pipeline :-)

**Comment by I-Valchev** [comment]
Actually, @doup , did you not fix this already in https://github.com/bolt/core/pull/2234?

**Comment by doup** [comment]
This is fixed by #2234. I prefer if you close this, I don't know what's your process.
