### ISSUE TITLE
Add a new config option to tell Bolt if the canonical URL should force-prefix the default locale or not

### ISSUE THREAD

**Issue by doup** [bolt/core#2219]
This could be interesting as you might start with a single locale (`en`), tell it to force the URLs without the default locale (`/pages`). Later on you decide to add a new locale (`es`), you could leave it as it was (e.g. `/pages` & `/es/pages`), but if you prefer to have for consistency all the URLs prefixed you could change this config so the canonical URLs always have the locale (e.g. `/en/pages` & `/es/pages`).

On root path `/` if locale prefix is enforced then it should redirect to `/<default_locale>/` (`/en/`).

How can you help?
-------------------------------

I can implement this if few guidelines/pointers are provided, e.g.: name of the config option, in which config file should go (`bolt/config.yaml`, `services.yml`?), general approach.

**Comment by I-Valchev** [comment]
Hi @doup ,

Happy to give some pointers here. I think the changes need to be implemented somewhere around here:

https://github.com/bolt/core/blob/de43643cafaf2e37473283847e19929c14883dd8/src/Utils/ContentHelper.php#L48-L62

And possibly further in the `getCanonicalRouteAndParams` call.

Where in config this would go depends on how it works. I can think of two options:

**Option 1: One config for the entire site**
This means we'll set the option once and it will apply to all ContentTypes across the site. If that's the case, it will go under `bolt/config.yaml`, most likely under the `localization` setting. (I don't know if that's added to the yaml file yet, but there is a `localization` key with `fallback_when_missing: true/false` option inside it.

**Option 2: One config per ContentType**
If we want to control this on a per ContentType level, it will need to be part of each ContentType config specifically, inside `contenttypes.yaml`.

In both cases, we should provide a default fallback config if it is missing. For a recent example of how to do this you can check https://github.com/bolt/core/pull/2077/files this PR (check `GeneralParser.php`).

Personally, I feel that option 1 is preferable. I can't think of a short, understandable option name right now! Feel free to add your suggestions 🙂

**Comment by doup** [comment]
This is fixed by #2234. I prefer if you close this, I don't know what's your process.

**Comment by I-Valchev** [comment]
Nice, let's close this. :-)

What we normally do, is in the first comment when you open a PR to fix an issue, say "Fixes #(issue number)" which automatically closes the issue when the PR is merged. Here's more if you're interested: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

Thanks anyway, I'm going to close this one now.
