### ISSUE TITLE
Replace our fork of `webdriver-binary-downloader`

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#2221]
And we'll replace it with `LANFest/webdriver-binary-downloader`, as discussed on slack: https://boltcms.slack.com/archives/C094GL7ME/p1607102915068600?thread_ts=1607023637.009500&cid=C094GL7ME

**Comment by japerry** [comment]
Great to hear! I'll let Travis Carden (who did a PR on your branch) that we're moving to the lanfest branch. And please, if you see any issues, feel free to make PRs and I'll get them merged in ASAP!

**Comment by japerry** [comment]
Oh, I found out I can add you as a co-maintainer, so if you wish, you can push to the lanfest fork as well now.

**Comment by bobdenotter** [comment]
I've abandoned the packages at packagist, in favor of the Lanfest forks! 👍 

https://packagist.org/packages/bolt/binary-chromedriver
https://packagist.org/packages/bolt/webdriver-binary-downloader

I've added a deprecation notice to our forks on github as well. 

Thanks, @japerry
