### ISSUE TITLE
Error 500: Notice: Undefined index: image (during image upload using WYSIWYG)

### ISSUE THREAD

**Issue by vbeskrovny** [bolt/core#2244]
Tried to upload an image using WYSIWYG editor and Bolt gives the following error:

![image](https://user-images.githubusercontent.com/38423084/102016147-b7d04800-3d5f-11eb-86af-74cb4d8e826d.png)

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0
| Install type                   |  Composer install
| BC Break                     | yes/no ???
| PHP version                 | 7.3
| Web server                  | Nginx
| For UX/UI issues        | Firefox 83 (x64)

Reproduction
------------

1. Install Bolt using composer
2. Goto pages
3. Create new page and insert a photo using the WYSIWYG editor
4. Error occurs.

PS: the image gets uploaded though:

![image](https://user-images.githubusercontent.com/38423084/102017849-aa1fc000-3d69-11eb-92af-dc95093a6286.png)

**Comment by bobdenotter** [comment]
Hi, Which version of Bolt exactly?

**Comment by vbeskrovny** [comment]
![image](https://user-images.githubusercontent.com/38423084/102018120-7fcf0200-3d6b-11eb-8129-4f79711f7853.png)

**Comment by vbeskrovny** [comment]
4.1.8

**Comment by postal** [comment]
I guess the "image" tag is missing in the getDefaults() method of the RedactorConfig class.

**Comment by postal** [comment]
I created a PR https://github.com/bolt/redactor/pull/14 for that issue.

**Comment by I-Valchev** [comment]
Seeing the PR in Redactor https://github.com/bolt/redactor/pull/14 created by @postal (nice work!) was merged in, let's close this one :-)
