### ISSUE TITLE
[RFC] Textarea attributes (add maxlength, remove pattern)

### ISSUE THREAD

**Issue by napley** [bolt/core#2284]
The pattern attribute is not working for textarea input : https://developer.mozilla.org/fr/docs/Web/HTML/Element/Textarea

- So I propose to remove the pattern option for textarea fieldtype.
- Moreover I think useful to add the maxlength attribute support for the textarea fieldtype to compensate for the lack of pattern support.

I already made a branch in my repo, I can create a PR

**Comment by I-Valchev** [comment]
Nice! I'm going to assign this issue to you then, thanks @napley !
