### ISSUE TITLE
Allow user to configure Bolt's assets directory

### ISSUE THREAD

**Issue by pevdh** [bolt/core#2298]
By default, Bolt writes all its assets to the public/assets directory with the bolt:copy-assets command. I am currently trying to integrate Bolt into an existing website, which also uses public/assets. This is a problem because Bolt overwrites the entrypoints.json and manifest.json files.

A simple solution and straightforward would be to allow the user to configure where Bolt stores its assets in config/bolt/config.yaml.

How can you help?
-------------------------------
I am willing to implement this feature myself. However, I am new to the project so I wanted to ask for input before opening a PR.

**Comment by I-Valchev** [comment]
hi @pevdh , really good suggestion!

I'd suggest adding an optional parameter to the `bolt:copy-assets` command that will override the destination folder.

This is where the command is defined:
https://github.com/bolt/core/blob/4.1/src/Command/CopyAssetsCommand.php

It uses the Symfony Console component, you can check the symfony docs to see how to add optional parameters. You can also check examples of how we've used other commands here:
https://github.com/bolt/core/tree/4.1/src/Command

**Comment by pevdh** [comment]
Thanks for the quick response! Unfortunately, adding an option to copy-assets is only part of the solution. The public/assets/ directory is hardcoded in webpack.config.js (see setOutputPath() and setPublicPath()), which causes everything in the entrypoints.json and manifest.json to point to /assets.

encore_entry_link_tags and encore_entry_script_tags use entrypoints.json to build script and link tags, so the generated HTML will still point to /assets, causing 404s.

I think modifying Bolt to use a different directory such as /public/bolt-assets (just a suggestion) would be a better solution, but that would obviously be a breaking change.

**Comment by I-Valchev** [comment]
hi @pevdh , yes you are indeed correct, nice findings.

It turns out that having a configurable assets folder was implemented in Bolt 3, and it used to cause issues and problems for people. Based on that, it is more preferable that if there is a conflict, you'd change your project's assets. It will also be much easier to implement in a specific project than more generally in bolt itself.
