### ISSUE TITLE
Translation is not updated when editing in PHP Translation bundle WebUI.

### ISSUE THREAD

**Issue by napley** [bolt/core#2305]
When it works a message is display when the field lost the focus :
![image](https://user-images.githubusercontent.com/6539378/104193890-e3a72200-5420-11eb-82bb-7f9c7d1acd80.png)

Current behaviour we are an error :
webui.js:29 Uncaught ReferenceError: editUrl is not defined
    at editTranslation (webui.js:29)
    at HTMLTextAreaElement.onchange (VM123 messages:147)

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version  | 4.1.10
| Install type                   |  Composer install
| BC Break                     | no
| PHP version                 | 7.4
| Web server                  | Nginx
| For UX/UI issues        | Firefox 84

Reproduction
------------

Edit an translation field in the PHPTranslation WebUI

The problem
------------

The template manage in bolt/core templates/bundles/TranslationBundle/WebUI/base.html.twig doesn't editUrl like the translationBundle does.

I will make a PR with the fix

PS : For a quick solution, I tested to override the template as we do for other Symfony bundles but it didn't work, can't it be done?

**Comment by I-Valchev** [comment]
Fixed by #2306
