### ISSUE TITLE
[4.2] Small regression in login screen

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#2316]
4.2 introduces Symfony forms for the login screen, but in doing so we've lost the small "Show password" button. We should put that back. 

Before:  

![Screenshot 2021-01-14 at 16 25 46](https://user-images.githubusercontent.com/1833361/104611523-8233bd00-5685-11eb-961e-b4bc08049412.png)

After: 

![Screenshot 2021-01-14 at 16 26 13](https://user-images.githubusercontent.com/1833361/104611538-865fda80-5685-11eb-8954-039e72a4f52f.png)

**Comment by I-Valchev** [comment]
@bobdenotter I am not sure I can replicate this, here is what I get on the master branch:

![image](https://user-images.githubusercontent.com/7093518/104891116-c9b19600-5970-11eb-823f-0bebe0603184.png)

**Comment by bobdenotter** [comment]
Fixed in #2351
