### ISSUE TITLE
Unexpected length output

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#2328]
I want to show the total number of records from a contenttype in a template. I use the following code in my template:

```
{% setcontent personen = 'personen' %}
{{ personen|length }}
```
This works but the max amount shown is 20 (there are 70+ published records)

From config.yaml:
`listing_records: 10`
No additional listing_records is set in contenttypes.yaml

I expected the total amount of records from my contenttype. 
But {{ personen|length }} shows the right amount of records until it hits 20. 

It's fixed by adding LIMIT to the query:
`{% setcontent counter1 = "personen" limit 100000 %}`

-------
Bolt 4.1.11

**Comment by I-Valchev** [comment]
Hi @peterboorsma ,

In fact this is the _correct_ behaviour, even if it appears strange. If you don't specify the limit directive, by default Bolt will use 20. https://docs.bolt.cm/4.0/templating/content-fetching#using-limit

**Comment by peterboorsma** [comment]
But why the default? When I don't set a limit, I don't expect to be limited. :)

**Comment by I-Valchev** [comment]
Because most of the time you'd only need a handful of records, in which case it is a much more "expensive" (time, memory) and inefficient operation if it were to grab 100-1000-10000 records.

**Comment by peterboorsma** [comment]
Point taken. I noticed this behavior in a query that will result in 30.000+ records. Twice on a page. I'm a bit worried about how that's gonna work out.

Now I know this, it isn't a problem anymore. But I do think it's counter-intuitive.

**Comment by bobdenotter** [comment]
You can use `{{ records.nbResults }}` to output the total number of records. 

I've written a short bolt-tip on it: https://bolt.tips/entry/outputting-the-total-number-of-records-for-a-contenttype
