### ISSUE TITLE
Select field with multiple values has empty loop

### ISSUE THREAD

**Issue by napley** [bolt/core#2368]
Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version |  4.1.11 
| Install type                   |  Composer install
| BC Break                     | no
| PHP version                 | 7.4 |
| Web server                  | Nginx
| For UX/UI issues        | Chrome 88

Reproduction
------------

We have created a select field type with multiple paramter to true like this :
```
services:
            label: Ajouter des services
            type: select
            multiple: true
            autocomplete: true
            sortable: true
            group: Services
            values:
              {
                  mail-management: "Gestion, réexpedition, scan de votre courrier",
                  registered-mail: "Prise en charge de votre recommandés",
                  call-management: "Gestion personnalisée de vos appels/messages",
                  administrative-assistance: "Assistance administrative",
                  financial-support: "Support comptable, financier et juridique",
                  creation: "Aide à la création et la gestion d'entreprise"
              }
```
In database, we have this with three values selected:
`["it-support","registered-mail","administrative-assistance"]`

But when I dump field information in front I have this:

![image](https://user-images.githubusercontent.com/6539378/107020235-eb00e780-67a2-11eb-926c-a9503e0f2c3f.png)

Finally, it doesn't loop like this for the values:
```
{% for value in solution.services %}
    {% dump(value) %}
{% endfor %}
```

For a fast fix I loop on select option and test if selected is true:
```
{% set listServices = select_options(solution.services) %}
{% for service in listServices %}
    {% if service.selected == true %}
            //Code
    {% endif %}
{% endfor %}
```

I don't found why there is no value on field information, have you an idea ?

**Comment by I-Valchev** [comment]
Hi @napley, thanks for reporting this issue and the detailed bug report.

A fix is in the pipeline!
