### ISSUE TITLE
Fields in a set won't get deleted when removed from contenttypes.yaml

### ISSUE THREAD

**Issue by M-Stgelais** [bolt/core#2387]
Hello,

I'm using Bolt 4 with PHP 7.3, and I keep getting the same bug over and over. When I delete or rename a field inside a set, the deleted/renamed field still show up in the already created content when I edit it. To get rid of it, I have to rename my set field, to sort of "re-create" the set, but if I rename it back to it's original name, the old fields show up again.

Here is how to reproduce the issue:
![1](https://user-images.githubusercontent.com/78932889/107695627-e050c180-6c7e-11eb-96ab-85664f6c9f78.PNG)
![2](https://user-images.githubusercontent.com/78932889/107695642-e21a8500-6c7e-11eb-8931-9876004544ed.PNG)

And here is what happen when I rename my "page_content" field to "page_content_2", the old field still show up, along with the "new/renamed" field:

![3](https://user-images.githubusercontent.com/78932889/107695743-024a4400-6c7f-11eb-85af-ddd83e8a9414.PNG)
![4](https://user-images.githubusercontent.com/78932889/107695750-037b7100-6c7f-11eb-8f05-9535c4805abb.PNG)

Am I doing something wrong? Or is that a bug? The entries still seem to exist even if they are deleted from contenttypes.yaml.

Thank you!

**Comment by I-Valchev** [comment]
Hi @M-Stgelais , thank you for the detailed issue report!

A bug for this is in the pipeline, see #2400.
