### ISSUE TITLE
Main configuration page gives error: mb_strpos() expects parameter 1 to be string, null given.

### ISSUE THREAD

**Issue by romokebi** [bolt/core#2393]
Hello there, I've recently discovered Bolt and I was giving it a try.
Unfortunately, while navigating through the admin panel, after clicking on "Configuration > Main configuration" I ran into the following error:

`mb_strpos() expects parameter 1 to be string, null given.`

I'm a dev but I don't have much experience with Symfony and servers in general so I'm reaching out to you to see if this is a mistake of mine or something. 

Thank you for any help in advance.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version  |  4.1.12
| Install type                   |  Composer install
| BC Break                      |  ?
| PHP version                 |  7.4 
| Web server                  |  Nginx
| OS                                |  Linux Alpine 
| Docker image              |  webdevops/php-nginx:7.4-alpine

Reproduction
------------

### Bug summary

` mb_strpos() expects parameter 1 to be string, null given `

in vendor/bolt/core/src/Controller/Backend/FileEditController.php (line 56)
in vendor/bolt/core/src/Controller/Backend/FileEditController.php mb_strpos (line 56)
in vendor/symfony/http-kernel/HttpKernel.php -> edit (line 157)
in vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 79)
in vendor/symfony/http-kernel/Kernel.php -> handle (line 195)
Kernel->handle(object(Request))
in public/index.php (line 39)

### Specifics

URL: 
` http://localhost:8081/bolt/file-edit/config?file=/bolt/config.yaml `

### Steps to reproduce

Admin panel > Configuration > Main configuration

### Expected result

Expecting no errors

### Actual result

` mb_strpos() expects parameter 1 to be string, null given `

**Comment by I-Valchev** [comment]
Hey @romokebi ,

Thank you for the bug report.

I have the feeling that there is something strange going on with the URL.

I think it is missing an `=` after `?file`, like so: `/bolt/file-edit/config?file=/bolt/config.yaml`

Can you check if that works? I'm still not able to reproduce the error on my end.

**Comment by romokebi** [comment]
Hi @I-Valchev !
Thank you for your reply and sorry for my late one. 

I am really sorry I must have pasted the link incorrectly, I can confirm the " = " sign is actually present (I'am going to edit my original post).
I've just created another testing environment and gave it `777` to make sure it wasn't a permissions problem.
I now have a different error, still on almost any of the configuration settings files:

`Argument 2 passed to Bolt\Utils\PathCanonicalize::canonicalize() must be of the type string, null given, called in /var/www/html/mybolt/vendor/bolt/core/src/Controller/Backend/FileEditController.php on line 59`

Does it ring any bells?? 

Thank you again, your support is much appreciated!

**Comment by I-Valchev** [comment]
Fantastic, glad you managed to solve it! Do you think we need to update the nginx config in the [documentation](https://docs.bolt.cm/4.0/installation/webserver/nginx) to make sure others don't fall into the same trap?

**Comment by romokebi** [comment]
No @I-Valchev , I had totally missed the nginx config part of the docs, my bad. Being it a late night side project I'm usually pretty tired at that time, haha. 
Glad to see such support and kindness, thank you. 
I'm loving bolt so far BTW.
I will get back to you guys with some suggestions, should I have any!
Have a great day! 🙂
