### ISSUE TITLE
Duplicate a record seems to break Article and Redactor fields

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#2414]
When choosing to duplicate a record, it looks like the Article and Redactor fields are not being loaded correctly.

**Comment by bobdenotter** [comment]
Merged and tagged new releases for Redactor and Article.

**Comment by eduardomart** [comment]
Could this be related to [this](https://github.com/bolt/article/issues/22) ?

**Comment by I-Valchev** [comment]
@eduardomart I am not sure, not been able to reproduce it yet.

Seeing that all linked PRs have been merged in, it's time to close this issue. 👍
