### ISSUE TITLE
You don't have permission to access /media/edit/{id}

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#2424]
Hi!

As spotted with @I-Valchev I'm opening this issue.

I no longer can see the edit page of the the uploaded media when navigating to `/media/edit/{id}`

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | master
| Install type                   | Composer install
| PHP version                 | 7.3 
| Web server                  | Built-in, symfony

Reproduction
------------
In the CMS:
1. Go to File Management -> Uploaded files.  `/filemanager/files`
2. Upload an image or use an existing one
3. Click on the image title
4. You get redirected to the Bolt Dashboard

### Expected result

See the edit page of the image

### Actual result

Redirected to Bolt Dashboard

**Comment by bobdenotter** [comment]
This is fixed, probably in #2450 

If it doesn't work yet, please update `permissions.yaml` to look like this: https://github.com/bolt/core/blob/master/config/bolt/permissions.yaml
