### ISSUE TITLE
[5.0] Require login when `IS_AUTHENTICATED_REMEMBERED` is insufficient.

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#2450]
With the new permissions feature, we make proper use of permissions.

`IS_AUTHENTICATED_REMEMBERED` is weaker than `IS_AUTHENTICATED_FULLY`, but some actions, such as editing a profile, require `IS_AUTHENTICATED_FULLY`.

In those cases, when a user is authenticated with `IS_AUTHENTICATED_REMEMBERED`, Bolt should redirect to the login page to ask for full authentication, rather than forbidding the action completely.

**Comment by bobdenotter** [comment]
Fixed in #2458
