### ISSUE TITLE
`contentRepository->findOneByFieldValue` doesn't work with integers or numeric strings

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#2478]
Let's say you're doing something like this:

```
$om = $this->getObjectManager();
$contentRepository = $om->getRepository(Content::class);

// works as expected
$content = $contentRepository->findOneByFieldValue('itemid', 'a1b2c3d4');

// does not work
$content = $contentRepository->findOneByFieldValue('itemid', 12345);
```

Then it will not return the `$content` for the second one.

**Comment by I-Valchev** [comment]
@bobdenotter Works for me with this setup:

![image](https://user-images.githubusercontent.com/7093518/111998488-55d06d00-8b1c-11eb-9211-5d60b8e7e489.png)

When you tested it, was it with a JSON database or not? 🤔   It sounds plausible that the non-JSON databases break?

**Comment by I-Valchev** [comment]
As we've not seen this pop up, let's close it for now. We can always re-open it if it shows up agian.
