### ISSUE TITLE
Cleanup in FieldFillListener seems to be unused

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#2481]
It seems like this part is never triggered: 

https://github.com/bolt/core/blob/4.1/src/Event/Listener/FieldFillListener.php#L41-L47

(I found out, because the code samples on bolt.tips contain `ZWSP` if saved twice, while these should have been stripped)

**Comment by I-Valchev** [comment]
Does it have this?
https://github.com/bolt/core/blob/4.1/config/services.yaml#L57

I think it got added in one of the RCs, and the bolt.tips might have been older?

**Comment by bobdenotter** [comment]
Yes, I checked that, but no dice: https://github.com/bobdenotter/bolt-tips/blob/master/config/services.yaml#L58

**Comment by I-Valchev** [comment]
Running it on master, in `bolt/core` it worked:

![image](https://user-images.githubusercontent.com/7093518/112130072-5aeaf600-8bc8-11eb-958b-32d1c5875b31.png)

First one has the `ZWSP`, the second one does not.

**Comment by I-Valchev** [comment]
Let's close this for now, and come back to it if we need to

**Comment by bobdenotter** [comment]
In the location where I bumped into this (bolt.tips), it's working correctly now. So yes, it was probably PEBCAK. :-)
