### ISSUE TITLE
SQL error after installing 5.0 b5

### ISSUE THREAD

**Issue by Dwev** [bolt/core#2536]
After upgrading to 5.0b5 via 4.2b11 I get this error:

An exception occurred while executing 'SELECT t0.id AS id_1, t0.content_type AS content_type_2, t0.status AS status_3, t0.created_at AS created_at_4, t0.modified_at AS modified_at_5, t0.published_at AS published_at_6, t0.depublished_at AS depublished_at_7, t0.author_id AS author_id_8, t9.id AS id_10, t9.display_name AS display_name_11, t9.username AS username_12, t9.email AS email_13, t9.password AS password_14, t9.roles AS roles_15, t9.lastseen_at AS lastseen_at_16, t9.last_ip AS last_ip_17, t9.locale AS locale_18, t9.backend_theme AS backend_theme_19, t9.status AS status_20, t9.avatar AS avatar_21 FROM bolt_content t0 LEFT JOIN bolt_user t9 ON t0.author_id = t9.id WHERE t0.content_type = ? AND t0.id = ? LIMIT 1' with params ["homepage", 1]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't9.avatar' in 'field list'

Adding a field called "avatar" to the bolt_user table fixed this, but not sure what its attributes should be...

Was there an intermediate step I missed that would change the DB?

**Comment by bobdenotter** [comment]
Did you follow the upgrade steps here?

https://github.com/bolt/core/discussions/2318

After that, you'll either need to run the migration and/or fix it by updating the schema:

```bash
bin/console doctrine:schema:update -v --dump-sql --force --complete
bin/console doctrine:migrations:sync-metadata-storage -q
bin/console doctrine:migrations:version --add --all -n -q
```

**Comment by Dwev** [comment]
Yes, I followed the upgrade steps in 2318.
I didn't know about the migration steps though...  I'm new to Bolt, so maybe I missed the documentation about migrating?

I can see the scheme update worked to add the avatar column as a varchar(250).  Thanks!

**Comment by bobdenotter** [comment]
>  I'm new to Bolt, so maybe I missed the documentation about migrating?

Well, since 5 is not out yet, we didn't really document that thoroughly just yet. ;-)

**Comment by Michael-1** [comment]
I think now that Bolt 5 has been released is the time for including that into the documentation. :-)
