### ISSUE TITLE
PHP Fatal error:  Declaration of Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with Psr\Container\ContainerInterface::has($id)

### ISSUE THREAD

**Issue by LordSimal** [bolt/core#2546]
Tried to update BoltCMS (as I always do weekly-ish) via `composer update -W` and got the following error:

```
boltcms@home [09:41:56 PM] [~/httpdocs] 
-> % composer update -W
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "^5.1"
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package sensiolabs/security-checker is abandoned, you should avoid using it. Use https://github.com/fabpot/local-php-security-checker instead.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
drupol/composer-packages: Regenerating classes...
drupol/composer-packages: Done.
98 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear --no-warmup [KO]
 [KO]
Script cache:clear --no-warmup returned with error code 255
!!  PHP Fatal error:  Declaration of Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with Psr\Container\ContainerInterface::has($id) in /var/www/pfiff.me/boltcms/httpdocs/vendor/symfony/dependency-injection/ServiceLocator.php on line 46
!!  
Script @auto-scripts was called via post-update-cmd
```

Composer Version: 2.0.11 2021-02-24 14:57:23

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.1
| Install type                   | Composer install
| PHP version                 | 7.4.16 with psr PHP Module
| Web server                  | Nginx

Here are all my installed PHP Modules

<details>
  <summary>PHP Modules</summary>
  
  apc
  apcu
  bcmath
  calendar
  Core
  ctype
  curl
  date
  dom
  exif
  FFI
  fileinfo
  filter
  ftp
  gd
  gettext
  gmp
  hash
  iconv
  imagick
  imap
  intl
  json
  libxml
  mbstring
  mysqli
  mysqlnd
  openssl
  pcntl
  pcre
  PDO
  pdo_mysql
  pdo_pgsql
  pdo_sqlite
  pgsql
  Phar
  posix
  pspell
  psr
  readline
  Reflection
  session
  shmop
  SimpleXML
  soap
  sockets
  sodium
  SPL
  sqlite3
  standard
  sysvmsg
  sysvsem
  sysvshm
  tidy
  tokenizer
  xml
  xmlreader
  xmlrpc
  xmlwriter
  xsl
  Zend OPcache
  zip
  zlib
  
  [Zend Modules]
  Zend OPcache
</details>

**Comment by LordSimal** [comment]
I also tried
```
rm -rf vendor
rm composer.lock
composer install
```
still the same problem

**Comment by bobdenotter** [comment]
I've not seen this happen myself, yet.. Can you try `composer update -W -v` to see if it gives more verbose output?

**Comment by LordSimal** [comment]
It is related to https://github.com/jbboehr/php-psr/issues/88
Basically, as I already expected, you will only get this error when you have the php-psr module installed in your OS.
If you don't have that module installed and use the "default" composer installed packages everything is fine.
I guess thats why you dont get that error

**Comment by LordSimal** [comment]
but here is the output of `composer update -W -v`

<details>
  <summary>Click me!</summary>
  
  ```
  boltcms@home [06:33:33 PM] [~/httpdocs]
-> % composer update -W -v
> pre-update-cmd: Symfony\Flex\Flex->configureInstaller
> pre-update-cmd: cweagans\Composer\Patches->checkPatches
Loading composer repositories with package information
> pre-pool-create: Symfony\Flex\Flex->truncatePackages
Restricting packages listed in "symfony/symfony" to "^5.1"
Updating dependencies
Dependency resolution completed in 0.095 seconds
Analyzed 6317 packages to resolve dependencies
Analyzed 68329 rules to resolve dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package sensiolabs/security-checker is abandoned, you should avoid using it. Use https://github.com/fabpot/local-php-security-checker instead.
Generating autoload files
> post-autoload-dump: PackageVersions\Installer->dumpVersionsClass
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> post-autoload-dump: drupol\ComposerPackages\Plugin->regeneration
drupol/composer-packages: Regenerating classes...
drupol/composer-packages: Done.
> post-autoload-dump: Symfony\Flex\Flex->updateAutoloadFile
98 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> post-update-cmd: Symfony\Flex\Flex->update

Run composer recipes at any time to see the status of your Symfony recipes.

> post-update-cmd: @auto-scripts
> auto-scripts: Symfony\Flex\Flex->executeAutoScripts
Executing script cache:clear --no-warmup
Executed script cache:clear --no-warmup  [KO]
 [KO]
Script cache:clear --no-warmup returned with error code 255
!!  PHP Fatal error:  Declaration of Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with Psr\Container\ContainerInterface::has($id) in /var/www/pfiff.me/boltcms/httpdocs/vendor/symfony/dependency-injection/ServiceLocator.php on line 46
!!
Script @auto-scripts was called via post-update-cmd
  ```
</details>

**Comment by LordSimal** [comment]
I also get the same problem with a completely unrelated Drupal 9 installation so its nothing directly related with Bolt.
Its a symfony problem combined with the php-psr module which you can seperately install in your OS.
So I will close this issue since it will probably fix itself.

**Comment by LordSimal** [comment]
It seems like there is a difference between the php-psr Module which you can install in the OS and the psr interface which is installed via composer. https://github.com/symfony/symfony/issues/40870#issuecomment-822811607
Currently the easiest solution for me is to just uninstall the php-psr module from the OS.
`sudo apt remove php7.4-psr` 
After that everything is fine

**Comment by hamzaeddr** [comment]
just clear the cache and try again
