### ISSUE TITLE
Checkbox field setcontent where clause exception

### ISSUE THREAD

**Issue by ntomka** [bolt/core#2547]
I'm playing with the new 5.0.0 beta 5 version of Bolt and I have a problem with checkbox fields in templates. I'm trying to fetch content where a checkbox field is checked, like this.

```twig
{% setcontent fooRecords = 'foos' where { checkboxField: true } %}
```

But I'm getting an exception:

`
Argument 2 passed to Bolt\Doctrine\JsonHelper::wrapJsonFunction() must be of the type string or null, bool given, called in /srv/www/vendor/bolt/core/src/Storage/SelectQuery.php on line 325
`

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 5.0.0 beta 5
| Install type                   |  Composer install
| BC Break                     | no
| PHP version                 | 7.4.16
| Web server                  | nginx/1.19.3
| Database server | MySQL 5.7.32
| For UX/UI issues        | -

### Steps to reproduce

Contenttype like this:

```yaml
foos:
    name: Foos
    singular_name: Foo
    fields:
        name:
            type: text
            variant: inline
            label: Name
        checkboxField:
            type: checkbox
```

Fetch contents like this:

```twig
{% setcontent fooRecords = 'foos' where { checkboxField: true } %}
```

### Expected result

Contents according to where clause.

### Actual result

Exception:

`
Argument 2 passed to Bolt\Doctrine\JsonHelper::wrapJsonFunction() must be of the type string or null, bool given, called in /srv/www/vendor/bolt/core/src/Storage/SelectQuery.php on line 325
`

<details>
<summary>Stack trace:</summary>

```
TypeError:
Argument 2 passed to Bolt\Doctrine\JsonHelper::wrapJsonFunction() must be of the type string or null, bool given, called in /srv/www/vendor/bolt/core/src/Storage/SelectQuery.php on line 325

  at vendor/bolt/core/src/Doctrine/JsonHelper.php:23
  at Bolt\Doctrine\JsonHelper::wrapJsonFunction()
     (vendor/bolt/core/src/Storage/SelectQuery.php:325)
  at Bolt\Storage\SelectQuery->build()
     (vendor/bolt/core/src/Storage/Handler/SelectQueryHandler.php:44)
  at Bolt\Storage\Handler\SelectQueryHandler->__invoke()
  at call_user_func()
     (vendor/bolt/core/src/Storage/ContentQueryParser.php:457)
  at Bolt\Storage\ContentQueryParser->fetch()
     (vendor/bolt/core/src/Storage/Query.php:66)
  at Bolt\Storage\Query->getContentByScope()
     (vendor/bolt/core/src/Storage/Query.php:86)
  at Bolt\Storage\Query->getContentForTwig()
     (var/cache/dev/twig/a9/a99dd26a4bb9ce7a3019e8513c7c3ecdee55e2f6566eb0648e2629c5705d3b59.php:139)
  at __TwigTemplate_5910ccc0b8688d80c6c414080f4399caf6f7d50e1695877bd8ad7f7844cb8b49->block_main()
     (vendor/twig/twig/src/Template.php:171)
  at Twig\Template->displayBlock()
     (var/cache/dev/twig/5b/5b57a53ec61eb780bb228fd541f88b33d57086bbd6b7ffc27bd025ad55d7cefc.php:219)
  at __TwigTemplate_1f1c69ee45af87ebc36a5194ed5e08d7fda52bd54b27c398dee8f2ae51e2af37->doDisplay()
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling()
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display()
     (var/cache/dev/twig/a9/a99dd26a4bb9ce7a3019e8513c7c3ecdee55e2f6566eb0648e2629c5705d3b59.php:48)
  at __TwigTemplate_5910ccc0b8688d80c6c414080f4399caf6f7d50e1695877bd8ad7f7844cb8b49->doDisplay()
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling()
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display()
     (var/cache/dev/twig/0a/0afa37713518f5bc9d0e4a86d9b75c7160c4a49ab13d5fc31aa10b3414c5a9dc.php:47)
  at __TwigTemplate_fcb02321d9a6f1382205ebbac478d1f563d3d0d533c9bf31c4cc325fad0fb623->doDisplay()
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling()
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display()
     (vendor/twig/twig/src/Template.php:379)
  at Twig\Template->render()
     (vendor/twig/twig/src/TemplateWrapper.php:40)
  at Twig\TemplateWrapper->render()
     (vendor/twig/twig/src/Environment.php:277)
  at Twig\Environment->render()
     (vendor/bolt/core/src/Controller/TwigAwareController.php:108)
  at Bolt\Controller\TwigAwareController->render()
     (vendor/bolt/core/src/Controller/TwigAwareController.php:158)
  at Bolt\Controller\TwigAwareController->renderSingle()
     (vendor/bolt/core/src/Controller/Frontend/HomepageController.php:56)
  at Bolt\Controller\Frontend\HomepageController->homepage()
     (vendor/symfony/http-kernel/HttpKernel.php:157)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:195)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:30)            
```
</details>

**Comment by ntomka** [comment]
Also, if I commment out the line 325 in `SelectQuery.php` which is this

```php
$param = JsonHelper::wrapJsonFunction(null, $param, $query->getEntityManager()->getConnection());
```

... I don't get an exception. Instead boolean parameter in the query converted by doctrine to integer:

```sql
(JSON_EXTRACT(b2_.value, '$[0]') = 1 AND b1_.parent_id IS NULL AND b1_.name = 'checkboxField'
```

This is also not correct because JSON_EXTRACT gives the correct boolean value back and if I change 1 to true in the query I get the correct results.

**Comment by I-Valchev** [comment]
Hi @ntomka , thanks for creating a detailed, reproducible bug report! 

A PR that fixes the issue is in the pipeline :-)

**Comment by ntomka** [comment]
Thank you!

I also tried your fix in my environment but what

**Comment by ntomka** [comment]
Thank you!

I also tried your fix in my local environment, but then the same happens as above:

> boolean parameter in the query converted by doctrine to integer:
> 
> ```sql
> (JSON_EXTRACT(b2_.value, '$[0]') = 1 AND b1_.parent_id IS NULL AND b1_.name = 'checkboxField'
> ```
> 
> This is also not correct because JSON_EXTRACT gives the correct boolean value back and if I change 1 to true in the query I get the correct results.

At least for me, that's why I didn't come up with this solution here. Am I doing something wrong?

**Comment by I-Valchev** [comment]
Hm, for me it _does_ work. I think I might need a few more details about this one.

Can you show the output to of `php bin/console bolt:info`?
If you are using `setcontent`, can you add `printquery` at the end, e.g. `{% setcontent fooRecords = 'foos' where { checkboxField: true } printquery %}` and show that output as well?

Thanks!

**Comment by ntomka** [comment]
```sh
$ bin/console bolt:info

⚙️  Bolt
=======

 Bolt version: 5.0.0 beta 5
 
 * Install type: Packaged distribution
 * Database: mysql 5.7.32 - <docker-compose-service>-mysql via TCP/IP (with JSON)
 * PHP version: 7.4.16
 * Symfony version: v5.2.6
 * Operating System: Linux - 5.8.0-50-lowlatency
 ```

I have checked on another contenttype, here is the query:

```sql
SELECT content FROM Bolt\Entity\Content content
LEFT JOIN content.fields fields_featured
LEFT JOIN fields_featured.translations translations_featured
WHERE
  content.contentType = :ct0
  AND (
    (
      JSON_EXTRACT(translations_featured.value, '$[0]') = :featured_1
      AND fields_featured.parent IS NULL
      AND fields_featured.name = :field_featured
    )
    AND content.status = :status_1
  )
ORDER BY content.publishedAt DESC

ct0: entries
featured_1: 1
status_1: published
field_featured: featured
```

**Comment by ntomka** [comment]
I've tried a fresh install, then an install of stable Bolt version 4, all the same results.  Even tired mariadb on Bolt 4.

I admit that this is another problem, not related to the exception.

**Comment by ntomka** [comment]
Should I open a new issue for this?

**Comment by bobdenotter** [comment]
@ntomka Feel free to add addtional findings here. After Ivo's fix, it seems to work for me, but that doesn't mean there isn't something else wonky in this part. If needed, we can always edit the title to reflect the contents of the thread, if needed. :-)

**Comment by ntomka** [comment]
Thank you. Then I don't know what's wrong on my side. :D Can you add some advice how can I debug this out?

**Comment by bobdenotter** [comment]
@ntomka Not yet, sorry.. Let's leave this one open for now. I've added it to the Milestone for v5. 

One question: Do you have a Bolt v4 present on the same setup? I'd be interested to see if that makes a difference. 🤔 💭

**Comment by ntomka** [comment]
As I wrote before I tried clean installations just to test this out:

> I've tried a fresh install, then an install of stable Bolt version 4, all the same results. Even tried mariadb on Bolt 4.

I use docker-compose if it matters.

**Comment by bobdenotter** [comment]
Ah, I missed that. Then it's likely a bug in v4, and not strictly related to the v5 beta. 

Not sure how to fix it yet, though. 🤔

**Comment by ntomka** [comment]
Is it? I don't even sure about this is a bug, rather it is working as intended. I mean with setParameter the boolean type in doctrine [converted to integer](https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#mapping-matrix). But `JSON_EXTRACT` in SQL returns the exact true/false boolean value from the serialized string. Obviously this will never equals in SQL.

What I don't get here why do we experience different results. :thinking:

**Comment by I-Valchev** [comment]
Hey @ntomka , I'm looking up a different issue when I stumbled upon the piece of code that _should_ handle the checkboxes:

https://github.com/bolt/core/blob/a835b4b08386527986aa755580dd5ce6004a6916/src/Storage/SelectQuery.php#L182-L184

This is meant to _not_ parse the `true` or `false` in the `setcontent` to a string, hence preserving it as `true` or `false` for comparisons in SQL.

Can you check if it goes wrong here?

**Comment by ntomka** [comment]
No. What I'm talking about is this line:

https://github.com/bolt/core/blob/a835b4b08386527986aa755580dd5ce6004a6916/src/Storage/SelectQuery.php#L328

As I mentioned earlier boolean values in doctrine converted to integer here.
Let me show you how the result looks when I copy the generated SQL to PHPMyAdmin:

![image](https://user-images.githubusercontent.com/2313363/117808795-9d8e8d80-b25d-11eb-80c8-dd60e13dbc82.png)

And If I change the value to true from 1:

![image](https://user-images.githubusercontent.com/2313363/117808952-d29ae000-b25d-11eb-99e4-dc4818b00e6d.png)

3 is the correct result.

**Comment by ntomka** [comment]
I've came back with another info. Check this bugreport: https://bugs.mysql.com/bug.php?id=90469

> What you are seeing is the intended behaviour. We chose to make comparisons of JSON values treat booleans and numbers as different in order to make comparisons consistent with sorting. When you do ORDER BY json_col, you don't get a result where booleans come interleaved with the numbers such as {-2, -1, false, 0, 1, true, 2, 3}, but instead {-2, -1, 0, 1, 2, 3, false, true}, and we didn't want values that sort differently to compare as equal.
> 
> If you want to conflate numbers and booleans when doing comparisons, you would have to cast the JSON operand to a numeric type:
> 
> mysql> select cast(json_extract('{"b":true}','$.b') as signed int) = 1;
