### ISSUE TITLE
Edit Permissions links to edit general configuration (config.yaml)

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#2590]
Hi I just bumped into this.

The button "Edit permissions" in `/bolt/users` links to the wrong configuration file. 

![Capture](https://user-images.githubusercontent.com/6607455/118785574-460da480-b891-11eb-85d8-606389111bb7.JPG)

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 5.0.0 beta 6
| Install type                   |  Composer install 
| BC Break                     | no
| PHP version                 | 7.3
| Web server                  | Symfony local server

### Expected result

Link to edit page of `permissions.yaml` configuration file

### Actual result

Link to edit page of `config.yaml` configuration file

**Comment by bobdenotter** [comment]
Fixed in #2591
