### ISSUE TITLE
Default value of checkbox should be unchecked or 0

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#2593]
When adding a checkbox field to a contenttype, the content editor sets it to "checked" or "1" (don't know which one exactly) by default. 

This can be changed by adding` default: 'unchecked'` to the field but I think it should not be checked by default.
Example:

```
my_checkbox_field:
    type: checkbox
    default: 'unchecked'
```

_Besides this I have the feeling that a checkbox value isn't consistent throughout the Bolt system. Sometimes I have to use 0 or 1 and sometimes "checked" or "unchecked". Is there a logical explanation for this?_

Details
-------
Bolt 4.1.19 + Bolt 5 beta 6

**Comment by Virprince** [comment]
For me only  `default: '0'` works on Bolt 4.1.22

Without the default option:

- If the checkbox field is in a content created by a form submit (bolt/form), the value returned is `null` in twig dump  
When i open the edit content page in backoffice for the first time after creation, the checkbox is visualy checked
When i register the content without touching the checkbox, the field register as checked.

- If I create a new content, checkbox field is checked by default and register as checked if i don't uncheck it.
