### ISSUE TITLE
Refactor Bolt Storage `DirectiveHandler` classes as services

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#2637]
All these classes:

https://github.com/bolt/core/tree/4.1/src/Storage/Directive

Mainly, the `OrderDirective.php` now requires a lot of services for it to create a proper order query. But it's not a service at the moment (having naturally grown):

https://github.com/bolt/core/blob/0916ee977a04f1147f987304421081a8957f5285/src/Storage/FrontendQueryScope.php#L83
https://github.com/bolt/core/blob/0916ee977a04f1147f987304421081a8957f5285/src/Storage/ContentQueryParser.php#L124

If we convert them into services, we won't need to instantiate them manually anymore.

**Comment by bobdenotter** [comment]
Ha, I was just looking at the huge list in the constructor earlier today, and wondering if we could improve this! 

Needless to say, i'm all for this. 👍

**Comment by I-Valchev** [comment]
Ha, nice! ^^

**Comment by I-Valchev** [comment]
Fixed in #2638
