### ISSUE TITLE
Saving with empty title can generate empty slug

### ISSUE THREAD

**Issue by Puddingboy** [bolt/core#2718]
![127 0 0 1_8000_bolt_edit_10](https://user-images.githubusercontent.com/4963787/124883031-3aa54280-dfd1-11eb-8c24-9a7e23487f4e.png)

If you leave the title empty. It generates an empty slug. 
The empty slug persists after the first save unless changed manually.

This is an issue, because users may be inclined to think of a title later after which the slug is already set.
Doing so causes the "view saved version" link to reload the backend page in a new tab instead of opening the actual saved version because the slug is invalid. There is no signal to point users to the actual issue, which is the empty slug.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 5.3.2 
| Install type                   |   Composer install 
| BC Break                     | yes/no
| PHP version                 | 7.3
| Web server                  | Apache / Nginx / Built-in, version [ version ] < really?
| For UX/UI issues        | Brave > Chromium <<<< really this doesnt matter here

Reproduction
------------

create record without title > save > forget to change slug > attempt to open saved version of page

### Bug summary

empty slugs don't throw errors

### Specifics

It's a simple issue. doesn't get more specific than this.

### Steps to reproduce

* create record without title 
*  save 
*  forget to change slug
*  attempt to open saved version of page

### Expected result

some kind of error or notice slugs are not allowed to be empty if I try to open saved version

### Actual result

record edit page keeps opening in new tab

*sorry for the originally large picture format

**Comment by bobdenotter** [comment]
Moved this to the correct repository: `bolt/core`
