### ISSUE TITLE
"contentlink" doesn't properly recognize internal links

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#2723]
see screenshot: 

![Screenshot 2021-07-21 at 07 23 50](https://user-images.githubusercontent.com/1833361/126435404-9bd31047-3195-44b9-8ab3-d5a63261cdcc.png)

On the frontend, this doesn't link to `/page/news`, but rather to `page/news`, which is problematic, because if you're already on a subpage, it'll effectively link to `/page/page/news`

**Comment by I-Valchev** [comment]
After looking it up with @bobdenotter , turns out this works fine. We need to make sure to use `absolute_link` rather than relative.
