### ISSUE TITLE
4.x → 4.2 update failed because passthru() is not allowed

### ISSUE THREAD

**Issue by DamShaa** [bolt/core#2751]
After updating to Bolt 4.2, composer throw this error :
passthru() has been disabled for security reasons

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.2
| Install type                   |  Composer install
| BC Break                     | no
| PHP version                 | 7.3
| Web server                  | Apache

Reproduction
------------

### Bug summary

Some host (Planethoster in my case) does not allow the usage of some PHP functions (disable_functions), then the usage of post-update-cmd by composer throw an error when updating to Bolt v4.2

### Steps to reproduce

Following the procedure from https://github.com/bolt/core/discussions/2731
On the last step, the composer update command throw this error : [ErrorException]  passthru() has been disabled for security reasons

Why not using the Symfony Process Component instead of  passthru() in Bolt\ComposerScripts ?

**Comment by bobdenotter** [comment]
> Why not using the Symfony Process Component instead of passthru() in Bolt\ComposerScripts ?

We don’t instantiate the symfony kernel in those scripts. They are intended to keep on working, if for some reason bolt itself is broken. That said, it does sound like a good idea to see if we can use the Process Component, instead of plain `passthru()`. :-)
