### ISSUE TITLE
Bug when upgrading from 4.2.0 to 4.2.1

### ISSUE THREAD

**Issue by levincem** [bolt/core#2780]
Hi, 

I've made the upgrade to bolt 4.2.1 and i don't have the side bar of the admin anymore.. No menu shows.
I'm in prod mode, debug 0. I've emptied the var/cache directory, and nothing shows up.. ?

When i try to change in mode dev, debug 1, the bottom web debug bar shows 0 error, 0 warning, 228 deprecations

I've also tried log out / log in again, with no changes

What should i do ?

**Comment by bobdenotter** [comment]
Duplicate. Please see #2768 for the fix.
