### ISSUE TITLE
Empty slug field when saving a record without title

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#2809]
If your contenttype uses a "title" field to create a slug (Bolt's out of the box behaviour) no slug is added when a user saves the record without adding a title.
Also, when adding a title later, the slug field remains empty.

I made a screencast to show you what happens:
https://www.dropbox.com/s/8kdcd7yyigcaw9d/Screen%20Recording%202021-08-30%20at%2016.19.27.mov?dl=0

This results in records not having a valid url in the frontend templates.

---
Bolt 5.0.0 b14

**Comment by Puddingboy** [comment]
I think our issues are related:
https://github.com/bolt/core/issues/2718
