### ISSUE TITLE
dh tag not supported in HTMLPurifier

### ISSUE THREAD

**Issue by Joossensei** [bolt/core#2825]
### If you add the `dh` tag to the allowed html tags in the `config.yaml` it will return that it is not supported (See screenshot for more info).

![Screenshot 2021-09-09 at 13 39 03](https://user-images.githubusercontent.com/40595903/132679266-befd6488-1937-4fc7-bf66-3958f7e03b57.png)

**Comment by bobdenotter** [comment]
I don't think `<dh>` is an existing tag.. https://developer.mozilla.org/en-US/docs/Web/HTML/Element

Why do you need to be able to have this tag whitelisted?

**Comment by Joossensei** [comment]
I came across while upgrading from Bolt 3 to Bolt 5. In the Bolt 3 it was supported.

**Comment by Joossensei** [comment]
Was about an older HTML tag which isnt used anymore
