### ISSUE TITLE
Queries issues with v5

### ISSUE THREAD

**Issue by Sandrine-D** [bolt/core#2858]
Hello,

I upgraded in V5 from V4.1  and now all my queries with a field like `field:"a || b"` or `field:"!a"` don't work.

### Bug summary

`{% setcontent records = 'articles' where { type:'a || b || c' } limit 500 %}`
**An exception has been thrown during the rendering of a template ("Too many parameters: the query defines 5 parameters and you bound 7").**

`{% setcontent records = 'articles' where { type:'!a' } limit 500 %}`
No error but returns nothing (worked fine with V4.1)

| Question                                              | Answer
|------------------------------------ | ------
| Relevant Bolt Version                          | 5.0
| Install type                                           |  Composer install 
| PHP version                                          | 7.2 |
| Web server                                           | Apache
| For UX/UI issues                                   | Safari

Thank you for your support

**Comment by Joossensei** [comment]
Hi! I cant seem to reproduce this issue in the newest Bolt version (5.0.7). Can you update to the newest version of Bolt (5.0.7) and see if this fixes it?
