### ISSUE TITLE
Since upgrade to Bolt 4.2, admin sidebar menu is empty

### ISSUE THREAD

**Issue by jovuk** [bolt/core#2862]
Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 |  4.2
| Install type                                          |  Composer install 
| <abbr title="Backwards Compatibility">BC</abbr> Break | yes
| PHP version                                           | 7.4 |
| Web server                                            | Nginx 
| For UX/UI issues                                      | Firefox / Chrome

Reproduction
------------

### Bug summary

Since migrating from Bolt 4.1 to Bolt 4.2.1  the admin sidebar menu is empty. I've tried everything already said in #2771, #2768 and #2780. 
Also well configure composer.json as https://github.com/bolt/core/discussions/2731. 
Not a clue why it s happening

### Specifics

    URL impacted: /bolt/ and all the URLs in the inside
    Bolt version: 4.2.1, upgraded from 4.1 with Composer

### Expected result

A menu should be displayed in the sidebar.

### Actual result

empty menu

``

![Screenshot from 2021-10-12 14-50-58](https://user-images.githubusercontent.com/65944225/136960124-0eb994e1-0734-4a14-80ff-2066679fab6b.png)

![129364693-380390bd-bb3c-4710-a37d-48cacfe86b65](https://user-images.githubusercontent.com/65944225/136960394-4a249677-ce9f-4023-a189-87eb8bcfc291.png)

**Comment by nestordedios** [comment]
Hi @jovuk,

This no longer seems to be an issue.

For cleanup reason of the issues list I'm closing this one. If you still bumped into this, let us know.
