### ISSUE TITLE
Localized collections don't show up nicely in the backend

### ISSUE THREAD

**Issue by mcdennem** [bolt/core#2899]
![image](https://user-images.githubusercontent.com/49211363/139812506-9148bcb1-8950-49ec-93e2-28d4d0a627e2.png)

There buttons and the symbol are overlapping. Do you think you can take a look and see how we can solve it? @Joossensei

**Comment by Joossensei** [comment]
<img width="750" alt="Screenshot 2021-11-02 at 11 03 06" src="https://user-images.githubusercontent.com/40595903/139826367-3763bbcf-063a-4b07-bff4-c819a5dda649.png">

Maybe like this? Or do we want it specifically on the right? @mcdennem

**Comment by Joossensei** [comment]
<img width="615" alt="Screenshot 2021-11-02 at 11 19 45" src="https://user-images.githubusercontent.com/40595903/139828724-005b18dd-7c94-4a67-b838-b0412c8a4f0f.png">

**Update:**
The float-right will only be removed for the collection fields
