### ISSUE TITLE
Dynamic configuration values are not resolving correctly

### ISSUE THREAD

**Issue by aLLeXUs** [bolt/core#2909]
Dynamic configuration values are not resolving correctly from the `.env` file.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.0.6
| Install type                                          |  Composer install
| PHP version                                           | 8.0 |
| Web server                                            | Nginx

Reproduction
------------

[The documentation says](https://docs.boltcms.io/5.0/configuration/introduction#dynamic-values-for-config-settings) that we can specify settings in the `.env` file, or in a server's environment settings, but when specifying it in the `.env` file, the variable contains a value from the config (ex. `%env(FOO)%`) instead of the resolved value from the `.env` file.

### Steps to reproduce

1. Install Bolt CMS using composer.
2. Configure database.
3. Run `bin/console bolt:setup` to perform the initial setup and load fixtures.
4. Add `foo: '%env(FOO)%'` to the `config/bolt/config.yaml`.
5. Add `FOO=resolved-value` to the `.env` file.
6. Add new meta tag `<meta name="foo" content="{{ config.get('general/foo') }}">` to the `public/theme/base-2021/partials/_master.twig` file.

### Expected result

Variable resolved correctly, and the rendered pages contain a new meta tag inside the `head` block:
```html
<meta name="foo" content="resolved-value">
```

### Actual result

Rendered pages contain a new meta tag inside the `head` block, but the value is incorrect:
```html
<meta name="foo" content="%env(FOO)%">
```

The variable is getting resolved only when specifying it in a server's environment settings.

**Comment by dsdeboer** [comment]
I'm experiencing the same issue.
