### ISSUE TITLE
'View site' link is on the left side of the screen not the right side of the screen as in Bolt 3

### ISSUE THREAD

**Issue by Sander-Hub** [bolt/core#2944]
This is not actually a bug, but did not figure out where to put this:

Is it posible to move the 'View site link' on the Bolt dashoard to the right side of the screen as it was with Bolt 3

Link Bolt 5:

![Capture_link_site_Bolt5](https://user-images.githubusercontent.com/66225295/142383247-eb75de40-893d-488b-a046-d58139bf91f1.PNG)

The 'View site' link in Bolt 3

![Capture_link_site_Bolt3](https://user-images.githubusercontent.com/66225295/142383332-4e4ac767-d153-41a7-9ecf-37f26d014c46.PNG)

This will improve transition to a newer version of Bolt coming from Bolt 3. I am convinced folks keep clicking in the wrong place due to muscle memory.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.0.6
| Install type                                          |  Composer install
| PHP version                                           | 7.3
| Web server                                            | Symfony CLI

**Comment by I-Valchev** [comment]
Hey @Sander-Hub , thanks for reporting this! I understand where you're coming from, but we should not be changing the location of a button in a minor/maintenance release of Bolt 5.
