### ISSUE TITLE
Cypress tests improvements

### ISSUE THREAD

**Issue by Joossensei** [bolt/core#2961]
I think we can improve duration and readability for the cypress test by removing some of the `describe`.  Just discovered you can use multiple `it` inside a single `describe`.

I think it would look cleaner and maybe even shave some time off the cypress tests.

With multiple `it`: 
![Screenshot 2021-11-23 at 10 14 04](https://user-images.githubusercontent.com/40595903/142997757-02f60c5f-04a2-4557-b623-e935a2e37084.png)

Without multiple `it`:   
![Screenshot 2021-11-23 at 10 14 28](https://user-images.githubusercontent.com/40595903/142997813-12e3909e-2f78-4b09-9d91-58a8c735b0d9.png)

**Comment by I-Valchev** [comment]
![hell-yeah](https://media.giphy.com/media/3oFzlV2pq0nnFntAZ2/giphy.gif)

I like that!
