### ISSUE TITLE
Complete backend is suddenly English (updated)

### ISSUE THREAD

**Issue by gwbonline** [bolt/core#2998]
When I log in on Bolt, the whole backend is suddenly translated to English, even though I set the language to Dutch on my profile page.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | Bolt 5.0.7 / 5.1.0
| Install type                                          |  Composer install
| PHP version                                           | 7.3.29
| Web server                                            | Linux
| For UX/UI issues                                      | Firefox

Reproduction
------------

- After log in on Bolt, the complete backend is English
- To solve this, I have to open my profile page and save this page (without edit settings)
- Use the main menu to go to Maintenance > Translations
- When on that page, the whole backend is suddenly translated to English
- When going back, the backend is translate to the set language again

**Comment by eherber** [comment]
I can confirm this behaviour. The same happened to me with Bolt v5.1.1 and "german" set in the profile page.
The admin interface (backend) is in English and will only get switched the German after re-saving the profile page
(without making any changes).

However after next logout/login cycle the admin interface falls again back to English.

**Comment by UtechtDustin** [comment]
I also can confirm this behavior, we have the same issue as @eherber has.
If we set the language to german in the profil it works finde and anything is in german, but as soon we logout and login it's back to english. The Option in the Profile still shows german as selected language.
