### ISSUE TITLE
[RFC] - Add the possibility to sort and filter users in the backend

### ISSUE THREAD

**Issue by damien-jourdan** [bolt/core#3050]
Hey,

I want added the sort and filter on the backend listing of users.
By default, this feature is disabled, but can be activated by adding `user_show_sort&filter: true` in bolt/config.yaml

Commit:
https://github.com/oto-technology/bolt-core/commit/5f3544dba0d92a3a293f748d4300c17ad469c743

Picture :
![users](https://user-images.githubusercontent.com/40166762/149535379-0268b6b1-e104-407d-b3ae-068b6e867a00.png)

**Comment by bobdenotter** [comment]
Cool! 👍

**Comment by vlad-ghita** [comment]
+1
