### ISSUE TITLE
Fix autocomplete / search does not work for relationships 

### ISSUE THREAD

**Issue by ionutlip** [bolt/core#3054]
A brief description of the issue goes here.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.1.2
| Install type                                          |  Composer install 
| <abbr title="Backwards Compatibility">BC</abbr> Break | yes/no
| PHP version                                           | 8.0.14
| Web server                                            |  Nginx
| Database                                               |  Mysql 8
| For UX/UI issues                                      | Browser name and version

Reproduction
------------

autocomplete / search does not work for relationships

**Comment by bobdenotter** [comment]
Closed by #3055
