### ISSUE TITLE
Wee typo, but I could not find the source.

### ISSUE THREAD

**Issue by evertalbers** [bolt/core#3065]
Found this in 5.0.7. Probably should be "measurably". Groet!

![Screenshot 2022-01-26 at 17-43-45 Grow To Go](https://user-images.githubusercontent.com/3974120/151208057-c0930b93-7669-4b57-ac90-b0595913e710.png)

**Comment by fsidobre** [comment]
Hey @evertalbers, this text is coming from a dependency, you can [find the file here](https://github.com/bobdenotter/configuration-notices/blob/master/src/Checks.php)!

**Comment by evertalbers** [comment]
Thanks! Made a PR right away.
