### ISSUE TITLE
As ROLE_EDITOR, can't save changes on any record

### ISSUE THREAD

**Issue by vlad-ghita** [bolt/core#3082]
Using default Bolt installation, when logged in as user with ROLE_EDITOR, when clicking "Save changes", I'm redirected to dashboard and with a message saying I don't have permissions.

Reproduction
------------

1. Login with ROLE_EDITOR
2. Create any record -> record created.
3. Open created record. Press "Save changes"
4. Expect to redirect to Dashboard. Alert says: "You do not have permission to access this page."

Investigation
-------------

Acces is denied due to `ContentVoter::CONTENT_CHANGE_STATUS` attribute [here](https://github.com/bolt/core/blob/master/src/Controller/Backend/ContentEditController.php#L210).

Seems `$originalPublishedAt` and `$content->getPublishedAt()` differ.

FYI @bobdenotter

**Comment by simongroenewolt** [comment]
I did a little bit of research on this issue, and I can reproduce it.

In my situation at [this line](https://github.com/bolt/core/blob/8cbe02383a3b31b71cbf3e7b3fe35ba29ceacde4/src/Controller/Backend/ContentEditController.php#L207)

    Date::datesDiffer($originalPublishedAt, $content->getPublishedAt())

The two dates are different in the milliseconds part:

<img width="376" alt="Screen Shot 2022-02-20 at 14 17 31" src="https://user-images.githubusercontent.com/3960/154844617-3c1fe421-90cd-4462-8f1b-e889c9044461.png">

My guess it the millis part is left out when it is displayed on the edit page, and therefore missing when 'posted back' to the controller.
