### ISSUE TITLE
Select field with 'allowempty' set to true, does not allow empty field

### ISSUE THREAD

**Issue by Sander-Hub** [bolt/core#3106]
While importing content from a yaml export file.

The specific field did not contain any data:

![Capture_null](https://user-images.githubusercontent.com/66225295/156376824-bfbe4067-6d49-48cd-880e-82a62f49a12e.PNG)

The select field defined options in the contenttypes allows for an empty value and is not required

![Capture_selectfield](https://user-images.githubusercontent.com/66225295/156377200-21664651-62c0-4b6c-9998-840f2b9850c8.PNG)

When checking in the dashboard however said field did not allow empty or no value, instead 'some' value was used.

![Capture_weird](https://user-images.githubusercontent.com/66225295/156377647-812bcba1-64dd-4e83-aeed-bd12795acf80.PNG)

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.1.3
| Install type                                          |  Composer install
| PHP version                                           | 7.3
| Web server                                            | Symfony

**Comment by jordanaubert** [comment]
I'm facing the same situation, if you set the `multiple` value to `false`, you can empty your field then save. There will be still a value set in the field but when you check the `bolt_translation` table, there is no value associated to the field, meaning it's really empty and the value displayed is used as a "placeholder". Still a bug to me tho.
