### ISSUE TITLE
setcontent and '!' condition = error

### ISSUE THREAD

**Issue by AltB** [bolt/core#3130]
Use of '!' for filtering setcontent in twig result in QueryException (An exception has been thrown during the rendering of a template ("Too many parameters: the query defines 4 parameters and you bound 5").

Example from documentation:
{# get all products where price is not empty #}
{% setcontent myproducts = 'products' where { price: '!' } %}
 
Tested and reproductible with bolt 5.x (php 7.4/8x)

**Comment by Joossensei** [comment]
Hey @AltB! I've found a fix which will work for now.

Example query:
`{% setcontent myproducts = 'products' where { price: '!""' } %}`

This should return only the records where the specified field is empty.

**Comment by AltB** [comment]
This always not working on string !
Example :
{% setcontent myproducts = 'products' where { sometring: '!""' } %}
Does not return products records with sometring field not empty

**Comment by Joossensei** [comment]
You could also try to switch the single and double quotes around.
`{% setcontent myproducts = "products" where { sometring: "!''" } %}`.
I'm not sure if it'll work but it's worth the try.

**Comment by AltB** [comment]
This is not working for empty/null value... Tested all case with strings not working (directly editing db).

**Comment by Joossensei** [comment]
There is an alternative huge workaround which will work but requires a bit more work.
You can use `|filter` to 'filter' out the records with that specific field not filled in.

This causes some unexpected behavior with the record listing. The 'filtered' records get set to a sort of hidden mode which leaves a lot of 'holes' on the site where the records should be.

To fix this you can use the [paginate](https://github.com/bolt/core/pull/2994) function which rearranges the records into one list, without holes, again. 

I hope this will partially fix the problem. If you need any help don't mind asking 😊
