### ISSUE TITLE
findParents() is named incorrectly, _and_ the function is not in use

### ISSUE THREAD

**Issue by simongroenewolt** [bolt/core#3140]
The function [findParents()](https://github.com/bolt/core/blob/39f9eccbdb8da207215326f4cd602180dae37b26/src/Repository/FieldRepository.php#L126) in FieldRepository.php is incorrectly named (If it finds anything, what it will return are children). It is not used anywhere in the project. I'd say it would be a good idea to delete it to prevent future confusion.

**Comment by simongroenewolt** [comment]
Of course I'll gladly make a PR, but that might be overkill for this change?

**Comment by bobdenotter** [comment]
Yeah, probably a leftover from old code. I'll make a 'quick pr', just so it'll run the tests! 👍
