### ISSUE TITLE
De-randomize cypress tests

### ISSUE THREAD

**Issue by simongroenewolt** [bolt/core#3175]
The cypress tests are dependent on the seeded content in the database. At a couple of points this seeded data uses 'random' to generate various situations. At least at one point I think I've located an issue that will trigger 'random' failures in the cypress tests -- this is confusing, especially for new contributors.

The location I've noticed is here: https://github.com/bolt/core/blob/57936b8ac131104f9babaaaeb5b252f5d6503dc3/src/DataFixtures/ContentFixtures.php#L97 where entries are assigned a random 'owner'. Tests like this https://github.com/bolt/core/blob/55e51836abebe8fa7574d7c488f5ace9a4935293/tests/cypress/integration/record_listing.spec.js#L11 assume there will be max 5 entry-items with admin as owner, but the randomness can definitely assign more entries to owner 'admin'.

I think it will be better to either fully remove randomness, only use seeded randomness that is fixed for both CI and development use, or not use randomness at all for things that are tested. This could be achieved by either changing the default fixtures, or creating special fixtures to be used for the tests.

**Comment by simongroenewolt** [comment]
Additionally there is a setting that allows the tests to retry twice given a certain timeout value, however, if a test was half done when the retry happened the state of the DB and UI is unknown, I've seen errors locally that were triggered by the first (unfinished) test run asserting no data, then inserting data, then timing out. The second attempt then failed on the assertion that there should be no data because that was inserted by the first (unfinished) test run.

**Comment by simongroenewolt** [comment]
I think array_rand is the main culprit -- https://github.com/bolt/core/search?q=array_rand

**Comment by bobdenotter** [comment]
In config we have: 

https://github.com/bolt/core/blob/57936b8ac131104f9babaaaeb5b252f5d6503dc3/config/bolt/config.yaml#L220-L222

Which we use here: 

https://github.com/bolt/core/blob/57936b8ac131104f9babaaaeb5b252f5d6503dc3/src/DataFixtures/ContentFixtures.php#L48-L51

Doesn't that already ensure this is working as should? 

If the seed is set, you'll get the same content every time you reset the DB.

**Comment by bobdenotter** [comment]
> Additionally there is a setting that allows the tests to retry twice given a certain timeout value, however, if a test was half done when the retry happened the state of the DB and UI is unknown, I've seen errors locally that were triggered by the first (unfinished) test run asserting no data, then inserting data, then timing out. The second attempt then failed on the assertion that there should be no data because that was inserted by the first (unfinished) test run.

This is an actual problem, yes.

**Comment by simongroenewolt** [comment]
> In config we have:
> 
> https://github.com/bolt/core/blob/57936b8ac131104f9babaaaeb5b252f5d6503dc3/config/bolt/config.yaml#L220-L222
> 
> Which we use here:
> 
> https://github.com/bolt/core/blob/57936b8ac131104f9babaaaeb5b252f5d6503dc3/src/DataFixtures/ContentFixtures.php#L48-L51
> 
> Doesn't that already ensure this is working as should?

Hmm, you are probably right since php 7.1 https://www.php.net/manual/en/migration71.incompatible.php#migration71.incompatible.rand-srand-aliases aliases the 'old' rand() to mt_rand() 

In that case I was probably thrown off by another issue and wrongfully suspected the (pseudo)randomness.

**Comment by simongroenewolt** [comment]
I'm guessing what happened is as follows: Using seeded random provides identical randomness when there are no changes, so two runs on the same code will/should have consistent results. However, for some situations a change at an unrelated piece of code will actually make the random values different. In my case: I've added a contenttype, and this changes the amount of mt_rand() calls, thereby changing the outcome of all calls that happen after those related to my new contenttype.

In my case: adding a new contenttype causes the number of "Entries" owned by admin to change, and this triggers a failure in the test "checks that an admin can sort content".

**Comment by bobdenotter** [comment]
True, if the contenttypes change, the resulting content will change as well. Not sure how/if/when we could prevent that 🤔

**Comment by simongroenewolt** [comment]
> True, if the contenttypes change, the resulting content will change as well. Not sure how/if/when we could prevent that 🤔

I agree with you that that is not preventable, but I think this is different. It is: "if the number of contenttypes changes the number of 'Entry' items assigned to author 'admin' change because they are assigned at random, and then a totally unrelated test will fail because it was written with an assumption on the number of Entries with (randomly) assigned author 'admin'.

I'd say tests should never really depend on randomly generated content if a change in the seed would break the test. I get that it is easier to use the random content to 'completely' fill a bolt cms for exploratory testing, and it is OK to me to generate 20 items with random names, and then do a test on the number of items (although I would probably generate names 'by hand' for this). 
What I'd like to prevent is if you then add a test "you should be able to sort the items", and assert the first user is 'bob' after sorting. Because 'bob' is only the first (and in the list at all!) when using one specific seed and order of calls to faker/mt_rand(). So for a test on sorting I'd say content should have been added with specific names.

**Comment by simongroenewolt** [comment]
Closing for now, I think there still is improvement possible, but that is better done in separate steps, not by 'fixing' them in one big PR or something like that.
