### ISSUE TITLE
Field type number options max and min are not working

### ISSUE THREAD

**Issue by anoukhermsen** [bolt/core#3184]
In the [Bolt 5 documentation](https://docs.boltcms.io/5.0/fields/number#options) the option to add a minimum and maximum accepted value should be available according to the documentation. But is not implemented in [`assets/js/app/editor/Components/Number.vue`](https://github.com/bolt/core/blob/5a5423d47004a7a078319c6e64e15580e3b891cc/assets/js/app/editor/Components/Number.vue)

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.1.7
| Install type                                          |  Composer install
| PHP version                                           | 7.2 |
| Web server                                            | Nginx

Reproduction
------------

Added the field as followed in the contenttypes.yaml:
```
number_of_reviews:
    type: number
    mode: integer
    required: true
    min: 0
    max: 6
```

### Bug summary

Currently the input field does not see a max or min and will increase the number in the input higher than 6

### Expected result

I would expect when filling in a number higher than 6 (in this case) it would not accept it and clicking out of the number input field it should show an error.

**Comment by Saltibarsciai** [comment]
Can this be reopened? Merged PR only sets default values, but does not take custom values from contenttypes and also no validation is set, you can enter any number above max or below min
