### ISSUE TITLE
 SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION bolt.JSON_EXTRACT does not exist

### ISSUE THREAD

**Issue by Joossensei** [bolt/core#3203]
Hi! I've been working on a website that is being deployed via FTP but I encountered a weird error saying the JSON_EXTRACT function does not exist. So I checked on my server but there the file in `vendor/bolt/core/src/Doctrine/Functions/JsonExtract.php` exists.
Here is a screenshot of the error:
<img width="1069" alt="Screenshot 2022-05-16 at 16 05 19" src="https://user-images.githubusercontent.com/40595903/168611087-65e8fc0d-78e2-4d49-9af3-ea82c7f10862.png">

I've tried to reupload the whole project a few times but this doesn't fix the issue.

Also tried reinstalling Bolt but did not help either.

**Comment by bobdenotter** [comment]
Does your `doctrine.yaml` have this line: 

https://github.com/bolt/project/blob/master/config/packages/doctrine.yaml#L36

**Comment by Joossensei** [comment]
Yes it does. I reinstalled it via composer create-project but still the same error

**Comment by bobdenotter** [comment]
Are you using Sqlite or Mysql? Might it be an older version? Is it possible to try the other? 

Alternatively, I can set up a MySql DB on one of our servers, and you can remotely connect to that (from the other server)

**Comment by Joossensei** [comment]
Its MySQL and with the following version:
<img width="356" alt="Screenshot 2022-05-17 at 08 14 53" src="https://user-images.githubusercontent.com/40595903/168741619-bb843243-bc3e-44cb-91c6-a4855636c714.png">

**Comment by Joossensei** [comment]
About the alternative im not sure if this server allows to connect to yours but its worth the try

**Comment by Joossensei** [comment]
Hey! I fixed it by using an sqlite db! Thanks for the suggestion Bob!
Im going for the 10 now 😉

**Comment by bobdenotter** [comment]
Excellent! Good luck, mate! 🥇 🎖️

**Comment by andysh-uk** [comment]
JSON functions were only added in MariaDB v10.2.3.

@bobdenotter I submitted a PR for the docs to specify this version number requirement, but looks like it isn't live yet?

PR: https://github.com/bolt/docs/pull/1238
Docs page: https://docs.boltcms.io/5.0/getting-started/requirements
