### ISSUE TITLE
Old Bolt 4 tasks/trackers list

### ISSUE THREAD

**Issue by JarJak** [bolt/core#323]
Let's keep them here as a reference.

First of all, wireframes:
---
- https://xd.adobe.com/view/30ea2c74-1f05-4e41-5b8f-77e52f9a5de5-46db/

And their trackers:
---
- file management https://github.com/bolt/bolt/issues/7611
- content fields https://github.com/bolt/bolt/issues/7610
- edit permissions https://github.com/bolt/bolt/issues/7612
- users https://github.com/bolt/bolt/issues/7613
- edit content https://github.com/bolt/bolt/issues/7609
- content type overview https://github.com/bolt/bolt/issues/7608
- navigation https://github.com/bolt/bolt/issues/7607
- dashboard https://github.com/bolt/bolt/issues/7606

Other:
---
- extension updating and changelogs https://github.com/bolt/bolt/issues/6794
- multiple contenttypes.yml https://github.com/bolt/bolt/issues/7331
- add limit to select field https://github.com/bolt/bolt/pull/7742
- more image attributes https://github.com/bolt/bolt/issues/7741

Issues with field default value (to be fixed in DBAL?):
---
- https://github.com/doctrine/dbal/pull/514
- https://github.com/bolt/bolt/pull/7477
- https://github.com/bolt/bolt/issues/7265
- https://github.com/bolt/bolt/issues/7304
- https://github.com/bolt/bolt/issues/6642
- https://github.com/bolt/bolt/issues/7739
- https://github.com/bolt/bolt/issues/7539

**Comment by bobdenotter** [comment]
Let's close this, because it's not really actionable. Feel free to open, if required.
