### ISSUE TITLE
[RFC] Add an about section field to Bolt User Entity.

### ISSUE THREAD

**Issue by abdellahrk** [bolt/core#3311]
Bolt as a CMS is used in some cases to create  blogging platforms or a news website or just a website with blogging features. In most cases like the ones I have faced, content owners will like to have a brief intro of themselves after their names and pictures on every post they create or will just want to have a page dedicated to them. This is why I am opening this RFC if I can send a PR.

How can you help?
-------------------------------
I can send a PR if this feature is valid and is suitable for most users. I already have a functional version of it.

**Comment by mankerst** [comment]
I am very interested in having this feature.

**Comment by abdellahrk** [comment]
@mankerst It has been implemented already. Just waiting for it to be validated by either @bobdenotter or any core team for me to open a PR.

**Comment by bobdenotter** [comment]
Hi @abdellahrk, sure! sounds like a nice little feature to have! :-)

**Comment by abdellahrk** [comment]
Approved by #3327
Closing.
