### ISSUE TITLE
Image select "from library" throws error

### ISSUE THREAD

**Issue by jewe** [bolt/core#3328]
For Bolt 5.2.0 beta 5 and PHP 8.1.2:
If i try to select an image by "Upload" > "from Library" the popup opens, but the request results in an error:
.../bolt/async/list_files?location=files&type=images

Bolt\Widget\Injector\RequestZone::getFromRequest(): Argument #1 ($request) must be of type Symfony\Component\HttpFoundation\Request, null given, called in .../vendor/bolt/core/src/Widgets.php on line 155

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Install type: | Packaged distribution
| Database: | sqlite 3.37.2 -
| PHP version: | 8.1.2
| Symfony version: | v5.4.13
| Operating system: | Linux - 5.15.0-43-generic
| Assets version: | 5.1.99.4
| File size upload limit: | 2 MB 
| Memory limit: | 1024M

The HTTP-request to 
.../bolt/async/list_files?location=files&type=images
fails also if the files-directory is empty.

**Comment by bobdenotter** [comment]
I thought we fixed this, recently. How did you install the beta? Perhaps try running `composer update` to get beta 6?

**Comment by jewe** [comment]
Same problem with Bolt 5.2.0 beta 6 and Assets version 5.1.99.4.

I have a local bolt installation with PHP version: 7.4.30 and "Assets version": 5.1.99.6 where everything works fine.
But if i try to update to Assets 5.1.99.6 on the PHP8-server i get the following error:
```
$ composer update "bolt/assets" 5.1.99.6
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bolt/assets ^5.2, found bolt/assets[5.2.0-beta.1, ..., 5.2.0-beta.6] but it conflicts with your temporary update constraint (bolt/assets:5.1.99.6).
 ```

**Comment by bobdenotter** [comment]
Let me repeat: Why/how did you install the beta? This shouldn't be an issue in the latest stable version.

**Comment by jewe** [comment]
In the latest stable version Bolt 5.1.17 this error is fixed. The popup opens, but the user can select images only by selecting their path in an select filed and not in a thumbnail grid.
With the latest Beta and Assets version 5.1.99.6 the very cool  thumbnail grid works now.
Thanks!
