### ISSUE TITLE
postUpdate fails while composer update

### ISSUE THREAD

**Issue by samarija** [bolt/core#3330]
"composer update" fails to complete the postUpdate - instead the "vendor/bolt/core/bin/fix-bundles.php" file is opened in the IDE.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.1.16
| Install type                                          |  Composer install
| PHP version                                           | 8.1.10
| Web server                                            | Apache  [ 2.4.47 ]
| OS | WIndows 10

Reproduction
------------

### Bug summary

After running the composer update command the postUpdate part of the process fails (timeout). At the same time "vendor/bolt/core/bin/fix-bundles.php" is opened in the IDE assigned to .php-files.

### Steps to reproduce

run composer update

### Expected result

finish the update succesfully 

### Actual result

error while runninig postUpdate

### Solution?

remove the .php ending for "vendor/bolt/core/bin/fix-bundles.php" in bin/composer-script/PostUpdateScript.php ( line 13 )

**Comment by bobdenotter** [comment]
Closed in #3331
