### ISSUE TITLE
Twig error for method "next"

### ISSUE THREAD

**Issue by jewe** [bolt/core#3335]
According to the documentation it is possible to use the twig method "next" with options:
https://docs.boltcms.io/5.0/twig-components/method/next

But the most important option "byColumn" is currently not implemented:
Error "Ordering content by column other than ID is not yet implemented"

**Comment by abdellahrk** [comment]
Hello @jewe, the ordering is only by ID i.e the next or previous items are only ordered by id. 
What do you want it to be order by? I can do that an open a PR.

**Comment by jewe** [comment]
My point was: the docs for next/previous are wrong - it is currently not possible to sort "byColumn". But this would be very helpful. In most cases items should be sorted by date or other fields.

**Comment by abdellahrk** [comment]
@jewe for my understanding and what it currently does is it sorts by id hence the error `Ordering content by column other than ID is not yet implemented`. I will open a PR as soon as I implement sorting by date as you have suggested.

**Comment by abdellahrk** [comment]
@jewe I believe this PR [](https://github.com/bolt/core/pull/3343 ) addresses the issue raised.

**Comment by jewe** [comment]
Great! Thank you!

**Comment by doenietzomoeilijk** [comment]
One thing of note: my PR only adds the various date fields for ordering (created/modified/published/depublished). Selecting prev/next by another field from your contenttype definition is, as of yet, still not possible. Adding that would be _possible_ but a lot trickier than the dates.
