### ISSUE TITLE
Update .env files config

### ISSUE THREAD

**Issue by JarJak** [bolt/core#334]
Details: https://symfony.com/doc/current/configuration/dot-env-changes.html#updating-my-application

More about it: https://symfony.com/blog/improvements-to-the-handling-of-env-files-for-all-symfony-versions

After all, call `composer sync-recipes --force` from https://symfony.com/blog/new-in-symfony-flex-1-2

**Comment by bobdenotter** [comment]
Calling `composer sync-recipes --force` breaks a _lot_ of things. We should leave this as-is.
