### ISSUE TITLE
The FrontendMenuBuilder doesn't check if the contentType exists

### ISSUE THREAD

**Issue by clem** [bolt/core#3471]
When menus on the frontend are built, the builder does not check if the related contentType exists, it assumes that it does.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | master
| Install type                                          |  GitHub checkout
| <abbr title="Backwards Compatibility">BC</abbr> Break | no
| PHP version                                           | 8.2 |
| Web server                                            | Built-in

Reproduction
------------

### Bug summary

* Create a menu item with a link like `whatever/an_existing_slug` (with `an_existing_slug` that really exists as a ContentType slug)
* Display the menu on the website
* The url of the menu item does not match the provided link

### What's next?

I will create a PR to fix this issue 😊

**Comment by bobdenotter** [comment]
Fixed by #3472
