### ISSUE TITLE
🎨 Make a new `base-2020 traditional` theme

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#40]

**Comment by bobdenotter** [comment]
Bump, @Dsduit  ;-)

**Comment by zomars** [comment]
Is there a design for this? Or how could I help?

**Comment by Dsduit** [comment]
I just added the base html to the bolt/themes (base-2020). It work in progress and currently needs a good header solution with a navigation. Besides that it needs to get the tags and everything to let it work with Bolt4

**Comment by bobdenotter** [comment]
Link: https://github.com/bolt/themes/pull/32

**Comment by bobdenotter** [comment]
This is done!
