### ISSUE TITLE
Refactor "uploader" file handling

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#402]
We currently use https://github.com/siriusphp/upload under the hood to handle uploads, but it requires us to pass in `$_FILES` instead of `$request->files->all()`. We should investigate if we want to remedy this. 

Three options: 

 - We fix sirius/upload, and upstream the fix
 - We use SF's upload mechanisms
 - We use VichUploaderBundle

**Comment by adrianmiu** [comment]
I'm the author of siriusphp/upload and I just want to tell you that I've upgraded the code to PHP 7.1+ and bumped the version to 3.0.0
Other people requested implementing support for PSR-7's UploadFileInterface but I think more people are using Symfony's File which are closer to $_FILES and easier to adjust for.

**Comment by adrianmiu** [comment]
I've added support for Symfony Files https://www.sirius.ro/php/sirius/upload/integrations.html

Is it what you wanted?

**Comment by bobdenotter** [comment]
@adrianmiu That is great news! Sounds like just what we needed. :-D

Thank you for the update. We'll be sure to update our implementation to the new version.
