### ISSUE TITLE
Remove PagerFanta, in favor of Doctrine Paginator

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#444]
We're currently using PagerFanta, but the current developers are looking for new maintainers. https://github.com/whiteoctober/Pagerfanta/issues/278

We're _already_ using Doctrine, so this might be a good moment to start using Doctrine's Paginator instead. Two less Composer requirements! 

See also: https://github.com/symfony/demo/pull/991

**Comment by stof** [comment]
Note that you are already using Doctrine's Paginator, as Pagerfanta uses it for the low-level pagination.
What the Symfony demo did is replacing Pagerfanta with its own custom code, not replacing it with Doctrine's Paginator.

**Comment by bobdenotter** [comment]
@stof Yes, that's correct! Thanks for the clarification. :-)

**Comment by harikt** [comment]
I would like to pick this issue if this is still relevant when I get some time. Do we need to move something similar to how symfony/demo did ?

**Comment by bobdenotter** [comment]
@harikt Yes, exactly.. 

We'd only need to think about if it impacts convenience for the user.. Right now pagerfanta works both in the frontend as well as in the backend. If we replace it, we can perhaps make a nice snippet for the frontend theme's, so that it'll be a smooth replacement for them. :-)

My colleague @nestordedios already did some work on this, in this branch, but it's not quite finished: https://github.com/bolt/core/tree/feature/doctrine-paginator

**Comment by bobdenotter** [comment]
Since the pager in the frontend uses "helpers" now, so the implementors have more control over what the pagers look like, IMHO this issue has no priority at the moment. 

Moving to the backburner.

**Comment by bobdenotter** [comment]
Pagerfanta found a new home, so I don't see the need to replace it anymore. Closing this (at least for now)
