### ISSUE TITLE
Make backend responsive

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#474]
The backend works OK-ish on Desktop formats. It looks crappy on mobile. Should be improved

**Comment by bobdenotter** [comment]
Also: Check is how we use "Grid" is OK.. If not, either use Grid properly or refactor to Flexbox

**Comment by sbonardt** [comment]
IMO we should rework this and start mobile first. @anketwokings, @sbonardt and anybody interested are thinking about streamlining this and getting this in properly

**Comment by sbonardt** [comment]
Made changes for wide screens. Still WIP and under development, but already a usable solution

**Comment by sbonardt** [comment]
The backend is now responsive, mobile first. I would still like to rewrite all classes as this isn't BEM, but I'll save that for another issue and PR.

The 'admin__body--container' is the main css Grid container for the content. It has 12 columns. The sub element 'admin_body--main' is by default 12 columns wide. If there is anything present in the sidebar region this container gets the additional class 'admin__body--container--has-sidebar' and a sub element 'admin_body--sidebar'. The 'admin__body--main' element will then be 9 columns wide and the 'admin__body--sidebar 3 columns'

Sub elements like content-listings or fields can inherit/work upon this grid.

There are still some tweaks and alignment improvements to be made in the near future.
