### ISSUE TITLE
[RFC] We should add an "article" or "blocks" editor

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#524]
You know, one of those things where you can dynamically add blocks of content. Easy and straightforward for editors. Some options:

- A standalone version of Gutenberg: https://github.com/front/g-editor
- Imperavi's Article: https://imperavi.com/article/ ($$$, not Open Source)
- Codex / Editorjs: https://editorjs.io/ 

Noteworthy mention: Statamic's Bard looks neat, but it's not available for use in other projects than Statamic: https://v3.statamic.com/blog/fullscreen-bard

## Some screenshots: 

Bard:
![bard-fullscreen](https://user-images.githubusercontent.com/1833361/61023591-d849e500-a3aa-11e9-814c-107d4e4dd930.png)

Codex / EditorJS:
![Screenshot 2019-07-11 at 07 05 21](https://user-images.githubusercontent.com/1833361/61023592-d849e500-a3aa-11e9-9a79-104a2bb930ca.png)

Drupal - Gutenberg:
![Edit Basic page Introducing a new way to Drupal - Drupal Gutenberg - Edit Basic page Introducing a new way to Drupal - Drupal G… 2018-07-13 10-15-30](https://user-images.githubusercontent.com/1833361/61023593-d849e500-a3aa-11e9-9beb-1f5a927476fe.png)

Article:
![Screenshot 2019-07-11 at 07 09 11](https://user-images.githubusercontent.com/1833361/61023594-d849e500-a3aa-11e9-936d-da99c3647a7b.png)

**Comment by doenietzomoeilijk** [comment]
I'm hugely in favor of having an editor like this, as long as I'm able to come up with custom block types that I can add. Currently I tend to set up pages as a short bit of content with a blocks field of different types of content, I'd say this could/should be able to replace that. At least CodeX seems to be able to do just that, from a cursory glance at the site - we'd need to make sure that this could also be done through a contenttype / extension, and not just by completely rebuilding a "master" JS file.

**Comment by twwd** [comment]
Such thing would be really awesome! From my point of view, it really important that the developer has total control over the generated markup (which is e.g. not the case for WordPress' Gutenberg).

There also some other Open Source alternatives:

### [GrapesJS](https://grapesjs.com/)

- [Demo](https://grapesjs.com/demo.html)
- License: BSD 3-clause

![grapesjs](https://user-images.githubusercontent.com/8222565/61041902-6fc32e00-a3d3-11e9-8621-9e129d9ffaad.png)

### [Hyper Editor](https://github.com/DivineITLimited/hyper-editor)

- [Demo](https://divineitlimited.github.io/hyper-editor/demo.html)
- License: MIT

![hyper-editor](https://user-images.githubusercontent.com/8222565/61041975-92554700-a3d3-11e9-85cf-559fdd0b647b.png)

**Comment by harikt** [comment]
Nice collection of new editors. I am in favour of opensource editors than going with properitery. 

The one I like more is :  https://editorjs.io/

Another one I know is :  http://getcontenttools.com/ . But I don't think it is better than editorjs as I noticed now.

**Comment by 0spinboson** [comment]
I'd say stylistically, editor.js or alternatively hyper editor are good fits, though I'm already running into small issues with using the both of them (as a relative novice ~WYSIWYG CMS user). 
GrapesJS seems like a gutenberg clone that may be preferable over Gutenberg.

**Comment by bobdenotter** [comment]
So far, I think GrapesJS looks nicest. I haven't looked into how much effort it'd be to integrate, though. :-)

**Comment by 0spinboson** [comment]
> So far, I think GrapesJS looks nicest. I haven't looked into how much effort it'd be to integrate, though. :-)

yeah, on reflection none of these really seem very logical fits with bolt's contenttype-fields approach.

**Comment by bobdenotter** [comment]
Let's close this, now we have Article and Redactor
