### ISSUE TITLE
UI backend: states, buttons, ui-info colors

### ISSUE THREAD

**Issue by sbonardt** [bolt/core#555]
Revisit and check all button state, lins state, ui-info and messaging colors to bring these more in line with each other. Is already in place for 75%, but refinements needed. Discussion needed.

- Button colors
- Links
- Headings
- Button sizes (like paging and view mode buttons on listings need same look&feel)
- View mode buttons now not in line with UI.

**Comment by sbonardt** [comment]
I really do not like the greenish color of the edit button (dashboard page) and various other buttons in V4 (image upload, date, etc). To me it feels kind of too much in combination with the publish status colors and main button colors. I do lik the main 'save'/action button (green) end the 'preview' button color (blue)

I believe if we tone this action/adit button down a bit the whole CMS will feel more consistent. So, my suggestion is using the blue'ish (instead of defaulting to grey again) from the topbar as the color for those buttons as well.

See below screenshots of  1 the dashboardUI as is, 2 with the proposed color and 3 a screenshot of the edit record page with the proposed color:

1.
![Screenshot 2019-10-21 at 12 27 48](https://user-images.githubusercontent.com/5597447/67198307-0190fd00-f3ff-11e9-9356-e0f9c326b6f2.png)

2.
![Screenshot 2019-10-21 at 12 29 07](https://user-images.githubusercontent.com/5597447/67198306-0190fd00-f3ff-11e9-8e64-c9cc142c65b8.png)

3.
![Screenshot 2019-10-21 at 12 29 43](https://user-images.githubusercontent.com/5597447/67198305-00f86680-f3ff-11e9-89cb-3d0b3c09c6a2.png)

**Comment by xiaohutai** [comment]
Something like this should be defined in a kitchensink, pattern library, style guide, or design system. To see how many variants exist and what the purpose is for each variant.
~Sometimes~ Often—and probably in this case too—having less options is better.

That said, I personally like the blue version (No. 2) 👍

**Comment by bobdenotter** [comment]
Like @xiaohutai says: The kitchensink contains all current button variants. Feel free to make modifications there. I'm not attached to the colors we're currently using. I'd prefer to keep the "Primary" (a shade of) green, and "Danger" (a shade of). Secondary and Tertiary buttons can be changed, and their usage can be shifted around.

**Comment by bobdenotter** [comment]
Closing for now, not actionable enough. 

(if somebody has bandwidth to work on this, they're more than welcome, of course!)
