### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by osstap1989** [bolt/core#643]
Has anyone ever had the same issue when running this command?

> Executing script cache:clear [KO]

> Script` cache:clear returned with error code 1
> !!  In ContainerBuilder.php line 1025:                                                                             
> !!    You have requested a non-existent service "php_translation.edit_in_place.activator".                                                                                                                                                  

> Script @auto-scripts was called via post-update-cmd

**Comment by bobdenotter** [comment]
Needs more info.. What did you do? When are you getting this?

**Comment by osstap1989** [comment]
clone the project from master-branch and run the command "composer install"

**Comment by bobdenotter** [comment]
.. so precious little information.. 

For me it works.. this is the last part of the output: 

```
  - Installing symplify/package-builder (v5.4.16): Loading from cache
  - Installing symplify/better-phpdoc-parser (v5.4.16): Loading from cache
  - Installing slam/php-cs-fixer-extensions (v1.19.1): Loading from cache
  - Installing symplify/coding-standard (v5.4.16): Loading from cache
  - Installing symplify/easy-coding-standard (v5.4.16): Loading from cache
Writing lock file
Generating autoload files
drupol/composer-packages: Regenerating classes...
drupol/composer-packages: Done.
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [OK]
Executing script assets:install --symlink --relative public [OK]

> php bin/console bolt:info

 Bolt version: 4.0.0 beta 3, The third beta release (Git clone).
```

What kind of environment, php version are you on? Do you deliberately want to check out _this_ repo, and not `composer create-project bolt/project` instead?

**Comment by bobdenotter** [comment]
Closing, since no feedback was given. Feel free to re-open if required.
