### ISSUE TITLE
Make design for the login page

### ISSUE THREAD

**Issue by sbonardt** [bolt/core#649]
The look and feel for the Bolt login page feels out of date and a style change in general (the gradient, the colors in the gradient, the login box)

I would like to propose a login screen more in line with the backend UI, for a consistent experience

**Comment by sbonardt** [comment]
Current design

![Screenshot 2019-09-27 at 16 47 29](https://user-images.githubusercontent.com/5597447/65778601-82354400-e146-11e9-9bc5-f28db7a9727a.png)

**Comment by sbonardt** [comment]
I've created a design for the login page. I've made this more in line with the backend design that will be viewed after login, to make the experience more consistent. One thing I had to change was the color of the logo letters. I've used the main dark Bolt blue for "Bolt" and the main ilght blue for "CMS" In my opinion this ties the logo as a whole a bit more toether, while keeping the distinction between "Bolt" and "CMS".

For the look and feel of the whole screen. I've used the current styling and colors that we use in the backend now.

To me, the whole feels more in line with the backend and has a more 'calm' and 'professional' feel to it when you compare it to the current look and feel you can see above. 

![Login page Bolt 4 Desktop HD](https://user-images.githubusercontent.com/5597447/66207096-27ee3300-e6b2-11e9-9007-50cf7c6a6efc.jpg)
![Login page Bolt 4 error message Desktop HD](https://user-images.githubusercontent.com/5597447/66207097-27ee3300-e6b2-11e9-9e4c-0ac2615ac434.jpg)

**Comment by sbonardt** [comment]
I now see an inconsistency on the logo _nut_ , probably due to scaling in Sketch. Nevermind that one

**Comment by sbonardt** [comment]
@anketwokings @bobdenotter What are your thoughts about the proposed login screen above?

**Comment by anketwokings** [comment]
+1, totally agree. Looks really professional, and trustworthy. I'd say, go for it!

**Comment by bobdenotter** [comment]
Imho it's mostly "more boring", without the images. But if the consensus is that this is better, feel free to go ahead. 
Note that the `omit_backgrounds` setting at https://github.com/bolt/core/blob/master/config/bolt/config.yaml#L57 doesn't break the layout in the "create project" vs. the "git clone" versions.

**Comment by sbonardt** [comment]
Uhm, this issue is not so much about using images or not in the background... It's about the look-and-feel of the login page/form, bringing it more inline with the Bolt backend design and giving the user a bit more professional and robust feeling and expectation for how the backend looks. This ties the login and the backend more together design-wise, regardless of background-images...

But I'll go ahead on this one then

**Comment by bobdenotter** [comment]
Ah, ok.. In that case, sure! Tying it more together is always a plus.. 

Do you need the sources for the logo image?

**Comment by sbonardt** [comment]
Yes, could certainly use 'em. Where can I find them?
