### ISSUE TITLE
Update to Doctrine DBAL 2.9.3 breaks tests

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#702]
Doctrine DBAL 2.9.3 update added this particular line: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connection.php#L365

```
$this->transactionNestingLevel = 0;
```

This causes Bolt's tests to break. For example, run `composer update`, and then: 

```
$ ./vendor/bin/phpunit --testdox tests/php/Repository --stop-on-failure                                                  (disable-tests✱)
PHPUnit 7.5.17 by Sebastian Bergmann and contributors.

Bolt\Tests\Repository\TaxonomyRepository
 ✔ Search by type

In StaticDriver.php line 142:

  There is no active transaction

```

The "There is no active transaction" is caused by `DAMA\DoctrineTestBundle` trying to rollback a DB, while there's no apparent transaction going. 

It's invoked here: https://github.com/dmaicher/doctrine-test-bundle/blob/29882b0d1a815f4819126ef714931bb24a31cbaa/src/DAMA/DoctrineTestBundle/PHPUnit/PHPUnitListener.php#L39

```
        public function endTest(\PHPUnit\Framework\Test $test, float $time): void
        {
            StaticDriver::rollBack();
        }
```

I suspect this is happening in Bolt, because of how we're using the DB in `DbAwareTestCase`.  

@JarJak Since you've initially written this, could you please look into this?

**Comment by bobdenotter** [comment]
See also: https://github.com/dmaicher/doctrine-test-bundle/issues/94

**Comment by dmaicher** [comment]
I'm on vacation over the weekend. Will look into this next week :+1:

**Comment by bobdenotter** [comment]
@dmaicher Thanks in advance! Have a nice vacation! 👋

**Comment by dmaicher** [comment]
I am able to reproduce this locally now and will look into the issue today :blush: 

```
it@f5e2da3f8c45:/var/www/core  (master) $ make test
vendor/bin/phpspec run
                                      100%                                       25
4 specs
25 examples (25 passed)
661ms

vendor/bin/phpunit
PHPUnit 7.5.17 by Sebastian Bergmann and contributors.

.........................................
In StaticDriver.php line 142:
                                  
  There is no active transaction  
                                  

Makefile:60: recipe for target 'test' failed
make: *** [test] Error 255
