### ISSUE TITLE
Number field adds many 0s, overriding input

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#745]
The number field adds a lot of zeroes by default, which overrides input on save.
<img width="741" alt="Screenshot 2019-11-23 at 15 48 37" src="https://user-images.githubusercontent.com/7093518/69480566-c7a18500-0e08-11ea-9b2a-3664aea1781c.png">

**Comment by UtechtDustin** [comment]
Can not reproduce the issue.

**Comment by I-Valchev** [comment]
@UtechtDustin there were a few issues playing around, so I found out it only happens under certain circumstances. A fix is on the way #783
