### ISSUE TITLE
Duplicate items in `locales()`

### ISSUE THREAD

**Issue by DJWassink** [bolt/core#769]
Much like #694 the `locales()` method in twig theme templates return multiple locales depending on how many times a certain locale is defined in the `contenttypes.yaml`.

Currently I have 4 contenttypes with `locales: ['en', 'nl']` thus my current `locales()` looks like:
![image](https://user-images.githubusercontent.com/1822404/70169489-37e2bd00-16cb-11ea-91c2-18f118d9f6ae.png)

**Comment by bobdenotter** [comment]
@DJWassink Thanks! Fix is in the pipeline -> #772
