### ISSUE TITLE
Jumping dropdowns

### ISSUE THREAD

**Issue by UtechtDustin** [bolt/core#775]
While testing Bolt 4 i saw that the the dropdowns has a different location/offset if you hover or click on the "label".

![dropdown2](https://user-images.githubusercontent.com/13292481/70269519-dd1c9480-17a2-11ea-9f62-60ae238bee48.gif)
![dropdown1](https://user-images.githubusercontent.com/13292481/70269521-dd1c9480-17a2-11ea-8902-9cf45c782ca8.gif)

**Comment by I-Valchev** [comment]
Thanks for bringing this up @UtechtDustin 
A fix is in the pipeline #777
