### ISSUE TITLE
Log in on /bolt/login redirects back once

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#806]
Hitting /bolt/login directly, then filling in username with password and logging in, redirects back to /bolt/login.
On second login attempt, it redirects correctly to dashboard.

**Comment by UtechtDustin** [comment]
Souns like a deeplink issue(?), but i cant reproduce that issue on the master.

- Started the server (`symfony server:start`)
- Opened the login page directly (`http://127.0.0.1:8000/bolt/login`)
- Loggedin
- Dashboard was opened

**Comment by bobdenotter** [comment]
Just tested, this is no longer the case. Works as expected..
