### ISSUE TITLE
Publish Date for Draft/Revison

### ISSUE THREAD

**Issue by CCWongVR** [bolt/core#813]
Add functionality to save changes to published content type as unpublished draft, and publish those changes at set time like you would for regular publishing.

**Comment by bobdenotter** [comment]
hi, @CCWongVR . Thanks for bringing this up, this is definitely in the pipeline. The expected flow is to set it to "timed publish", after when it'll be automatically published at the set time.

**Comment by bobdenotter** [comment]
Fixed in #823
