### ISSUE TITLE
templateselect - file seems to be missing

### ISSUE THREAD

**Issue by mbursa** [bolt/core#841]
When I add 
```
template:
    type: templateselect
```
to a content type, I get a select box to select a template. When I select a file (say `template.twig`) and save the change, what I get in the select box is then `["template.twig"] (file seems to be missing)`. If I try to view the page, I get an error `Unable to find one of the following templates: "["template.twig"]", ...`

I have a fresh Bolt 4 install using composer.

**Comment by bobdenotter** [comment]
@mbursa Hi, i can confirm this issue! We'll fix it.
