### ISSUE TITLE
Create 'Add {contenttype}' button when no records exist

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#843]
Currently it can only be done from the sidebar.
Would it be a good idea to add a button on the main area? @bobdenotter 

![Screenshot 2020-01-08 at 14 07 57](https://user-images.githubusercontent.com/7093518/71980443-4ff4b180-3220-11ea-92a3-980dc0b251a0.png)

**Comment by bobdenotter** [comment]
Also from the top bar, under "Create New…". But, yeah, if there are no records, it makes sense to provide the user with an abvious choice. 👍
