### ISSUE TITLE
Show correct path in Slug field

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#844]
Currently shows '/foobar/'

![Screenshot 2020-01-08 at 14 10 32](https://user-images.githubusercontent.com/7093518/71980594-b5e13900-3220-11ea-8797-325ca4fe6650.png)

**Comment by I-Valchev** [comment]
This only happens if it's new.

**Comment by UtechtDustin** [comment]
https://github.com/bolt/core/blob/fd3a23c9f9b2e6c83cd7048eaff5f1ff1385ae2a/src/Entity/Field/SlugField.php#L40

**Comment by bobdenotter** [comment]
@UtechtDustin Ha! That shouldn't be too hard to fix, then. 😇

**Comment by I-Valchev** [comment]
Though without content, you cannot fetch the slug
https://github.com/bolt/core/blob/fd3a23c9f9b2e6c83cd7048eaff5f1ff1385ae2a/src/Entity/Field/SlugField.php#L44
