### ISSUE TITLE
Support collections inside sets

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#884]
Recursive implementation for sets and collections parsing works at most levels.
Currently, two issues prevent this:
- [ ] Generate correct html field names (see `collection.html.twig` and `set.html.twig`)
- [ ] Call correct updateField method in ContentEditController for the appropriate field type (e.g. when there is a collection inside a set, handle it as a standalone collection would be)

In theory, resolving these should make collections work inside sets.

**Comment by bobdenotter** [comment]
Nothing to see here! 🙈 

(kidding aside: This'll be really tricky to implement, and the benefits will not outweigh the work)
