### ISSUE TITLE
Fields with `date` have no time inputs.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#885]
```yaml
        foo:
            type: date
            mode: datetime
```

Should have time inputs, below the calendar

**Comment by eduardomart** [comment]
Hi,

I just tested this:
```
foo:
            type: date
            mode: datetime
```

No time input is shown.

RC 41

**Comment by develth** [comment]
@eduardomart 

have the same issue. 
While debugging the config seems good and enableTime is passed to flat-picker. Strange

**Comment by develth** [comment]
Quick Fix: 
Remove ```.showTimeInput``` so  just ```&.hasTime``` is defined.

https://github.com/bolt/core/blob/master/assets/scss/vendor/flatpickr/flatpickr.scss#L96
