### ISSUE TITLE
Make "Remember me?" work on login page. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#886]
![Schermafbeelding_2020-01-17_om_16_01_38](https://user-images.githubusercontent.com/1833361/72622102-d86f0280-3942-11ea-89d6-edcccc5d0f08.png)

**Comment by UtechtDustin** [comment]
remember me is already configured:
https://github.com/bolt/core/blob/master/config/packages/security.yaml#L35

It works fine for me (firefox & Chrome).

**Comment by bobdenotter** [comment]
Closing this for now! The main reason it didn't work (for me) was that i had multiple instances running on the same IP, which triggers the 'destroy session' as it should.
