### ISSUE TITLE
Add allowtwig option to fieldtypes

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#935]

**Comment by bobdenotter** [comment]
Like this? https://github.com/bolt/core/blob/master/config/bolt/contenttypes.yaml#L88

See also `/page/title-of-the-test` in a standard installation with fixtures.

We should make sure the docs have this listed. In short: it can be set for `text`, `textarea`, `html` and `markdown`. It's enabled by _default_ only for `html` and `markdown`. 

Thinking about this, the same location in docs should probably document `sanitise: false`. This property is set to `false` for all fields, except for `text`, `textarea`, `html` and `markdown`, where it's set to `true` by default.

**Comment by bobdenotter** [comment]
Let's close the `wontfix` :-)
