### ISSUE TITLE
Add record.link() and record.canonical() functions

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#937]

**Comment by bobdenotter** [comment]
We shouldn't do this. The old `link` in v3 was confusing. When a contenttype had a _field_ named `link`, the results of `{{ record.link }}` were confusing. In v4, this is made explicit by using the `|link` "magic attribute".

```
{{ record|link() }} -> absolute link
{{ record|link(true) }} -> canonical URL
```

I'm not closing this yet, until we're sure it's documented as such. :-)

**Comment by bobdenotter** [comment]
Fixed by https://github.com/bolt/docs/pull/1002
