### ISSUE TITLE
Support keys option for select fieldtype

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#943]

**Comment by bobdenotter** [comment]
Let's not. This caused much headaches in the v3 days. It should _only_ be ids, and we'll provide a snippet in docs how people can fetch the records, without having to change the "keys" 

(keeping open, until docs are updated)

**Comment by I-Valchev** [comment]
👍 I'll update the docs.

**Comment by bobdenotter** [comment]
I think it's sufficiently documented here, now: https://github.com/bolt/docs/blob/4.0/docs/fields/select.md#outputting-selected-options

**Comment by I-Valchev** [comment]
Yes, lets close this :-)
