### ISSUE TITLE
Support limit option for select and collection fieldtypes

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#944]
- [x] Collections
- [x] Imagelist
- [x] Filelist
- [x] Select
- [x] Multiselect

**Comment by bobdenotter** [comment]
Fix for `Select` is in #1013

**Comment by I-Valchev** [comment]
👍 I'll start with the `Filelist`

**Comment by I-Valchev** [comment]
Fix for `Imagelist` in #1017

**Comment by I-Valchev** [comment]
Fix for `Collection` in #1019

**Comment by bobdenotter** [comment]
Aren't `Select` and `Multiselect` the same in this regard? 🤔 💭

**Comment by I-Valchev** [comment]
Yes. Great, one more thing checked off  ✅
