### ISSUE TITLE
HTML and Markdown fields cannot be required.

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#995]
HTML and Markdown fields cannot be required.

Details
-------

| Question                      | Answer
|---------------------- | ------
| Relevant Bolt Version | 4.0
| BC Break                     | no
| PHP version                | 7.2 / 7.3 / 7.4 |
| Web server                 | N/A
| For UX/UI issues        | N/A

Reproduction
------------

The third-party libraries that Bolt currently uses for the HTML and Markdown editors do not support the option to make these inputs required. Thus, Bolt's `require: true` field option does not work for those fields.

### Expected result

Setting `required: true` as a field option should make HTML and Markdown fields required on the in the admin edit area.

### Actual result

The option is ignored, and fields can be left out empty.

**Comment by bobdenotter** [comment]
Imho, this is "wontfix". We didn't have this in v3, and it never was too big of a problem.

**Comment by I-Valchev** [comment]
Sure, it's also applicable for most of the options as well.

**Comment by bobdenotter** [comment]
Let's close the `wontfix` :-)
